### ISSUE TITLE
Make dependence on 0/1 mutations in ancestors ts explicit or remove

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsinfer#107]
Currently we have to have 0/1 mutation in the ancestors ts, or assertions will fail. Either

1) Make this requirement explicit and test for it or 
2) Update the input code to ignore the actual states of the values.

Probably (1) is less nasty, as we're unlikely to forget about this if we're forced to set the values to 0/1 all the time.

**Comment by jeromekelleher** [comment]
Also need to update make_ancestors_ts to allow us set these values to 0/1 appropriately.

**Comment by hyanwong** [comment]
I think https://github.com/tskit-dev/tsinfer/issues/437 is probably relevant here: we should revisit this issue as part of allowing >2 alleles in matching.

**Comment by jeromekelleher** [comment]
I'm not sure this is true any more - we're matching with arbitrary alleles in the extend operation happily (if probably slightly wrongly #437)

**Comment by jeromekelleher** [comment]
I'm going to close - we can reopen if necessary.
