### ISSUE TITLE
Remove ``convert_1kg.py`` script.

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsinfer#110]
This is also kept in another repo, so remove this copy.

**Comment by jeromekelleher** [comment]
The version in the other repo is much more complex, so we should probably keep this here as an example of how to process VCFs. Possiblity should be moved into the documentation directory though.

**Comment by hyanwong** [comment]
We now have (pretty good, I think) example of reading a VCF in the [tutorial](https://tsinfer.readthedocs.io/en/latest/tutorial.html#reading-a-vcf), so I think we can remove this completely and close the issue.

**Comment by hyanwong** [comment]
Actually, I think this file has now gone anyway. So we can close this issue.
