### ISSUE TITLE
match_ancestors documentation does not match function params

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#122]
at https://tsinfer.readthedocs.io/en/latest/api.html#tsinfer.match_ancestors, params are listed as `sample_data, path_compression, num_threads=0` but the description lists sample_data, ancestor_data, num_threads. There is no mention of path_compression.

**Comment by jeromekelleher** [comment]
Good spot, thank.

**Comment by hyanwong** [comment]
Fixed with ce3ae679b2afb003b173dd5bdc748159bb0c01ec
