### ISSUE TITLE
tsinfer ls on tree sequence does not include 'nodes'

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsinfer#124]

**Comment by jeromekelleher** [comment]
(This was developed before the tskit info command - we could just say "use tskit info")

**Comment by hyanwong** [comment]
I agree, better to have this facility in `tskit info`. Could we just do what we do there and `print(ts)`, then say in the docs that this does the same as `tskit info`.

On the other hand, there is a comment that says "# TODO Add optional tree statistics like mean degree, etc." - is this something we would want in the normal `tskit info` command too?

**Comment by jeromekelleher** [comment]
It's very crude right now - let's just delete everything we have at the moment and print(ts)

**Comment by jeromekelleher** [comment]
So: don't bother deprecating it, as we might want to put in stuff that'll help us diagnose tsinfer'd tree sequences, but replace the current implementation with ``print(ts)``.

**Comment by hyanwong** [comment]
Good plan.
