### ISSUE TITLE
Weird bug in evaluation script (ep) for different lengths

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#140]
On holly (python 3.4), when I run `python3 evaluation.py ep -l 0.1 -s 123` it works fine, but when I run with larger lengths, e.g. `python3 evaluation.py ep -l 1 -s 123`, I get a numpy reshape error after a few loops have run.

```
2018-12-28 00:21:18,969 [46291] CRITICAL root: Traceback (most recent call last):
  File "evaluation.py", line 1595, in <module>
    args.runner(args)
  File "evaluation.py", line 251, in run_edges_performance
    for result in executor.map(edges_performance_worker, work):
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 549, in result_iterator
    yield future.result()
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 395, in result
    return self.__get_result()
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 354, in __get_result
    raise self._exception
ValueError: cannot reshape array of size 2048 into shape (1024,)
```

I'm wondering if this is a python 3.4 (or associated numpy) error, since it doesn't happen on my laptop with python 3.6

**Comment by jeromekelleher** [comment]
I doubt it's a Python 3.4 thing, I would imagine that it's just different random trajectories on your laptop and holly. How easy is it to provoke on holly?

**Comment by hyanwong** [comment]
It seems to be quite easy to reproduce on holly with different random seeds. No time to look into this now but will try to triage more when I get back to the UK.

**Comment by jeromekelleher** [comment]
No hurry. Are you using an older version of numpy on holly maybe?

**Comment by hyanwong** [comment]
A very slightly older version (1.15.4 on my laptop, 1.14.5 on holly). I'll update numpy on my holly version and report back

**Comment by hyanwong** [comment]
Nope, upgrading to the latest numpy doesn't solve it:

```
yan@holly:~/tsinfer$ python3
Python 3.4.2 (default, Sep 25 2018, 22:02:39) 
>>> import numpy
>>> numpy.__version__
'1.15.4'

yan@holly:~/tsinfer$ python3 evaluation.py ep -l 1 -s 123
2019-01-03 12:39:36,480 [32862] CRITICAL root: Traceback (most recent call last):
  File "evaluation.py", line 1595, in <module>
    args.runner(args)
  File "evaluation.py", line 251, in run_edges_performance
    for result in executor.map(edges_performance_worker, work):
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 549, in result_iterator
    yield future.result()
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 395, in result
    return self.__get_result()
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 354, in __get_result
    raise self._exception
ValueError: cannot reshape array of size 2048 into shape (1024,)
```

**Comment by hyanwong** [comment]
So this does seem to be associated with python 3.4. At least, when I run the script on holly with 3.7 in a miniconda environment, it works, but with 3.4 it doesn't, using the same numpy version. I'm not sure if we want to do anything about it, or just specify python 3.6 or greater compatibility for tsinfer.

**Comment by hyanwong** [comment]
This is when running code on the "hyanwong:allow-ancestor-age-ordering" branch. So that's likely to be the difference I guess. Still, only worth re-visiting once we do something about that PR in the future.

**Comment by jeromekelleher** [comment]
OK, since this doesn't apply to master I'm going to close the issue.
