### ISSUE TITLE
Need `tsinfer upgrade` command

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsinfer#144]
#143 added the ability to specify ages for sites, and in doing so changed the Samples and Ancestor file formats. As such, the current version of tsinfer in master will not be able to read files produced by the released version.

We need to provide an upgrade path for these old files via a ``tsinfer upgrade`` CLI command. Updgrading the files will be straightforward enough, as we can just read them in with Zarr and rename a column (in ancestors) or add and compute one (in samples).

cc'ing @hyanwong  and @awohns, so that you are aware this is an issue and a solution is planned.

**Comment by hyanwong** [comment]
Presumably this also needs to account to the change from `np.uint8` to `np.int8` (allowing for missing data) in SampleData files?

**Comment by jeromekelleher** [comment]
Yes.

**Comment by hyanwong** [comment]
Also breaking changes have been (or will be) made by #186 (change "age" to "time"), #190 (add "time" to individuals, not just variants), and possibly #188 (`sites_inference` stored as `bool` rather than `np.uint8`)

**Comment by hyanwong** [comment]
New changes in tsinfer 0.3, SampleData format 5 are caused by adding `individuals_flags` and (from version 4 to version 5) using tskit.UNKNOWN_TIME rather that `-np.inf` in the sites_time column.

**Comment by jeromekelleher** [comment]
There's a bit too much to do here for 0.2.0 - I've had a look, and writing an upgrade() tool is messy. I'm going to close the issue as a "wontfix", but if someone really does need to have this functionality we can reopen. It's worth noting that tskit 0.3 is going to require a completely new file format (see #373), and we will make a lot of effort to keep things stable from there on.

**Comment by hyanwong** [comment]
Yes, agree (I think you mean tsinfer 0.3 above)
