### ISSUE TITLE
Make SampleData.sites_age editable

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsinfer#145]
It seems likely people will want to edit the age field. Make this editable like the ``inference`` column.

**Comment by hyanwong** [comment]
Not sure if this is the right place to flag this up, but tskit tends to use the word `time` rather than `age` (e.g. https://msprime.readthedocs.io/en/stable/tutorial.html#historical-samples). Should we try to make the naming consistent before too many people start using this tsinfer functionality?

**Comment by jeromekelleher** [comment]
Changing the name of ``time`` in tskit would be a major pain, so I really don't want to do that. Should we change the ``age`` field to ``time`` here? I'm OK with there being a slight difference here --- age does capture the meaning better, but consistency is also good.

**Comment by hyanwong** [comment]
Yes, I assumed that we might want to change `age` to `time` in tsinfer, since this is (currently) trivial. I'm a bit on the fence here, but it's nice not to have to look up the docs which one to use ever time.

**Comment by jeromekelleher** [comment]
> Yes, I assumed that we might want to change age to time in tsinfer, since this is (currently) trivial. I'm a bit on the fence here, but it's nice not to have to look up the docs which one to use ever time.

OK, lets to that so. We haven't released the ``age`` stuff, so we can change that as we like.
