### ISSUE TITLE
Disk quota exceeded error in zarr/storage.py

### ISSUE THREAD

**Issue by luciansmith** [tskit-dev/tsinfer#152]
Running tsinfer from python on a cluster (which has file size quota) gives me an error:
```
Traceback (most recent call last):

  File "parse_seqgen.py", line 44, in <module>

    with tsinfer.SampleData(path=outfile) as sample_data:

  File "/net/gs/vol1/home/lpsmith/.local/lib/python3.6/site-packages/tsinfer/formats.py", line 704, in __init__

    super().__init__(**kwargs)

  File "/net/gs/vol1/home/lpsmith/.local/lib/python3.6/site-packages/tsinfer/formats.py", line 256, in __init__

    store = self._new_lmdb_store()

  File "/net/gs/vol1/home/lpsmith/.local/lib/python3.6/site-packages/tsinfer/formats.py", line 314, in _new_lmdb_store

    return zarr.LMDBStore(self.path, subdir=False)

  File "/net/gs/vol1/home/lpsmith/.local/lib/python3.6/site-packages/zarr/storage.py", line 1614, in __init__

    self.db = lmdb.open(path, **kwargs)

lmdb.Error: /net/gs/vol1/home/lpsmith/tsinfer_run/50tip_native0/treedump: Disk quota exceeded
```
I was able to fix it (sort of) by changing the zarr/storage.py line from:

map_size = (2**40 if sys.maxsize >= 2**32 else 2**28)

to:

map_size = (2**28)

which is large enough for my purposes.  Just checking sys.maxsize does not help: as far as the system is concerned, you can have files much larger than 2^40.  It's the *quota* system that instead needs to be checked (somehow).

**Comment by jeromekelleher** [comment]
Thanks for the bug report @luciansmith. It's a tricky issue, as it's interacting with the upstream zarr and lmdb libraries. Most of the time the default map size for LMDB seems to work fine (see [here](https://lmdb.readthedocs.io/en/latest/#environment-class) for docs).

Probably the thing to do here is add a ``max_file_size`` argument to the ``SampleData``, which defaults to something big and which users can set themselves if they encounter errors. Does this sound like a good solution to you? 

Out of interest, what file system are you using?

**Comment by luciansmith** [comment]
The default map size for lmdb works fine!  If I call lmdb.open("filename", **kwargs) where kwargs does not have map_size defined, I get no errors.  (And so, if I comment out the 'map_size' bits in zarr, that also works).  But I don't know what's going on under the hood there when you don't send it map_size (maybe it doesn't check if the file size can get big enough, and you might run into trouble later?)

Letting the user set the filesize seems like a reasonable possibility, though in this case you'd have to let the user set it as early as 'tsinfer.SampleData(path=outfile, maxfilesize=XXX)', and all the steps inbetween.

I'm not entirely sure what the file system I'm using is, though I could probably find out if you knew a way to check?  It's linux with tcsh.

Thanks for the reply!

**Comment by jeromekelleher** [comment]
That's very interesting @luciansmith, thanks for digging here. I had a look at the zarr source and they've chosen a default value arbitrarily as well, but one which is a good bit bigger than the LMDB default. So, I think the answer for tsinfer here is to set a default value that should be bigger than any file we expect (1TB?) and provide an option for users to make this smaller for cases where quotas make mapping a large sparse file problematic.

It's a simple enough change to make, and we could add the option and push out an update pretty quickly if you'd like a fix soon.

**Comment by luciansmith** [comment]
Any timing is fine with me--I edited the zarr source so it works for me for now, so there's no rush.  Thank you!

**Comment by jeromekelleher** [comment]
OK, thanks @luciansmith, we'll tack it in with the 0.2.0 release which will probably end up being in a month or so.

**Comment by hyanwong** [comment]
@jeromekelleher - did this get solved, or do you want me to tackle it? I'm assuming it's just a question of adding `max_file_size` to the SampleData init method, and passing that to [`_new_lmdb_store`](https://github.com/tskit-dev/tsinfer/blob/3c0f497d3039d04b486791c62fe663ef87f29707/tsinfer/formats.py#L307)? We could either 

1. set the default to `None` to get the existing behaviour (use the zarr defaults if not win32) or
2. set the default to 2**30 as you suggest above, which (I guess) risks hitting the disk quota warning more often?

**Comment by hyanwong** [comment]
OK. My preference is for 1. as it doesn't change current behaviour, and is (hopeully) less maintenance for us (we can blame other libraries!). Either way, I think we should allow `None` to mean the zarr default, so we'd need to document that.
