### ISSUE TITLE
Allow truncated samples (with missing data to left and right)

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#153]
I think it shouldn't be too hard to allow samples with missing data, ~~presumably marked as a variant whose allelic state is set to `tskit.NULL`~~ using the current notation this would be an allelic state equal to `constants.UNKNOWN_ALLELE` e.g.

    sample_data.add_site(
        position=1234, genotypes=[0, 0, 1, tsinfer.constants.UNKNOWN_ALLELE], alleles=["G", "C"])

~~Allowing missing sites in the zarr storage would require setting [`sites.genotypes`](https://github.com/tskit-dev/tsinfer/blob/73ee1bad0d232a2fbe35c60804811b9e216aca34/tsinfer/formats.py#L749) to `dtype=np.int8` rather than `np.uint8`, but I guess that's fine.~~ It would need a bit of hacking to pass the various error checks, and to skip matching that bit of the sample against the ancestors. But we have the code to do that for ancestor matching anyway, so I assume it would be a reasonably easy change.

(modified to reflect the fact that we currently use tsinfer.constants.UNKNOWN_ALLELE == 255)

**Comment by hyanwong** [comment]
I'm happy to code this up, if @jeromekelleher gives it the go-ahead.

**Comment by jeromekelleher** [comment]
There's a general issue about how to represent missing data in tskit over [here](https://github.com/tskit-dev/tskit/issues/144). We'd want to use the same encoding here whichever way we do it.

But yes, definitely something we want to support; thanks!

**Comment by hyanwong** [comment]
Just some notes about my current implementation (at https://github.com/hyanwong/tsinfer/tree/allow-UNKNOWN_ALLELE-in-samples).

1. We need to allow `constants.UNKNOWN_ALLELE` in add_sites in the SampleData method, without having to specify it in the `alleles` array. This should work whether the value for constants.UNKNOWN_ALLELE is negative or positive **DONE, including tests**
2. We need to check that the Li & Stevens process allows missing data, both (a) in the reference panel against which matches occur, and (b) in the haplotype which we are trying to match **NOT DONE**
3. Any ancestral haplotypes that contain a break, such that the focal sites are separated by a region where none of the derived samples have data, should be split into separate ancestral haplotypes. **NOT DONE**
4. When matching the samples, we should only match in the region from the leftmost known allele to the rightmost known allele (unknown sites in-between are tackled by 2. above). **DONE with tests, using the trim_region function**
5. When mapping the inference sites back to original sites (in `get_samples_tree_sequence()`), we need to trim the edges in the produced tree sequence such that if there is an entirely unknown region to the left or right (no data for any of the samples), then there is no tree in that region. I think it should, however, be OK to have a tree in a leftmost region if there are non-inference sites there. **DONE, including tests**

**Comment by jeromekelleher** [comment]
Sounds great, thanks Yan!

**Comment by hyanwong** [comment]
Replaced with #224
