### ISSUE TITLE
Allow variable recombination rates in Li & Stevens process

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#154]
@jeromekelleher: I've just been chatting to Gil about issues that tsinfer has in producing too many breakpoints. The solution we discussed requires specifying recombination probabilities in the L&S process. I thought that might already be a feature of tsinfer, but I can't find it. I'm guessing this is dependent on your reworking of the L&S process. Is it likely to be implemented at any time soon (or can I help?)

**Comment by jeromekelleher** [comment]
This will be part of the next update, yes. I would very much like to get this done by the end of July.

**Comment by hyanwong** [comment]
I guess this can be closed, @jeromekelleher ? (hurrah!)

**Comment by jeromekelleher** [comment]
> I would very much like to get this done by the end of July.

yes, well that landed on time didn't it!

**Comment by hyanwong** [comment]
Cleverly didn't specify which year, though!
