### ISSUE TITLE
Outdated TODO

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#157]
In algorithm.py (https://github.com/tskit-dev/tsinfer/blob/73ee1bad0d232a2fbe35c60804811b9e216aca34/tsinfer/algorithm.py#L62) it says 

    # this implementation currently partially allows for multiple focal
    # sites per ancestor, but the final generation algorithm assumes a single
    # focal site.

But I don't think that's true any more. We are trying to allow multiple focal sites all the time now, and don't intend to go back for a single focal site, do we? So can I remove this comment?

**Comment by jeromekelleher** [comment]
Probably, yes. This file is a bit messy, there's a few different iterations of the ancestor generation algorithm coexisting, unfortunately.
