### ISSUE TITLE
AttributeError: module 'numcodecs' has no attribute 'Zstd'

### ISSUE THREAD

**Issue by mcneney** [tskit-dev/tsinfer#161]
Hello. I've installed tsinfer via pip as suggested in the documentation.  Computer is running OSX Mohave, python version 3.7.3, numcodecs version 0.6.3. Typing python -m tsinfer --help gives the following error:

Traceback (most recent call last):
  File "/Users/mcneney/miniconda3/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/mcneney/miniconda3/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/mcneney/miniconda3/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/mcneney/miniconda3/lib/python3.7/site-packages/tsinfer/__init__.py", line 37, in <module>
    from .inference import *  # NOQA
  File "/Users/mcneney/miniconda3/lib/python3.7/site-packages/tsinfer/inference.py", line 37, in <module>
    import tsinfer.formats as formats
  File "/Users/mcneney/miniconda3/lib/python3.7/site-packages/tsinfer/formats.py", line 58, in <module>
    DEFAULT_COMPRESSOR = numcodecs.Zstd()
AttributeError: module 'numcodecs' has no attribute 'Zstd'

Any ideas?

Thanks,

Brad

**Comment by jeromekelleher** [comment]
Thanks for the bug report @mcneney. I don't know what the issue is here: perhaps there some issue with building Zstd on OSX?

Can you try installing numcodecs using conda please?

**Comment by jeromekelleher** [comment]
So it looks like this is happening on Windows as well (over in #163). @marianne-aspbury, is your numcodecs installed via conda or pip? Perhaps there's an upstream issue with the conda numcodecs package - if so, it'd be worth trying to install older versions of numcodecs.

**Comment by marianne-aspbury** [comment]
As in #163 , the first numcodecs would have been installed for me by requirements from `pip install tsinfer` but running `conda install numcodecs` successfully fixed this issue (probably to do with the version of numcodecs installed?). Although I had subsequent issues, which may just be to do with windows and be fine on a Mac @mcneney

**Comment by jeromekelleher** [comment]
Thanks @marianne-aspbury - looks like a problem with the pip version of numcodecs then. @mcneney, can you try using numcodecs from conda please?

**Comment by mcneney** [comment]
Yes, works when I install numcodecs using conda. Thanks.

**Comment by jeromekelleher** [comment]
Thanks - raising this with upstream.

**Comment by brianzhang01** [comment]
I got this issue on Linux as well today when trying to install tsinfer. I installed tsinfer version 0.1.4 using pip, which installed numcodecs version 0.6.3. My OS is Fedora 30. The issue was fixed after installing the same numcodecs (version 0.6.3) with conda.

**Comment by jeromekelleher** [comment]
Yes, this is a recurring problem --- we need a conda version of tsinfer. We'll do this when we release the next version.
