### ISSUE TITLE
Fix windows build

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsinfer#163]
#162 updated the C code so that the module will build. However, the tests aren't running because LMDB can't be found. Either fix this so that the tests work or determine a reason for why we definitely can't support windows.

See [here](https://ci.appveyor.com/project/tskit-dev/tsinfer/builds/26015455) for the failing build.

cc @hyanwong @marianne-aspbury

**Comment by hyanwong** [comment]
Thanks. It seems like LMBD should be available on windows, so @marianne-aspbury and myself should investigate why this is failing.

Meanwhile, will tsinfer work without lmbd? It seems so.

**Comment by jeromekelleher** [comment]
Great, thanks. Not sure if it'll work without lmdb, and it would take a fair bit of hacking to import without it. Probably better for figure out the underlying problem I'd say.

**Comment by marianne-aspbury** [comment]
tsinfer now installs on windows, but there's an issue when I call "import tsinfer" in python, here is the output:

(base) C:\Users\mazmysta>python
Python 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tsinfer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mazmysta\Anaconda3\lib\site-packages\tsinfer\__init__.py", line 37, in <module>
    from .inference import *  # NOQA
  File "C:\Users\mazmysta\Anaconda3\lib\site-packages\tsinfer\inference.py", line 37, in <module>
    import tsinfer.formats as formats
  File "C:\Users\mazmysta\Anaconda3\lib\site-packages\tsinfer\formats.py", line 55, in <module>
    DEFAULT_COMPRESSOR = numcodecs.Zstd()
AttributeError: module 'numcodecs' has no attribute 'Zstd'

**Comment by hyanwong** [comment]
Ah, that sounds like https://github.com/tskit-dev/tsinfer/issues/161

**Comment by hyanwong** [comment]
Apparently `lmdb` installs OK on @marianne-aspbury 's windows conda install, so it's probably just a fiddle needed to get it working on AppVeyor - it claims to be downloaded in the failing version on AppVeyor (https://ci.appveyor.com/project/tskit-dev/tsinfer/builds/26015455#L209 )

**Comment by jeromekelleher** [comment]
OK - feel free to fiddle with this on PRs @hyanwong and @marianne-aspbury!

**Comment by marianne-aspbury** [comment]
I fixed the numcodecs issue with `conda install numcodecs` 
New issue - now "no module named resource" , even after `pip install resource` this still fails 

Reference: 
(base) C:\Users\mazmysta>conda install numcodecs
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\mazmysta\Anaconda3

  added / updated specs:
    - numcodecs


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    numcodecs-0.6.3            |   py37h6538335_0         594 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         594 KB

The following NEW packages will be INSTALLED:

  numcodecs          conda-forge/win-64::numcodecs-0.6.3-py37h6538335_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
numcodecs-0.6.3      | 594 KB    | ########################################################################################## | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(base) C:\Users\mazmysta>python
Python 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tsinfer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mazmysta\Anaconda3\lib\site-packages\tsinfer\__init__.py", line 42, in <module>
    from .cli import get_cli_parser  # NOQA
  File "C:\Users\mazmysta\Anaconda3\lib\site-packages\tsinfer\cli.py", line 26, in <module>
    import resource
ModuleNotFoundError: No module named 'resource'

`(base) C:\Users\mazmysta>pip install resource
Collecting resource
  Downloading https://files.pythonhosted.org/packages/34/ad/9cd037c01c075f9a273c23557f8e71195d773d59d3881bbb26011d396c8b/Resource-0.2.1-py2.py3-none-any.whl
Collecting JsonForm>=0.0.2 (from resource)
  Downloading https://files.pythonhosted.org/packages/4f/b7/b9491ba4b709d0616fab15a89f8efe4d3a7924652e1fdd4f15303e9ecdf0/JsonForm-0.0.2.tar.gz
Collecting JsonSir>=0.0.2 (from resource)
  Downloading https://files.pythonhosted.org/packages/aa/bf/5c00c1dafaa3ca2c32e7641d9c2c6f9d6d76e127bde00eb600333a60c5bc/JsonSir-0.0.2.tar.gz
Collecting python-easyconfig>=0.1.0 (from resource)
  Downloading https://files.pythonhosted.org/packages/b1/86/1138081cca360a02066eedaf301d0f358c35e0e0d67572acf9d6354edca9/Python_EasyConfig-0.1.7-py2.py3-none-any.whl
Requirement already satisfied: jsonschema in c:\users\mazmysta\anaconda3\lib\site-packages (from JsonForm>=0.0.2->resource) (3.0.1)
Requirement already satisfied: six in c:\users\mazmysta\anaconda3\lib\site-packages (from python-easyconfig>=0.1.0->resource) (1.12.0)
Requirement already satisfied: PyYAML in c:\users\mazmysta\anaconda3\lib\site-packages (from python-easyconfig>=0.1.0->resource) (5.1)
Requirement already satisfied: attrs>=17.4.0 in c:\users\mazmysta\anaconda3\lib\site-packages (from jsonschema->JsonForm>=0.0.2->resource) (19.1.0)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\users\mazmysta\anaconda3\lib\site-packages (from jsonschema->JsonForm>=0.0.2->resource) (0.14.11)
Requirement already satisfied: setuptools in c:\users\mazmysta\anaconda3\lib\site-packages (from jsonschema->JsonForm>=0.0.2->resource) (41.0.1)
Building wheels for collected packages: JsonForm, JsonSir
  Building wheel for JsonForm (setup.py) ... done
  Stored in directory: C:\Users\mazmysta\AppData\Local\pip\Cache\wheels\e8\74\51\42c2d41c02bdc6f0e604476b7e4293b8c98d0bcbfa1dff78c8
  Building wheel for JsonSir (setup.py) ... done
  Stored in directory: C:\Users\mazmysta\AppData\Local\pip\Cache\wheels\ee\30\5c\3a3b5e1386c8db9a3be5f5c3933644ae0533c1351c6a8eb4b5
Successfully built JsonForm JsonSir
Installing collected packages: JsonForm, JsonSir, python-easyconfig, resource
Successfully installed JsonForm-0.0.2 JsonSir-0.0.2 python-easyconfig-0.1.7 resource-0.2.1

(base) C:\Users\mazmysta>python
Python 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tsinfer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mazmysta\Anaconda3\lib\site-packages\tsinfer\__init__.py", line 42, in <module>
    from .cli import get_cli_parser  # NOQA
  File "C:\Users\mazmysta\Anaconda3\lib\site-packages\tsinfer\cli.py", line 26, in <module>
    import resource
ModuleNotFoundError: No module named 'resource''

**Comment by jeromekelleher** [comment]
Thanks @marianne-aspbury -- looks like resource is a unix-only module, so we'll have to update the code to conditionally use that.

**Comment by hyanwong** [comment]
Looks like we need the module python-lmdb as well (https://github.com/ContinuumIO/anaconda-issues/issues/8740#issuecomment-370183360). Strange that it worked OK on non-windows systems though.

**Comment by hyanwong** [comment]
@jeromekelleher - I had a look at `resource.getrusage` etc. A few issues here, as not only does it not work on windows, but the `ru_maxrss` field is not standardised: e.g. on other unixes (FreeBSD, OS X, etc) it is returned in bytes, not kilobytes.

An alternative library that is cross-platform, but is not built-in, so would mean another requirement, is `psutil` (https://anaconda.org/anaconda/psutil)

**Comment by hyanwong** [comment]
@jeromekelleher This is almost there now: https://github.com/tskit-dev/tsinfer/pull/166 but still has an lmdb memory issue on the appveyor builds (see the PR). This is probably as far as I can easily go to get Windows compilation working. I imagine it's 90% there though.

**Comment by jeromekelleher** [comment]
Windows builds working as of #184
