### ISSUE TITLE
Any plans to make tsinfer installable by conda?

### ISSUE THREAD

**Issue by mcneney** [tskit-dev/tsinfer#171]
The reason I ask is that I'd like to use an R package called reticulate to interface with the tskit-dev modules, and this is much easier for modules available on conda-forge. Thanks, -b

**Comment by hyanwong** [comment]
Yes, I think this is on the to-do list - it's just a matter of time.

**Comment by jeromekelleher** [comment]
Yes, definitely @mcneney It should be straightforward to make a conda-forge package for tsinfer. It does take a bit of time though, so we just haven't gotten around to it, unfortunately.

**Comment by benjeffery** [comment]
https://github.com/conda-forge/staged-recipes/pull/15042

**Comment by mcneney** [comment]
Great, thanks!

**Comment by benjeffery** [comment]
@mcneney Sorry it took us almost two years :sob: !

**Comment by jeromekelleher** [comment]
Looks like it's all up and running now: https://github.com/conda-forge/tsinfer-feedstock

Thanks for making the feedstock @benjeffery!
