### ISSUE TITLE
Use tskit map_mutations method to add non-inference sites

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#180]
This issue replaces https://github.com/tskit-dev/tsinfer/issues/32, and is coded up in https://github.com/tskit-dev/tsinfer/pull/179. However, my current implementation is overly complex because SampleData files have fixed ancestral states (i.e. states at the root), which are not currently accounted for in `map_mutations`.

Note that it should be possible to change the (future) Sankoff algorithm to allow for known ancestral states, but this may risk bloating the algorithm code for this specific corner case.

**Comment by hyanwong** [comment]
Actually, since there is no real reason that we need the user to set the ancestral state for non-inference sites, the trivial fix is to simply state in the docs that "ancestral state" is ignored for non-inference sites. Any reason why this would be a bad idea?

**Comment by jeromekelleher** [comment]
> Actually, since there is no real reason that we need the user to set the ancestral state for non-inference sites, the trivial fix is to simply state in the docs that "ancestral state" is ignored for non-inference sites. Any reason why this would be a bad idea?

This seems like the right solution here to me. I don't think the parsimony algorithms will be particularly easy to modify to have a specified ancestral state, as they work from the leaves up.

**Comment by hyanwong** [comment]
OK - I will code this up in https://github.com/tskit-dev/tsinfer/pull/179 and change the unit tests accordingly.

**Comment by hyanwong** [comment]
Closed with https://github.com/tskit-dev/tsinfer/commit/6592b5a65ab270e8723d836d22a251241f9cb2bb
