### ISSUE TITLE
Allow some ancestral states to be unknown

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#181]
It should be possible to allow tsinfer to assign *some* ancestral states. We could ask tsinfer to do this by setting the ancestral state to `tskit.MISSING_DATA` when creating the sample data file. This is trivial for non-inference sites (see https://github.com/tskit-dev/tsinfer/issues/180), but is much more technical for sites that we want to use for inference. 

Essentially, we should be able to decide on the polarization of an ancestral state by looking at compatibility with surrounding sites. This issue is to collect thoughts about how we can do that (both Gil and Jerome think this should be possible).

**Comment by jeromekelleher** [comment]
This would be quite hard outside of the non-inference sites I think, seems there's a lot of features we'd want to implement first before tackling this to me.

**Comment by hyanwong** [comment]
Yes - this is a long-term goal, not something to be considered immediately.

**Comment by hyanwong** [comment]
Tim Barraclough came up with an interesting suggestion for this issue, which with I and @jeromekelleher thought was definitely worth trying. The basic idea is simply to polarise the ancestral states for biallelic alleles both ways, and create 2 ancestors for each inference site (but without changing the ancestral state assignment for adjacent sites). This should only double the time taken.

Here's how I see it working. For each inference site, we generate a new ancestor with the zeros swapped for ones, and flag this ancestor up as a "reverse polarised" one. Then we do the matching with all ancestors present. Ideally, only one of the two ancestors for a focal site should match (we should be able to identify the pairs of ancestors as they will share the same focal site positions). For this it would be helpful to add a "flags" field to the `AncestorData` class, which I will do in a branch.

If we can identify some of the incorrectly polarised states using this method, we should be able to correct them and re-run the inference, which could possibly end up detecting more incorrectly polarised states (since adjacent sites are no more likely to be correctly polarised). It would be helpful to be able to output a list of sites for which we have changed the ancestral state, so that we can check them by hand.

We already have a testing framework which throws in some ancestral state error, so we have some reasonable ways to test this. We can also run the pipeline on the 1000G data set and see if we get better compression. Some other observations that might be helpful for testing are that (a) the correctly polarised ancestors are likely to be a lot longer that the incorrect ones (b) only one of the two polarisations should be used in the final TS - if both are used we probably want some way of deciding which to include (e.g. the one with the fewest sample tips, or the shortest span). It's unclear to me whether we would want to simplify out unary nodes before testing this, but my inclination would be not to.

**Comment by hyanwong** [comment]
A quick thought: we have been experimenting with deleting the mutations from a site and placing them back on using parsimony. The `map_mutations()` method what we would use to do this infers its own ancestral state for the site. So it would be easy, and interesting, to see if parsimony suggests that some of the sites should have a different ancestral state.

**Comment by hyanwong** [comment]
> The basic idea is simply to polarise the ancestral states for biallelic alleles both ways, and create 2 ancestors for each inference site (but without changing the ancestral state assignment for adjacent sites). 

The problem, I think, with this approach is that the ancestor building algorithm needs to know the ancestral state at adjacent sites. Say we have a focal site `S_i`: we need to know if an adjacent site `S_{i+1}` is older or younger, which will depend on the ancestral state polarisation. and that's true in a combinatorial way for every adjacent site. So I think this approach won't actually work terribly well. It will be OK at the focal site, but then nothing will match onto that site from other ancestors.

**Comment by hyanwong** [comment]
> A quick thought: we have been experimenting with deleting the mutations from a site and placing them back on using parsimony. The `map_mutations()` method what we would use to do this infers its own ancestral state for the site. So it would be easy, and interesting, to see if parsimony suggests that some of the sites should have a different ancestral state.

We tried this, and the results weren't terribly good, sadly.

**Comment by hyanwong** [comment]
Allowing ancestral states to be `-1` is now possible with tsinfer 0.3. We should open a different issue to track the idea of assessing whether ancestral states have been correctly assigned.
