### ISSUE TITLE
SampleData.sites_inference[:] should be bool not int

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#188]
At the moment, `sites_inference[:]` returns an np_array of ints. That means when you use if for indexing, numpy uses it as an integer index, not a boolean, as is likely to be intended. That leads to the following mistake being easily made:

```
sd = tsinfer.SampleData.from_tree_sequence(ts)
inference_positions = sd.sites_position[:][sd.sites_inference[:]] # Wrong, hard to spot
inference_positions = sd.sites_position[:][sd.sites_inference[:].astype(bool)] # Right
```

**Comment by hyanwong** [comment]
I just tried a PR (https://github.com/tskit-dev/tsinfer/pull/191) and at least if passes the test suite. Probably worth asking @awohns to check his pipelines still work.

**Comment by jeromekelleher** [comment]
How are we using the sites_inference array within tsinfer at the moment though? Would you mind digging out a couple of examples?

**Comment by hyanwong** [comment]
Well, in the tests and eval_util we do things like:

```
sample_data.sites_position[:][sample_data.sites_inference[:] == 1]
...
np.sum(input_file.sites_inference[:])
```

which are both unaffected. It's only used 2 times in inference.py:

```
        sample_data_position = sample_data_position[
            self.sample_data.sites_inference[:] == 1]
...
        inference_sites = self.sample_data.sites_inference[:]
        if np.all(inference_sites == 0):
            ...
        else:
            position = position[inference_sites == 1]
```

**Comment by jeromekelleher** [comment]
Ah ok, thanks. You're right, ``bool`` is unequivocally better here, let's change it. (Should update these usages within the code to be use the bool properly as well)

**Comment by hyanwong** [comment]
OK - I'll go through and remove the `== 1` from those places where appropriate, and add them to this PR shall I?

**Comment by jeromekelleher** [comment]
Please

**Comment by hyanwong** [comment]
This is done. A few test adjustments when setting `sites_inference` because testing for `bool` is a little more convoluted than for an int range. So I check if it is an np bool array first, and if not, use the `np_safe_cast` routine I previously coded up to convert to uint8, then check for 0/1, then convert to bool. A bit convoluted, but I can't see an easier way. This means it raises different sorts of error (e.g. OverflowError for big numbers, TypeError for empty arrays etc). I guess that's fine.
