### ISSUE TITLE
Create new samples file with a subset of sites

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#209]
It's useful in a few instances to subset the sites in a SampleData file down to a limited number. Since we haven't got methods to iterate through e.g. the populations in a SampleData file, it's hard to recreate the file exactly (but with a subset of sites). We *can* do this, I think, by resizing the underlying zarr arrays, something like this:

```
def subset(sample_data, keep_sites_bool):
    site_shape = np.sum(keep_sites_bool).item(),
    subset = sample_data.copy()
    for attr in [a for a in dir(sample_data) if a.startswith('sites_')]:
        zarr_name = attr.replace('_', '/', 1)
        subset.data[zarr_name].resize(*(site_shape +  sample_data.data[zarr_name].shape[1:]))
        subset.data[zarr_name].set_basic_selection(..., sample_data.data[zarr_name][:][select])
    subset.finalise()
    return subset
```

Is this worth adding to tsinfer?

**Comment by hyanwong** [comment]
Or perhaps more to Jerome's taste, we could `clear()` the sites arrays in the copy and add sites back in incrementally using add_sites - presumably slower by less hacky (and doesn't subset a copy of the genotypes array in memory)

**Comment by hyanwong** [comment]
FWIW running `subset()` on chr20, 1000G, subsetting doen to about 1/3 of the 800,000 sites takes about 40 sec, whereas running `subset2()` takes about 3 mins.

**Comment by hyanwong** [comment]
I've just needed to do this again, without realising that I coded a solution previously. The code is neater if the zarr groups are used directly, and np.take is used. The version below creates a new SampleData object, instead of acting on an old one:


```
def keep_sites(sample_data, keep_sites, sequence_length=None, **kwargs ):
    """
    Return a new sample data object keeping only the specified sites.
    
    :param arraylike keep_sites: An array of sites to keep, either a list of
        site indices or a numpy boolean array of size sample_data.num_sites
    :param float sequence_length: A new sequence length for the returned
        SampleData object. If None (the default), take the existing sequence_length
    :return: A new :class:`.SampleData` object with a reduced number of sites
    :rtype: :class:`.SampleData`.
    """
    new_sample_data = sample_data.copy(**kwargs)
    new_sample_data._check_edit_mode()
    for name, arr in sample_data.data.sites.arrays():
        new_data = np.take(arr[:], keep_sites, axis=0)
        arr.resize(*new_data.shape)
        arr[:] = new_data
    new_sample_data.finalize()
    return new_sample_data
```

a. does this seem right
b. would this be a useful method for a SampleData object, or is it just me? (note that the odd site can be "masked out" of inference by setting its `sites_inference` value to 0, so this is primarily where large numbers of sites need to be entirely removed)

**Comment by jeromekelleher** [comment]
This is neat all right, and looks about right to me. The name isn't quite right though. What about:
```python
def subset(self, sites=None, samples=None, **kwargs):
     """
     Return a new sample data file keeping only the specified sites and/or samples.
     """"
```
So we can slice in the other dimension as well?

Why do you want to set the sequence length?

ps. To get code to format as python, put a "python" immediately after the triple backticks.

**Comment by hyanwong** [comment]
Nice about python formatting. Thanks! Happy to include samples as well. I'll code up, add some tests, and make it into a PR.

I guessed we wanted this to return a new SampleData object rather than editing in-place, but happy to do it either way (if in-place, we'd have to tell users to make it editable first, I presume).

**Comment by jeromekelleher** [comment]
Let's return a new file. The semantics get tricky otherwise.

**Comment by hyanwong** [comment]
Should I have a `sequence_length` parameter? It seems a little excessive (and perhaps only a few people will want to chop stuff off the end), but otherwise there isn't an obvious way to set the sequence_length, as it's a read-only property.

**Comment by jeromekelleher** [comment]
``sequence_length`` seems pretty niche, let's not bother with it.

**Comment by hyanwong** [comment]
Yep, could always make it editable anyway.

**Comment by hyanwong** [comment]
Closed via https://github.com/tskit-dev/tsinfer/pull/293
