### ISSUE TITLE
Path compressed ancestor time increment is hardcoded: can cause errors for user-input variant times

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#210]
I'm trying to re-infer a sample data file produced from the trees file on the wellcome server at

`/well/mcvean/ukbb12788/wohns/tsinfer_geva/tgp_geva_chr20.trees`

After installing the latest (github) version of tsinfer:

`python3 -m pip install git+https://github.com/tskit-dev/tsinfer --user`

I then use the from_tree_sequence method to create a sample data file within python:

```
import tskit
ts = tskit.load("/well/mcvean/ukbb12788/wohns/tsinfer_geva/tgp_geva_chr20.trees")
sd = tsinfer.SampleData.from_tree_sequence(
    ts, path="tgp_geva_chr20.samples", use_times=True)
sd.close()
```

then when I try inference, I fail at the match_samples stage, with error -5:

```
yan@holly:~$ python3 -m tsinfer infer tgp_geva_chr20.samples -p -t 6
ga-add   (1/6)100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 860k/860k [00:17, 50.5kit/s]
ga-gen   (2/6)100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 739k/739k [02:53, 4.25kit/s]
ma-match (3/6)  7%|█████████▊                                                                                                                                           | 48.7k/739k [14:45, 33.0it/s]2019-11-07 17:21:19,423 [6387] CRITICAL root: Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/yan/.local/lib/python3.7/site-packages/tsinfer/__main__.py", line 9, in <module>
    main()
  File "/home/yan/.local/lib/python3.7/site-packages/tsinfer/__main__.py", line 5, in main
    cli.tsinfer_main()
  File "/home/yan/.local/lib/python3.7/site-packages/tsinfer/cli.py", line 479, in tsinfer_main
    args.runner(args)
  File "/home/yan/.local/lib/python3.7/site-packages/tsinfer/cli.py", line 187, in run_infer
    sample_data, progress_monitor=progress_monitor, num_threads=args.num_threads)
  File "/home/yan/.local/lib/python3.7/site-packages/tsinfer/inference.py", line 171, in infer
    path_compression=path_compression, progress_monitor=progress_monitor)
  File "/home/yan/.local/lib/python3.7/site-packages/tsinfer/inference.py", line 249, in match_ancestors
    return matcher.match_ancestors()
  File "/home/yan/.local/lib/python3.7/site-packages/tsinfer/inference.py", line 995, in match_ancestors
    self.__match_ancestors_multi_threaded()
  File "/home/yan/.local/lib/python3.7/site-packages/tsinfer/inference.py", line 981, in __match_ancestors_multi_threaded
    self.__complete_epoch(j)
  File "/home/yan/.local/lib/python3.7/site-packages/tsinfer/inference.py", line 922, in __complete_epoch
    extended_checks=self.extended_checks)
_tsinfer.LibraryError: Error occured: -5
```

Where can I look up the meaning of a `-5` error, and how can I slim this down to debug?

**Comment by jeromekelleher** [comment]
Hmm, the error is defined [here](https://github.com/tskit-dev/tsinfer/blob/master/lib/err.h#L8). Looks like there's some assumption being violated?

**Comment by hyanwong** [comment]
And in fact, that error is only ever used once in the code, [here](https://github.com/tskit-dev/tsinfer/blob/f1957c47d82f2ae638370e66420a7ae6974d81d4/lib/tree_sequence_builder.c#L623). So there's a time issue (perhaps not surprising, as we are using variant times from GEVA here)

**Comment by hyanwong** [comment]
So the problem is that the trees file has been generated using path compressed ancestors, whose node times are incorporated into the sample data file. In this specific case, it leads to two ancestors in this epoch (in my cut-down version, ancestors 19734 and 19735) being placed at time 34127.49998474 - a value which comes from one of the parents at time 34127.5, minus the PC_ANCESTOR_INCREMENT.

In the original file, there must have been 2 PC ancestors at the same time point. We then try to path compress *these* ancestors (as they are in the same epoch), and place their 2nd degree PC ancestor near the parent, but fail, because the parent is only PC_ANCESTOR_INCREMENT different.

**Comment by hyanwong** [comment]
For the moment, an obvious way to hack around this is not to allow path compression on samples that have variant times which may have themselves come from path compression. But it seems a bit weird to me that we have any variants that originate on a PC ancestor.

**Comment by jeromekelleher** [comment]
Hmm, not sure what to do with that one. Can we construct a minimal test case that will reproduce the bug?

**Comment by hyanwong** [comment]
Yes, anything where the user-injected times between variants that give rise to the same ancestor (and which are path compressed) is < PC_ANCESTOR_INCREMENT. I can probably construct a test case.

If we want to support user-input times combined with path compression, I guess we might want to modify the use of PC_ANCESTOR_INCREMENT so that if it's not small enough, we shrink it until it is, and only bomb out when we hit floating point accuracy problems.

**Comment by hyanwong** [comment]
The easiest workaround for this would be to put the onus on the user by allowing PC_ANCESTOR_INCREMENT to be set when inferring (defaulting to 1.0 / 65536 as it does now), and advise that it may need to be smaller than the distance between any two successive ancestors. We could even replace the `path_compression` parameter with e.g. `path_compression_increment`, and if it is `0.0` or `False`, path compression is turned off (and if it is `True` or unspecified, it defaults to  1.0 / 65536).

The other (more sophisticate) way to do this is to treat  1.0 / 65536 as a maximum, and if the time between parent and child is less than this, we e.g. take a fraction of the distance between parent and child as the increment instead.

**Comment by jeromekelleher** [comment]
I'm sure I tried adaptive values for the increment, but it lead to some very difficult to track down bugs.

**Comment by hyanwong** [comment]
Perhaps just letting the user set a value would be sensible, then?

**Comment by jeromekelleher** [comment]
Yes, possibly. I'd want to have another pass at path compression before adding any extra parameters to the CLI that we need to maintain/deprecate though. Let's shelve this for a bit.

**Comment by hyanwong** [comment]
OK - I have a current hack around the problem for using the timed 1000 genomes data (i.e. don't bother with path compression on the final pass, or *in extremis* I could recompile with a different constant). However, I think it might be worth merging #213 so that we have a (skipped) test for this, and we don't forget it.
