### ISSUE TITLE
Tsinfer default metadata inconsistency vs tskit/msprime

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#212]
In msprime and tskit in general, unspecified metadata leads to the metadata field containing `b''`, whereas (I think in [line 458](https://github.com/tskit-dev/tsinfer/blob/f1957c47d82f2ae638370e66420a7ae6974d81d4/tsinfer/formats.py#L458)) tsinfer defaults to metadata fields containing `{}` (or its base64 encoded equivalent). We should probably standardise on something.

**Comment by hyanwong** [comment]
The underlying reason is that `tsinfer` [expects](https://tsinfer.readthedocs.io/en/latest/inference.html#metadata) metadata to always be something in JSON format, whereas `tskit` is [agnostic](https://tskit.readthedocs.io/en/latest/data-model.html#sec-metadata-definition). That makes it tricky to e.g. convert generic tree sequences to SampleData files.

**Comment by jeromekelleher** [comment]
I think it's reasonable for tsinfer to use JSON, so if the input tree sequence file has a non-empty metadata string, then it must be JSON or we throw an error.

**Comment by hyanwong** [comment]
OK - I think I'll add a "use_metadata" parameter to `from_tree_sequence` then, so that we can still port over tree sequences that have non-JSON metadata. I'll also need to convert tree sequence metadata that consists of the empty string, to `{}` (or pass it as `None` to the add_xxx functions, which ends up doing the same)
