### ISSUE TITLE
Weird node flags in inferred tree sequences?

### ISSUE THREAD

**Issue by gtsambos** [tskit-dev/tsinfer#218]
Hullo tsinfer team, congrats on the wonderful work! This issue is possibly not to do with tsinfer itself, but with tsunzip or even something on my own computer, but I thought I'd log it here just in case.

I have downloaded your inferred tree files from Zenodo, then applied `tsunzip` to them to get the trees files. When I load the resulting files, I notice that the tree sequences have a few nodes with an odd flag label 65536:

```
6200D-132482-M:0.raw gtsambos$ python
Python 3.7.4 (default, Aug 13 2019, 15:17:50) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tskit
>>> ts = tskit.load("1kg_chr21.trees")
>>> set(ts.tables.nodes.flags)
{65536, 1, 0}
```
Do you know why these nodes are flagged?

**Comment by hyanwong** [comment]
This denotes a "path compressed node" (NODE_IS_PC_ANCESTOR). Flags are defined in https://github.com/tskit-dev/tsinfer/blob/master/tsinfer/constants.py. Path compression is described in the tsinfer paper...

**Comment by hyanwong** [comment]
P.s. Can I close this issue, or do you want to add something to the docs in case it's not clear, and someone else has this question?

**Comment by gtsambos** [comment]
Thanks, hmm. So the reason why I found these is because I was trying to add some nodes of my own onto the treeseqs (Census nodes), with flags defined [here](https://github.com/tskit-dev/msprime/blob/60b3c7db2522742ddf3d0f1fce446d89efa993e7/lib/msprime.h), and this 65536 value is also what shows up in the flag column of these census nodes. It's a bit odd given that the hex value is different? But; this is probably a fairly niche use case and I wouldn't bother updating the docs about it, unless it also points to some broader issue

**Comment by hyanwong** [comment]
If any of these:

```
#define MSP_NODE_IS_RE_EVENT    (1u << 17)
#define MSP_NODE_IS_CA_EVENT    (1u << 18)
#define MSP_NODE_IS_MIG_EVENT   (1u << 19)
#define MSP_NODE_IS_CEN_EVENT   (1u << 20)
```

can be reasonably applied to an internal node in a tree, then we should ensure they don't clash with the flags from tsinfer, i.e.

```
NODE_IS_PC_ANCESTOR = 1 << 16
NODE_IS_SRB_ANCESTOR = 1 << 17
NODE_IS_SAMPLE_ANCESTOR = 1 << 18
```

We still have space left in the bit field to use different values, and either adjust the constants in tsinfer or msprime. I think this is a call for @jeromekelleher to make. Normally I would say that changing the tsinfer constants is preferred, because it's used less than msprime at the moment, but we have released files that use these constants, so we'd need to release new versions of those if we changed the bit flag assignment in tsinfer.

This is the time to do it, if at all, though, before tsinfer sees wider use.

**Comment by jeromekelleher** [comment]
The [upper half](tskit.readthedocs.io/en/latest/data-model.html#node-table) of the node flags space is free for applications to use, and we're not making any effort to coordinate what they mean centrally (the lower half is reserved for tskit internal use).

I'm OK with having tsinfer and msprime flags overlapping, I can't really see how msprime events are relevant to tsinfer'd tree sequences and vice-versa. What's your application for the census flags here @gtsambos?

**Comment by gtsambos** [comment]
Thanks @jeromekelleher; I was manually putting some census nodes on the trees in order to make certain IBD-ish things easier to do, but the long-term solution for this is a different algorithm anyway. I wouldn't worry about it.
