### ISSUE TITLE
Needs updated tskit submodule

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#230]
https://github.com/tskit-dev/tsinfer/pull/223 added tskit as a submodule, but in my repo, when cloning this submodule, the cloned `tskit/core.h` file does not define `TSK_MISSING_DATA`, which is a constant defined in the `core.h` file in the current (master) branch of the tskit repository. So it looks to me as if the tskit version stuck as a submodule in tsinfer is an old version that needs updating. Have I got this right, @jeromekelleher ?

**Comment by hyanwong** [comment]
Hmm, seems to work after a `git submodule update --recursive --remote`, but odd that it didn't before. Probably just my setup, so closing for the time being. Sorry about the noise.

**Comment by jeromekelleher** [comment]
I'm sure this is fine, the CI tests are passing.
