### ISSUE TITLE
Incorporate individuals_time into the inferred tree sequence sample nodes

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#232]
Thanks to #190, the sampledata file has the ability to store a time for an individual (as well as times for variants). The time for an individual is, however, currently ignored.

As part of tsdate, we'd like to be able to obtain the time for a non-contemporaneous sample node, and I think the sensible thing to do is to get this out of the inferred tree sequence. In other words, I would like a tree sequence with the sample nodes placed at the times specified in the `individuals_time` field.

This mean (a) placing the sample nodes at a time in the resulting ts as specified by the individuals_time of the individual with which they are associated AND (b) ensuring that these sample node times do not conflict with the internal node times imposed by tsdate (e.g. when using the frequency of the focal variants as a proxy for time).

One slighly hacky possibility, if the frequency of focal variants is used as the node time (i.e. if  variant times are not user-specified), is to find the oldest `individuals_time` value, and add that to all the variant frequencies (or multiply the frequency values by some large value) so that all ancestors are older than the oldest sample. Of course, if the user specifies a variant age when inputting the sites, then we shouldn't alter it, but rather throw an error if a variant is younger than the age of a sample (individual) containing that derived variant.

Also see https://github.com/tskit-dev/tsinfer/issues/207

**Comment by awohns** [comment]
One option is to handle all of this in tsdate, as it's relevant to the dating but not necessarily the topological inference.
