### ISSUE TITLE
Return errors with 'impossible' parameters and test

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsinfer#233]
#231 added support for variable mutation and recombination rates. It doesn't check for cases in which no solution for LS can be found (probably asserts out in the C case).

Once the code is updated to use tskit tree sequences natively, make this robust.

**Comment by hyanwong** [comment]
Note that this creates problems with real data files. In particular, where some genetic maps have recombination rates of zero in some places (which most do: I'm using GRCh38 maps from http://csg.sph.umich.edu/locuszoom/download/recomb-hg38.tar.gz with any rates over 100 cut out), then matching can fail some way through the match ancestors process.

I'm getting round this by replacing all the zero values with values that are lower than the minimum non-zero genetic distance seen in the rest of the file. But it would be nice not to have to do this.

**Comment by jeromekelleher** [comment]
There are now specific errors emitted on these failures, so closing.
