### ISSUE TITLE
Add documentation link to tskit for analysis

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#238]
At the moment the docs give examples of how to do inference, but then a novice user has no way to know how to analyse their data. I suggest it might be good to have a (very short) `analysis.rst` file that gives a single example (e.g. with GNN or Fst) and points to the statistics page in tskit for more information. What do you think @jeromekelleher ?

**Comment by jeromekelleher** [comment]
Good idea, go for it!

**Comment by hyanwong** [comment]
Great, will do, and consult with @markravinet about what he might find a useful example, as a new user.

**Comment by jeromekelleher** [comment]
Closed in #239
