### ISSUE TITLE
setup.py implies GPL licence: should it be MIT?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#245]
Just noticed that in the `tsinfer` setup.py file it says

```
license="GNU GPLv3+",
```

etc. Do you want me to change it to match the `tskit` licence i.e. (MIT), @jeromekelleher ?

**Comment by jeromekelleher** [comment]
No, the license is [GPL](https://github.com/tskit-dev/tsinfer/blob/master/LICENSE). Short version is we're including GPL source in here so we have to be.

**Comment by hyanwong** [comment]
Sorry. My bad. Didn't realise we had GPL code in there.

**Comment by hyanwong** [comment]
Just noting that it's the AVL implementation that's GPL:

https://github.com/tskit-dev/tsinfer/blob/main/lib/avl.h
