### ISSUE TITLE
New inference code still failing with -12 error if unused recombination rate is 0

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#257]
I am still getting the following error when performing inference with the first element of the recombination_rate array (which I gathered should be ignored), set to 0:

```
sample_data = tsinfer.load("1kg_chr20_small.samples")
rho = np.diff(sample_data.sites_position[:][sample_data.sites_inference])/sample_data.sequence_length
ts = tsinfer.infer(
    sample_data,
    recombination_rate=np.concatenate(([0.0],rho)),
    mutation_rate=np.concatenate(([0.0],rho))/100) # fails

ts = tsinfer.infer(
    sample_data,
    recombination_rate=np.concatenate(([np.min(rho)],rho)),
    mutation_rate=np.concatenate(([np.min(rho)],rho))/100) # works

```
(sample data file attached)
[1kg_chr20_small.samples.gz](https://github.com/tskit-dev/tsinfer/files/4394580/1kg_chr20_small.samples.gz)

**Comment by jeromekelleher** [comment]
Thanks, will get to this soon. Trying to land missing data first...

**Comment by hyanwong** [comment]
No hurry. Just realised that the sample file was generated using the save-default-time-as-null PR checked out (i.e. the times in the file are -inf), so you might not be able to test until that's merged anyway.

**Comment by hyanwong** [comment]
It looks like this is simply an issue of having any items in the mutation_rate array equal to 0. It runs fine if e.g. we set `np.full(sample_data.num_inference_sites, 1e-200)` or whatever. This is presumably because the 1st element in the mutation_rate array *is* used at site `0`, whereas the recombination rate is not. Erroring out with mutation_rate=0 is currently expected behaviour, so closing and opening a more usefully named issue https://github.com/tskit-dev/tsinfer/issues/260
