### ISSUE TITLE
Add ability to show progress monitor when running from within python

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#259]
It's a trivial thing, but I usually run inferences (e.g. testing 1000G) using a python script, rather than the command-line `tsinfer` version, even on long inferences. It would be lovely to be able to pass `progress_monitor=True` to e.g. `tsinfer.infer()`, instead of requiring the progress_monitor function to take `None` or a `ProgressMonitor` object. Perhaps in `infer()` we could do something like:

```
if progress_monitor == True:
    progress_monitor = tsinfer.cli.ProgressMonitor(
        generate_ancestors=True,
        match_ancestors=True,
        augment_ancestors=False,
        match_samples=True)
```

And similarly, with the appropriate parameters in `generate_ancestors` and friends. What do you think @jeromekelleher ? I'm happy to code this up, although I wonder if the ProgressMonitor class would therefore be best moved to its own source file (`progress.py`?)

**Comment by jeromekelleher** [comment]
I agree it would be nice to document this and make it available. However, I think you know what my response to ``progress_monitor == True`` is going to be...

Moving stuff into ``progress.py`` is a good idea. Can you paste in a fragment of your client code here and we can see if we can abstract it a bit and make it simpler?

**Comment by hyanwong** [comment]
> I agree it would be nice to document this and make it available. However, I think you know what my response to `progress_monitor == True` is going to be...

Indeed. Not that I'm trolling you @jeromekelleher, but I'm clearly happier with parameter oveloading that you are ! What would your suggestion be? Presumably a different parameter (e.g. simply `progress`?). Presumably if we then pass a non-null parameter to `prograss_monitor` we simply ignore the `progress` setting?

> Moving stuff into `progress.py` is a good idea. Can you paste in a fragment of your client code here and we can see if we can abstract it a bit and make it simpler?

Well, I'm simply using the following, although using positional arguments to `tsinfer.cli.ProgressMonitor` is obviously a quick hack:

```
ts = tsinfer.infer(
    sample_data, precision = 10, num_threads=10,
    progress_monitor=tsinfer.cli.ProgressMonitor(1, 1, 1, 0, 1)
    )
```

**Comment by hyanwong** [comment]
Do you want me to work this up into a PR? I think it's quite easy

**Comment by jeromekelleher** [comment]
> Not that I'm trolling you @jeromekelleher, but I'm clearly happier with parameter oveloading that you are !

I feel like I've said [this](https://docs.quantifiedcode.com/python-anti-patterns/readability/comparison_to_true.html) quite a few times... Parameter overloading is fine used sparingly, but comparing object identity with a boolean is never something I'm going to agree with.

**Comment by jeromekelleher** [comment]
Well what about:

```python
ts = tsinfer.infer(
    sample_data, precision = 10, num_threads=10,
    progress_monitor="all",
    )
```

Seems simple enough? We just need to make creating a tsinfer ProgressMonitor object easier.

**Comment by hyanwong** [comment]
OIC - you're happy with it being a string but not a boolean? I don't feel that we need the flexibility of having different sorts of progress monitor strings. If you run `infer()` and want a progress monitor, you should get it for all stages of the inference, otherwise you can simply run each step independently.

I don't really like having to pass predefined strings as parameter values unless absolutely necessary. It does seem obvious to me to expect `progress_monitor=True` to do the right thing. You can do this without conflicting with pep8 as long as you don't mind checking the object type. E.g.

```
if isinstance(progress_monitor, ProgressMonitor):
    #as before
elif progress_monitor:
    new_progress_monitor = tsinfer.cli.ProgressMonitor(1, 1, 1, 0, 1)
    # etc
else:
    pass # no progress monitor required
```

**Comment by benjeffery** [comment]
Pardon me for chipping in but I think setting `ProgressMonitor` to default to all on and then:
```python
ts = tsinfer.infer(
    sample_data, precision = 10, num_threads=10,
    progress_monitor=tsinfer.cli.ProgressMonitor(),
    )
```
Looks nice and clean and avoids the bool/string debate?

**Comment by hyanwong** [comment]
Thanks @benjeffery . I would probably prefer to default to *not* having a progress bar, but make it easy to switch it on, which is why explicitly having to set `progress_monitor=True` makes sense to me.

**Comment by benjeffery** [comment]
Yeah exactly, the default behaviour of `infer` is `progress_monitor=None`, I was talking about the default of `ProgressMonitor`'s categories.

**Comment by jeromekelleher** [comment]
I agree with Ben's approach.

**Comment by hyanwong** [comment]
OK. Will the progress monitor class need to detect whether it is running within `tsinfer.infer()`, `tsinfer.match_ancestors()`, or whatever, though?

**Comment by jeromekelleher** [comment]
No, ProgressMonitor() just needs a better inferface. No need for anything fancy.

**Comment by hyanwong** [comment]
Going through old issues - it seems like there's a lot of talking past each other here.

@benjeffery suggested

```
ts = tsinfer.infer(
    sample_data, precision = 10, num_threads=10,
    progress_monitor=tsinfer.cli.ProgressMonitor(),
    )
```

but, given that @jeromekelleher doesn't want the ProgressMonitor class to know which routine has called it,  we couldn't do the same for e.g. `build_ancestors()`. Instead we'd need to do something incomprehensible like:

```
ts = tsinfer.build_ancestors(
    sample_data, precision = 10, num_threads=10,
    progress_monitor=tsinfer.cli.ProgressMonitor(1, 0, 0, 0, 0),
    )
```

So I return to my original suggestion:

```
ts = tsinfer.build_ancestors(
    sample_data, precision = 10, num_threads=10,
    progress_monitor=True,
    )
```

and if we want to retain backwards compatibility, so that we can specify `progress_monitor=tsinfer.cli.ProgressMonitor()` as well as `progress_monitor=True`, we detect the class within the build_ancestors (our whatever) function:

```
if not isinstance(progress_monitor, ProgressMonitor) and progress_monitor:
    progress_monitor = tsinfer.cli.ProgressMonitor(...)  # here the  ... will be different within tsinfer.infer vs tsinfer.build_ancestors, etc
```

**Comment by hyanwong** [comment]
So #369 implements my suggestion. It turned out to be simplest to extract the instance check into the (already existing) `_get_progress_monitor()` function. That means we can either pass an existing progress monitor to e.g. `tsinfer.infer()` or `tsinfer.generate_ancestors()`, or something that is truthy: if True, we create a progress monitor to use, if not, we use the dummy.

Seems neat to me, and simplifies the cli.py logic rather easily, I think. I didn't add any extra documentation, as these are all undocumented at the moment anyway.
