### ISSUE TITLE
Store user-input add_site() inference preferences

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#262]
Like https://github.com/tskit-dev/tsinfer/issues/255 we should probably not simply store whether a site is used for inference by running a calculation during the `Sampledata.add_site()` routine, because if we later change the sample file e.g. by removing samples, we have to recalculate the value and do not know what the user originally intended.

Unlike the `sites_time[:]` value, which is only used once in inference, here we have the complication that we often use the `sites_inference[:]` array for indexing. If we have to recalculate it on the fly each time, this would be pretty tedious.

My initial thought would be to have *two* time arrays: `sites_inference[:]` as before, and a new array that stores the user-input value, say `sites_user_inference[:]`, or possibly (see below) `sites_skip_inference[:]`. In fact, we could deprecate the `inference=True|False|None` argument and replace it with `skip_inference = True|False` - i.e. only allow the user to force inference to be `False` (as I can't see any value in forcing inference to be `True` when a site is not usable).

Both `sites_inference[:]` and `sites_skip_inference[:]` would therefore be boolean arrays, and we can have a routine that calculates `sites_inference[:]` from a combination of `sites_skip_inference[:]` and the genotypes array. This routine would be run every time the genotypes array for a site was input or changed, or if the user changes the `sites_skip_inference[:]` array (which should be the only user-writable array). I.e. `sites_inference[:]` buffers the current inference value. 

This scheme has the benefit that it is basically an invisible change to most users - they can continue using the `sites_inference[:]` array as before, and we can make any `add_sites(..., inference=False` be treated as  `add_sites(..., skip_inference=True`.

Thoughts?

**Comment by jeromekelleher** [comment]
My feeling would be avoid storing this at all and to only decide whether a site gets used for inference at ancestor generation time. The reason we use sites_inference all the time is really just a technical one, which may be better to work around. I'd need to dig into it to see what's possible.

**Comment by hyanwong** [comment]
If we can get around using `sites_inference[:]` altogether, that would be better, yes (but it's quite often used e.g. in @awohns 's scripts). My comment about using `skip_inference=True|False` still stands, I think.

**Comment by hyanwong** [comment]
Closed by https://github.com/tskit-dev/tsinfer/pull/266
