### ISSUE TITLE
branch length and node age in tsinfer tree

### ISSUE THREAD

**Issue by hyl317** [tskit-dev/tsinfer#271]
Hi, I was following the simulation example provided here [here](https://tsinfer.readthedocs.io/en/latest/tutorial.html). I took the ts file returned by tsinfer and played around with the trees there a bit. I noticed that I can actually access the age of each node and tmrca of any two nodes. For example,
`
>>> import tskit
>>> ts = tskit.load("simulation.trees")
>>> ts.sequence_length
10000000.0
>>> t1 = ts.first()
>>> t1.branch_length(1)
7.0
>>> t1.branch_length(0)
2.0
>>> t1.time(t1.mrca(0,1))
5471.0
`

I thought tsinfer only attempts to infer tree topology but not branch length, right? If so, why could I access branch length in the returned tree? and how are these age estimates obtained? Thanks!

**Comment by jeromekelleher** [comment]
Thanks for trying out tskinfer @hyl317!

In tsinfer we make crude estimates of the node times using the frequency of the mutation at the current "focal site". Each ancestor that we estimate is the ancestral haplotype that a particular mutation arose on. We use this crude estimate as a way of ordering ancestors. This is the time that we get in the output trees.

I agree it's a bit misleading to have times in the trees when they're not particularly meaningful, but it's a topological requirement in tskit that [nodes must have a time](https://tskit.readthedocs.io/en/latest/data-model.html#definitions).

**Comment by hyanwong** [comment]
Glad you have been trying it out, @hyl317 . As Jerome says, the node "times" are just frequencies. When https://github.com/tskit-dev/tskit/issues/495 is fixed, it should be clearer, as we can set the "timescale_units" to "frequency", or something similar.

If you want to estimate a time length, you can try our (alpha) version of tsdate, currently at https://github.com/awohns/tsdate/ - this will probably be moved into the Tskit-dev branch when it is production-ready.

**Comment by hyl317** [comment]
Hi Yan and Jerome, thanks for the quick response! One more question, so is this branch length purely an ordering of ancestral nodes or do they actually have meanings (some simple calculation of expected age measured in generations given its current frequency)? I am asking this cuz I am thinking of using tsinfer tree as a starting point for an iterative approach and wonder if the branch length is reasonable for initialization.

**Comment by hyanwong** [comment]
It is purely a measure of frequency. In the stable version (0.1.4) it is an integer, simply giving the number of samples that have the focal mutation, so will range from 2...num_samples. In the current GitHub master, it is this number divided by the total number of samples, so the "time" is a floating point number ranging from 0 to 1. If you want a starting value you might want to scale this e.g. using the conditional coalescent. @awohns can probably give you the formula for converting a count + num_samples to a mean relative time under the conditional coalescent. Getting the mean is quite a simple formula.

**Comment by jelliotthiggins** [comment]
Hi all! I came here to ask this same question so I'm glad there's already a thread. I do have two additional questions though:

Is the unit of times inferred by tsdate generations?  
Is there any rough timeline for the preprint?

Thanks!

**Comment by hyanwong** [comment]
Ha - I'm just about to add a small note in the docs about it.

The timescale in tsdate is defined by the magnitude of the mutation rate you pass in. If you use (say) 1e-8 mutations per bp per generation, then the scale is in generations. If you use a per-year rate, then the result will be in years, etc.

**Comment by jeromekelleher** [comment]
I'm going to close this issue as there's no direct actions we need to take on tsinfer about it. Please feel free to continue the conversation if anyone else has questions though!

**Comment by jelliotthiggins** [comment]
@hyanwong that all helps a ton and the tutorial explanation is perfect. Thank you!
