### ISSUE TITLE
Output tree sequence should include metadata schemas

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#272]
With the nice new [metadata capabilities](https://github.com/tskit-dev/tskit/pull/543) in tskit, we might assume that people will want to have metadata associated with nodes in tree sequences created from real data. In this case we'll need a way to associate a schema with tables in a SampleData file, from where it will be pulled in to the generated tree sequence. @awohns is encountering this as he wants to associate metadata with ancient samples during inference. It's not at all urgent, however, as he can just use the "old way" of JSON encoded metadata for the moment. Pinging @benjeffery as he knows most about the metadata stuff, although he might not want to dive back into it now that it's nicely signed off in tskit!

**Comment by benjeffery** [comment]
How I see this working is that `tskit.MetadataSchema` would be used to encode metadata when it is stored in the SampleData file, the encoded bytes and schema would just be copied across to the tree sequence.

**Comment by hyanwong** [comment]
This sounds right, and actually, not that much work, when we get round to it eventually?

**Comment by jeromekelleher** [comment]
That's the plan - we need tskit 0.3.0 released before starting on it here though.

**Comment by jeromekelleher** [comment]
Following the basic principles laid out in https://github.com/tskit-dev/tskit/issues/1051 we should define minimal metadata schemas for the entities that we support metadata for. I will update with a proposal PR ASAP.

**Comment by hyanwong** [comment]
Do we need a JSON schema that supports `b''` as a metadata item, rather than requiring `null` or `{}`?

**Comment by benjeffery** [comment]
No such schema currently exists - it could be made to if JSONCodec interpreted b'' as None
