### ISSUE TITLE
Rename "mutation_rate" parameter?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#273]
The `mutation_rate` parameter in `match_ancestors` and `match_samples` is rather misleadingly named, as I think @jeromekelleher has previously pointed out. The issue is that it is nothing to do with the rate of mutation in the generated ancestors. It only measures the probability of a allowing a match to carry on through a haplotype even if one site does not agree. This could be an error in sequencing (including e.g. "mutations" during PCR) or a recurrent mutation, or a back mutation. I would really like to rename this before we release, but I'm not sure what to use. I reckon two choices are either to go for something to do with mutation, such as `multiple_hit_rate` or something that doesn't really mention mutation at all, but focuses on the matching process, e.g. `match_error_rate`.

Better suggestions actively solicited!

**Comment by hyanwong** [comment]
I just thought - how about "mismatch_rate" @jeromekelleher ?

**Comment by jeromekelleher** [comment]
Yeah, mismatch would be much better. I'm not clear on whether these really are rates/probas though.

**Comment by hyanwong** [comment]
I think of a rate as being per unit something (in this case, base pair, I think). A probability is something fixed for an instance. In this case, as I understand it, the value is taken as a probability of (say) recombination over the stretch between inference site n and n+1.
