### ISSUE TITLE
tsinfer ls: File not in KAS format

### ISSUE THREAD

**Issue by hannesbecher** [tskit-dev/tsinfer#278]
Hi, 

I've been following the tsinfer tutorial (currently doing the data simulation and subsequent inference section). `tsinfer ls` does not work for me. (I've set up tsinfer via pip as recommended.)

The inference itself seems to be ok; I get the same trees as shown in the tutorial. Another minor thing, not sure if related. The inference takes longer (10 mins) than stated in the tutorial on my more recent CPU (i5-7500T).

Running `tsinfer ls /mnt/1TBSSD/tsinfer_test/simulation.sample`
I get:
```
2020-06-25 16:45:18,518 [4108] CRITICAL root: Traceback (most recent call last):
  File "/home/hbecher/.local/lib/python3.7/site-packages/tskit/trees.py", line 1665, in load
    return TreeSequence.load(path)
  File "/home/hbecher/.local/lib/python3.7/site-packages/tskit/trees.py", line 2171, in load
    ts.load(str(path))
_tskit.FileFormatError: File not in KAS format

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hbecher/.local/bin/tsinfer", line 10, in <module>
    sys.exit(main())
  File "/home/hbecher/.local/lib/python3.7/site-packages/tsinfer/__main__.py", line 5, in main
    cli.tsinfer_main()
  File "/home/hbecher/.local/lib/python3.7/site-packages/tsinfer/cli.py", line 469, in tsinfer_main
    args.runner(args)
  File "/home/hbecher/.local/lib/python3.7/site-packages/tsinfer/cli.py", line 157, in run_list
    ts = msprime.load(args.path)
  File "/home/hbecher/.local/lib/python3.7/site-packages/tskit/trees.py", line 1667, in load
    formats.raise_hdf5_format_error(path, e)
  File "/home/hbecher/.local/lib/python3.7/site-packages/tskit/formats.py", line 259, in raise_hdf5_format_error
    raise exceptions.FileFormatError(str(original_exception)) from original_exception
_tskit.FileFormatError: File not in KAS format
```

Cheers,
Hannes

**Comment by jeromekelleher** [comment]
Thanks for the bug report @hannesbecher! Not sure what's after happening here, but we'll clear it up in the next release.

Can you tell me what version of tskit you're using please?

**Comment by hannesbecher** [comment]
It’s tskit 0.2.3.

Re-running

python3 -m pip install tsinfer --user

I get:

Requirement already satisfied: tsinfer in ./.local/lib/python3.7/site-packages (0.1.4)
Requirement already satisfied: humanize in ./.local/lib/python3.7/site-packages (from tsinfer) (2.4.0)
Requirement already satisfied: tqdm in ./miniconda2/lib/python3.7/site-packages (from tsinfer) (4.36.1)
Requirement already satisfied: six in ./miniconda2/lib/python3.7/site-packages (from tsinfer) (1.12.0)
Requirement already satisfied: daiquiri in ./.local/lib/python3.7/site-packages (from tsinfer) (2.1.1)
Requirement already satisfied: numcodecs>=0.6 in ./.local/lib/python3.7/site-packages (from tsinfer) (0.6.4)
Requirement already satisfied: lmdb in ./.local/lib/python3.7/site-packages (from tsinfer) (0.98)
Requirement already satisfied: sortedcontainers in ./.local/lib/python3.7/site-packages (from tsinfer) (2.2.2)
Requirement already satisfied: msprime>=0.6.1 in ./.local/lib/python3.7/site-packages (from tsinfer) (0.7.4)
Requirement already satisfied: zarr>=2.2 in ./.local/lib/python3.7/site-packages (from tsinfer) (2.4.0)
Requirement already satisfied: numpy in ./miniconda2/lib/python3.7/site-packages (from tsinfer) (1.16.4)
Requirement already satisfied: attrs in ./.local/lib/python3.7/site-packages (from tsinfer) (19.3.0)
Requirement already satisfied: python-json-logger in ./.local/lib/python3.7/site-packages (from daiquiri->tsinfer) (0.1.11)
Requirement already satisfied: tskit in ./.local/lib/python3.7/site-packages (from msprime>=0.6.1->tsinfer) (0.2.3)
Requirement already satisfied: fasteners in ./.local/lib/python3.7/site-packages (from zarr>=2.2->tsinfer) (0.15)
Requirement already satisfied: asciitree in ./.local/lib/python3.7/site-packages (from zarr>=2.2->tsinfer) (0.3.3)
Requirement already satisfied: svgwrite in ./.local/lib/python3.7/site-packages (from tskit->msprime>=0.6.1->tsinfer) (1.4)
Requirement already satisfied: jsonschema in ./miniconda2/lib/python3.7/site-packages (from tskit->msprime>=0.6.1->tsinfer) (2.6.0)
Requirement already satisfied: h5py in ./.local/lib/python3.7/site-packages (from tskit->msprime>=0.6.1->tsinfer) (2.10.0)
Requirement already satisfied: monotonic>=0.1 in ./.local/lib/python3.7/site-packages (from fasteners->zarr>=2.2->tsinfer) (1.5)

Thanks,
Hannes

**Comment by benjeffery** [comment]
I can confirm I can re-create this bug. Looking into it.

**Comment by benjeffery** [comment]
This bug was fixed already on the master branch and will not happen in the next release. You can install master with `pip install git+https://github.com/tskit-dev/tsinfer` BUT note that master is NOT stable and may have other issues.

**Comment by hannesbecher** [comment]
😊 thanks for the info. I guess it is not so urgent for me then.
Hannes

**Comment by jeromekelleher** [comment]
OK, I guess we can close this bug then, thanks for following up @benjeffery.

The tsinfer release has been far too long coming, we will get it out in a few months @hannesbecher. There's a bit of a release queue at the moment though!
