### ISSUE TITLE
Ancestors time-binning

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#284]
Closely related to the issue in https://github.com/tskit-dev/tsinfer/issues/276 is the fact that when there is missing data, many frequencies (i.e. times) will contain very few ancestors (because `freq = num_derived / num_nonmissing`, and there are often not many sites with the same `num_nonmissing` value). Since we only parallelise within a single timepoints, this  means that when we match_ancestors, we often can't parallelise easily, and this causes a huge slowdown.

We can solve this by dropping similar times into the same time bin, and parallelising with a time bin. @jeromekelleher thinks this should be an option built-in to tsinfer (presumably in `match_ancestors`), and I agree. @awohns has also needed this functionality when re-inferring from a tsdate-d tree sequence.

However, there are some gotchas:

1. This is only necessary when num_threads > 1. We should probably not even bother when doing single-threaded inference, as it's a bit of a hack
2. We probably want to retain the original ancestor times, especially if they have been passed into via tsdate, so we if we change the `ancestors_time[:]` value to a binned value when building ancestors, we might want to reinstate it to the original value afterwards.
3. We probably want to allow the user to pass in the time bins as a parameter to `match_ancestors`, called something like `parallel_timeslices`, and emphasise in the docs that this simply helps parallelisation. I guess we would expect the user to pass in an array of times, [x1,x2,...xn] and always have the first time bin as [0,x1), the second as [x1..x2), and so forth up to [xn..max_time]. This half-open interval matches the ones used for tree positions. We also want a way for the user to say "do this, but use default time bins", and I think the standard bins should be simply based on frequency counts. For example the middle of each bin could be 1/num_samples, 2/num_samples, ...., meaning that [x1, x2, x3, ...xn]=0.5/num_samples, 1.5/num_samples, 2.5/num_samples... num_samples-0.5/num_samples]. I'm not sure how to specify this: for example should we allow *either* an array *or* a string (e.g. "frequency"), or should we provide a function for making the necessary array instead, so that the user has to call `match_ancestors(..., parallel_timeslices=sd.freq_bins())` or something ugly like that?
4. Note that binning might interact with path_compression (because that happens after each time slice is completed). I'm not sure if this is a problem or not.

**Comment by hyanwong** [comment]
Note that restricting matching to ancestors only older than a certain time (point 2. above) is essentially what we need for matching ancient samples into an existing tree sequence (see https://github.com/tskit-dev/tsinfer/issues/207 ), so we might be able to implement this too, or at least lay the groundwork for it.

**Comment by hyanwong** [comment]
There's a nasty wrinkle that I only just thought about. If we bin an ancestor A with the derived state at site S into the same timeslice as the ancestor where S is a focal site, then A will have nothing to copy from. In this case, it will presumably be placed as an independent mutation.

**Comment by benjeffery** [comment]
This was fixed by #828
