### ISSUE TITLE
Ancestors time order required? Or not documented

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#286]
We [never seem to enforce](https://github.com/tskit-dev/tsinfer/blob/ba418b7aad37d2d4f8befce1b6378c1dc3427e7e/tsinfer/formats.py#L1971) the order of ancestors added to ancestors_data file, but inspecting one created, it looks like they are always in time order, with the oldest first. I assume this is required for later inference.

Should we 
a. check when we `add_ancestor` that the time of an added ancestor is less than or equal to the last added ancestor? OR
b. sort the ancestors on `finalise()`

a. is easier, b. would allow us to add ancestors in any order, e.g. adding additional ones into an existing file. I'm happy to implement b. if this is thought to be a good idea, @jeromekelleher

**Comment by jeromekelleher** [comment]
I think we have to enforce ordering here @hyanwong for performance reasons. Resorting the ancestors data would involve pulling the whole dataset back into memory on finalise, and would end up being quite expensive/finicky to optimise.

The simplest thing for now at any rate is to check the time in ``add_ancestor``, I think.
