### ISSUE TITLE
Mapping non-inference mutations as an independent function?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#298]
In several cases we want to [union](https://github.com/tskit-dev/tskit/pull/623) some inferred tree sequences together. For example, we might have matched UK-Biobank against an ancestors tree sequence to get a tree sequence TS_1, then matched the 1000 genomes samples against the same ancestors tree sequence to get another tree sequence, TS_2. When we union TS_1 and TS_2 together, the edges and nodes are the same, but the non-inference sites may have been mapped differently, so the union fails.

One way round this is to do the non-inference mapping separately, and make it possible to turn this off (with the warning in the docs that the haplotypes in the resulting TS will not be identical to the input if off). The function to add the non-inference sites could then be made publicly available, so it could be run after the fact. Alternatively, we could remove the non-inference-site mutations, and put them back on afterwards. Or lastly, and perhaps most sensibly, we could implement a tsinfer-compatible-union which takes not only a mapping of nodes from one TS to the other, but also list of sites whose mutations will be zapped and remapped to make consistent.

**Comment by jeromekelleher** [comment]
Having an indepdent function to do the mapping sounds like a good idea and a good starting place anyway - it would simplify things a bit I think. Basically, take a ts and sample data file as input, and every site that's in the sample data file and not in the ts, we try to push it in using parsimony. We could provide an explicit argument for ``sites`` as well, I guess.

**Comment by petrelharp** [comment]
What are the "non-inference sites", out of curiosity, @hyanwong?

**Comment by hyanwong** [comment]
> What are the "non-inference sites", out of curiosity, @hyanwong?

Mostly singletons, but also things like triallelic sites, or sites where we are uncertain of the ancestral state.

**Comment by hyanwong** [comment]
Another reason to want something like this is not just to re-map mutations onto existing sites, but to *add* sites to a tree sequence. For instance, for simplicity, @awohns is inferring tree sequences without indels, but we might want to add the indels in afterwards. I could imagine a function that took an inferred tree sequence and a sample data file with all the sites in the tree sequence plus some more, and which added in the sites using map_mutations.

**Comment by hyanwong** [comment]
Currently, I think we switch to a new tree exactly at at inference site, so that in the regions between full inference sites, the tree corresponds to the one that applies to the previous site. When adding sites into these intermediate region, we currently dump them onto the tree inferred from the previous site, but it might be that they are more parsimoniously placed on the next tree instead. A more sophisticated mutation-mapping function could be imagined that allowed Fitch-parsimony-placed mutations to change the exact edge boundaries - this would basically mean running the map_mutations method on each site using the trees to left and right, and placing the edge change at the position that produced the fewest mutations. It's a bit fiddly, and not a priority, but worth mentioning in this issue.

**Comment by hyanwong** [comment]
Yet another use for a tsinfer "map_mutations" function that takes an inferred TS and makes sure that it fully recreates a sample_data file, by mapping mutations as necessary is described as point 4 in https://github.com/tskit-dev/tsinfer/pull/300#issuecomment-665117526
