### ISSUE TITLE
Merge sample data files

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsinfer#299]
Provide a method to merge two (or more) sample data files. I guess we can require that the set of sites are present, so that we're just adding new columns into the genotype matrix?

cc @hyanwong @awohns 

I'll do this once #266 is merged.

**Comment by awohns** [comment]
I have a rough implementation of this function here: https://github.com/awohns/tsdate_paper/blob/master/all-data/tsutil.py

The approach I take is to add all the individuals and populations to a new, combined sampledata file then merge the sites using pandas: which checks position, ancestral, and derived alleles to combine sites. This approach seems to work but it isn't the most elegant thing in the world.

**Comment by jeromekelleher** [comment]
Semantics (decided in call with @awohns)

- Nonoverlapping sites are supported, and anything that's missing gets filled in with MISSING_DATA (we can add options later to make this be either REF or ancestral state later).
- Sites are matched by position. for each site, we check to see if the ancestral states are equal. If not, error out. Then, we build the joined allele list, and renumber the genotypes are needed.

Does this sound right?
