### ISSUE TITLE
Match Ancestors: Map ancestor ids

### ISSUE THREAD

**Issue by awohns** [tskit-dev/tsinfer#301]
In @hyanwong 's PR for matching noncontemporaneous samples, we need to keep track of the ID of the sample which was added as an ancestor. We can get the id of the ancestor that was added, but the ids change during match ancestors when path compression ancestors are added.

We think a extra parameter to match_ancestors which returns a mapping of node ids to ancestor ids would be helpful here, and better than simply iterating through the ancestors ts and adding +1 when we see a PC ancestor.
Thoughts, @jeromekelleher ?

**Comment by hyanwong** [comment]
I suggest that as with the `simplify` command, we have an optional `map_nodes` parameter, which causes the function to return a tuple containing the resulting tree sequence and a numpy array mapping ancestor IDs in the ancestors file to their corresponding node IDs in the returned ancestors tree sequence. This will be useful for #

**Comment by hyanwong** [comment]
Think about it, we should also add an equivalent parameter to match_samples, which not only adds path compressed ancestors, but by default also runs `simplify(keep_unary=True)` on the resulting TS, so that the nodes are completely jumbled by the end.

**Comment by awohns** [comment]
`Come to think of it, we should also add an equivalent parameter to match_samples, which not only adds path compressed ancestors, but by default also runs simplify(keep_unary=True) on the resulting TS, so that the nodes are completely jumbled by the end.`
I've been thinking about this bit, I think we would use simplify's `map_nodes` here too?

**Comment by hyanwong** [comment]
> I've been thinking about this bit, I think we would use simplify's `map_nodes` here too?

Yes, exactly. But we also will have a few extra nodes to account for (presumably ignore) because of the extra path compressed nodes.

**Comment by hyanwong** [comment]
As discussed in TreeTea, we could put this in the metadata info instead: that way it gets passed through without us having to do anything.
