### ISSUE TITLE
Tests potentially broken on python3.8 OS X

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#304]
In python 3.8 on OS X, the multiprocessing default has [changed from "fork" to "spawn"](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods), and on my machine, this seems to mess with running the test suite. I wonder if we could/should add python 3.8 to Travis to check whether this is an issue with my machine only?

I think at the moment Travis not only runs tests on OS X w/python3.6, but also linux Xenial , which seems a bit weird, as I thought that linux testing is mainly through circleCI. So perhaps we should replace the linux Travis tests with one under OS X / python 3.8? There's probably a reason why it is as it is, though.

**Comment by jeromekelleher** [comment]
What issues are you getting? Can you paste in some error messages please?

**Comment by hyanwong** [comment]
Well, it's not very helpful - it just segfaults, but one of the messages implies some sort of multiprocessing issue. This could be something weird in my installation, so I wondered if there was a way of testing on a vanilla 3.8 OS-X distro:

```
yan@Yans-New-Air tsinfer % python3 -m nose -v                                    
test_augment_ancestors (test_cli.TestCommandsDefaults) ... zsh: segmentation fault  python3 -m nose -v
yan@Yans-New-Air tsinfer % /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by jeromekelleher** [comment]
Can you run it through gdb, and backtrace? At least we'd see where the segfault is anyway.
```
gdb python3
run -m nose -v
# stuff
bt
```

**Comment by hyanwong** [comment]
Just revisited this. I think the segfault was a problem with my installation, but the warning is still there, e.g:

```
test_ancestor_comparison (test_evaluation.TestCli) ... /usr/local/anaconda3/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 8 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
ok
test_ancestor_properties (test_evaluation.TestCli) ... /usr/local/anaconda3/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 8 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
ok
test_ancestor_quality (test_evaluation.TestCli) ... ok
test_edges_performance (test_evaluation.TestCli) ... /usr/local/anaconda3/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 8 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
ok
```

**Comment by jeromekelleher** [comment]
Strange. Still, doesn't look like a major problem, particularly when it's just tests for the evaluation scripts. We can probably close this?

**Comment by hyanwong** [comment]
It's annoying to get the warnings, but, as you say, not fatal. Happy to close for the moment
