### ISSUE TITLE
Mark non-contemporaneous samples with a flag?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#314]
At the moment, when we do a "normal" inference, we put all the sample nodes at time 0, even if they are from a sample associated with an ancient individual. There's no helping this in the normal inference, but it would be useful to know in the resulting tree sequence which nodes are not from contemporaneous individuals. I propose to add a new flag, 'NODE_IS_NONCONTEMPORANEOUS_SAMPLE' for these nodes, so they can be easily identified. What do you think, @jeromekelleher ?

**Comment by jeromekelleher** [comment]
Since this is something happening external to tsinfer, it's probably better to put this information as metadata in the sample data file? Unless we're going to have a function for doing this?

**Comment by hyanwong** [comment]
I don't think it is external to tsinfer? When we make a SampleData file we can give times to individuals. When we infer using the standard tsinfer pathway, we then put samples from these individuals at time (=freq) 0. This is somewhat confusing, and I think flagging it up somehow is a generic part of tsinfer, rather than e.g. a tsdate specific thing?

**Comment by jeromekelleher** [comment]
Right, that's true. We should probably save the time that we originally associated with them in that case though - this is a useful value, presumably? So, we add a ``sample_data_time`` or something key to the metadata, and store that value in there?

**Comment by hyanwong** [comment]
Yes, I think we should have a flag *and* a little piece of metadata, as you suggest, in case people want further detail.

**Comment by jeromekelleher** [comment]
closed in #322
