### ISSUE TITLE
Fix samples iterator

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsinfer#316]
https://github.com/tskit-dev/tsinfer/commit/11cb3c033eba02216029f290576a3ee20df6874a#r40853295

Error introduced in #308

**Comment by hyanwong** [comment]
I had to implement a fix and there were a few things missing from your original PR, @jeromekelleher  - fix is at https://github.com/tskit-dev/tsinfer/pull/320

**Comment by hyanwong** [comment]
This can be closed now that #320 is merged
