### ISSUE TITLE
Unexpected behavior with individuals_population

### ISSUE THREAD

**Issue by awohns** [tskit-dev/tsinfer#319]
After the recent change referenced in #313, I've run into unexpected behaviour (I think a bug) when making SampleData files. It threw me for a loop for a long time, but I think I've isolated the issue.

When adding > 512 individuals with populations specified to a sampledata file, the individuals_populations Zarr array begins to record populations incorrectly. See the following trivial example:

```
import tsinfer
import numpy as np
with tsinfer.SampleData(sequence_length=10) as samples:
    samples.add_population()
    samples.add_population()
    [samples.add_individual(ploidy=2, population=1) for i in range(513)]
    samples.add_site(position=2, genotypes=np.zeros(513*2).astype(int))

np.unique(samples.individuals_population[:], return_counts=True)
>>>(array([0, 1], dtype=int32), array([513, 513]))
```
If 512 individuals are used instead of 513, the entire `samples.individuals_population[:]` array is filled with population 1, as expected.
Is something going on here with the Zarr array expecting inputs < 1kb?

**Comment by hyanwong** [comment]
@awohns  - I think your code above is missing a line that tabulates the output. But you are right: I've tried it with the latest tsinfer from GitHub, and it creates a `samples.individuals_population[:]` array that is the size of the number of samples (i.e. 513*2 in your example above), not the number of individuals, so something is obviously wrong.

**Comment by awohns** [comment]
Forgot the `np.unique`, edited now.

**Comment by hyanwong** [comment]
Fixed in https://github.com/tskit-dev/tsinfer/pull/320 @awohns
