### ISSUE TITLE
Dollo parsimony approach sub-optimal

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsinfer#32]
We are potentially using too many back mutations when placing non-inference sites. We should try to find clades of ancestral state samples and put mutations over those rather than just putting a back mutation over every sample.

Fix, and update docs in inference.rst.

**Comment by hyanwong** [comment]
I think this can be closed, @jeromekelleher ?

**Comment by jeromekelleher** [comment]
Closed in #179 and #180.
