### ISSUE TITLE
Add flags to an individual, to match tskit

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#324]
It seems sensible to match the Individual class in tsinfer as much as possible to a tskit Individual, so that we can convert between them. But tsinfer Individuals don't have a flags field. Should we add one?

**Comment by jeromekelleher** [comment]
Yes, it probably makes sense to add this. What will we use it for, though, other than round-tripping data from tskit (which we only do for testing - there's not much point in running tsinfer on something that's already in a tree sequence?)?

**Comment by hyanwong** [comment]
Well

a) I'm trying to make a few simple functions to compare between individuals & populations in a sample data file (#325), so this should make generic functions easier to add.
b) We do create individuals in tsinfer, and turn them into tree sequences, so we probably want to be able to move everything necessary that way through the pipeline.

I'll make a simple PR

**Comment by hyanwong** [comment]
This would be a format change, and so I guess it's a contender for going into  0.2.0, especially as the change is already in a commit. I'll look over the commit and check it works first
