### ISSUE TITLE
Adding ancient samples to the tsinfer pipeline

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#328]
After discussion with @jeromekelleher and @awohns around the topic of "historical" samples (i.e. those associated with an individual with non-zero `individuals_time`), we are closing https://github.com/tskit-dev/tsinfer/pull/300, where some relevant discussion has taken place, and will open up a new PR, with goal to create a new function which given an existing ancestor_data file and a sample data file, outputs a new ancestor_data file with added "proxy sample ancestors" based on some of the samples in the sample data file.

A "proxy sample ancestor" (other name suggestions welcome) is an ancestor that has exactly the same haplotype at inference sites as a sample, but is allowed to differ at other sites: the node (`v`) that it creates in the tree sequence will *not* be marked with `NODE_IS_SAMPLE`, and will *not* be associated with an individual. Each proxy ancestor will be added at a time `T+epsilon`, where `T` is the time of the corresponding individual. During the `match_samples` phase, the true sample will be matched and  should match exactly to the proxy ancestor at full inference sites. Given this is the case, it should then be possible to change the node time of the true sample to be exactly `T`, with the parent node `v` at time  `T+epsilon`.

We agreed that this should be the default way to include historical samples, as it provides a branch for placement of unique mutations (i.e. singletons) in the historical samples. 

### Additional notes:

Adding proxy sample ancestors at a user-specified time only makes sense when the ancestor times and the individual times use the same units. For example if the ancestors are using frequency as a measure of time, we should probably bomb out when adding historical samples, as the individuals_time is likely to be measured in years or generations. It would be nice eventually to encode the meaning of time in the top level metadata associated with ancestors and sample data files.

We need extra functionality in the `match_samples` stage. This would operate after matching a sample, and would attempt to change the node time of the sample if it is associated with a non-zero-time individual. It may be that this is impossible, in which case we should probably bomb out (and for this reason, we should probably try to match the historical samples first). We should make this an option to match samples - perhaps "force_historical_times" or something? Again, we should only allow this if the time units of the ancestors_ts are the same as the time units in the sample_data file.

The pipeline would presumably go:
1) generate `Ancestors_1` from the sample_data file with all samples, including historic ones
2) match ancestors
3) match samples *excluding* historical samples (but mapping non-full-inference sites such as singletons etc, as happens by default).
4) tsdate the resulting tree sequence, which should have no historical sample nodes (at the moment this involves simplifying to remove unary nodes, but if this is done, we should *not* filter sites) 
5) replace the site times in the sample_data file with (possibly unconstrained) site times from `tsdate`, and regenerate the ancestors to create `Ancestors_2`. We can't simply replace the times in the ancestors file, as site time changes may affect the actual generated ancestors*
6) NEW FUNCTION - create new ancestors file (`Ancestors_3`) with proxy sample ancestors included
7) match ancestors against the new `Ancestors_3`
8) match samples using `Ancestors_3`, but this time *including* historic samples (including adding singletons, historical-only mutations etc).
9) (optional) re-date the entire tree sequence.

[*] If there are any variants whose derived alleles are restricted to the historical samples only, then these will not have finite dates, and should probably be excluded from full inference. They *will* end up with dates in step (9) - if there are lots of them, and we want them to be used for full inference, we could then to a third round of iteration, i.e. repeat steps 5-9.

We might want to specify which samples to use as a basis for proxy ancestors. By default I would imagine adding those associated with a positive (non-zero) individuals_time (i.e. historic samples), but there are cases where we might want to add contemporaneous ancestors too (see next para)

I wonder if this should be a replacement for the `augment_ancestors` functionality: e.g. instead of augmenting the tree sequence with samples that we treat as ancestors, we simply make a set of proxy ancestors from the selected samples, placing them at `0+epsilon`, and then let match_ancestors do its stuff. This would work for the case where we matched UKB against the TGP ancestors+samples, but not for the repeated augmenting procedure with 2, then 4, then 8, etc proxy samples which we did for UKB.

Note that implementing this also should address https://github.com/tskit-dev/tsinfer/issues/208 and https://github.com/tskit-dev/tsinfer/issues/207

It seems sensible to be able to keep track of which samples were used for proxy ancestor generation by adding optional metadata to ancestors in the ancestors_data file (but I think this is nice-to-have, not required).

Have I forgotten anything?

**Comment by jeromekelleher** [comment]
This sounds good, thanks @hyanwong. I think we just decided that  NEW FUNCTION should be called something like ``AncestorData.insert_proxies(self, sample_data)``, or something similar.

**Comment by hyanwong** [comment]
> This sounds good, thanks @hyanwong. I think we just decided that NEW FUNCTION should be called something like `AncestorData.insert_proxies(self, sample_data)`, or something similar.

Great, thanks. I'll code this up today. FWIW, I was going to use `insert_proxy_samples(self, sample_data, *, sample_ids=None, **kwargs)` as the method.

**Comment by awohns** [comment]
Just had a close read, this looks _excellent_ to me @hyanwong. 

In particular, I like your idea to `generate` and `match_ancestors` including historic samples, but exclude them from `match_samples` in the first pass. Also, checking for time unit consistency is important.

**Comment by hyanwong** [comment]
Two problems I have just encountered:

1. If there are any exactly identical ancestors in the file, but that exist at a younger time, then the match_samples algorithm could match a historical sample against the non-proxy ancestor, and then we might not be able to push the age of the sample backwards in time enough. This happens in simple test cases, (`ts = msprime.simulate(samples=[msprime.Sample(0, t) for t in (0.0, 0.0, 1.0, 1.5, 15)], recombination_rate=0.1, mutation_rate=10, random_seed=123)`) but might not be an issue in real data, where we are vanishingly unlikely to have an exactly identical ancestor to an particular sample. Still, it makes me uncomfortable.

2. A proxy ancestor could contain a derived variant but we have dated that variant to be more recent than the sample on which the proxy ancestor is based. In this case, I guess we should bomb out when calling `insert_proxy_samples`?

**Comment by hyanwong** [comment]
> A proxy ancestor could contain a derived variant but we have dated that variant to be more recent than the sample on which the proxy ancestor is based

In https://github.com/tskit-dev/tsinfer/pull/331/commits/1b5012480eda3d3b7ea1d3031ae17e45e856e28d I've added a `allow_mutations` parameter to `insert_proxy_samples()`  so that we can chose to bomb out or not.
