### ISSUE TITLE
Treatment of SampleData files with only some user-specified site times

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#330]
Is it sensible to allow users to set a bespoke time for a site (`SampleData.add_site(time=XXX)`) if we are using the allele frequency as a proxy for time? Or, if there are any bespoke times specified, should we assume that the other sites (where time is unspecified) should not be used for inference? In other words, should we only use time=freq if *all*  sites_time values are `tsinfer.TIME_UNSPECIFIED`, and otherwise just mark sites with unspecified times as not-for-inference?

**Comment by jeromekelleher** [comment]
Not sure. We could raise an error if someone tries to mix known/unknown times in a SampleData file, which is probably the simplest way to make sure that these issues don't crop up. If it turns out there's a good reason for doing it, we can relax the requirement and decide what the semantics should be.

**Comment by hyanwong** [comment]
There are cases where we don't know the time for a site (this was the original reason I asked) - e.g. if a site has derived alleles only in historical samples, and we omit those samples when matching. This could happen in Wilder's pipeline, and if so, we would probably want to simply not do full inference on those sites.

**Comment by hyanwong** [comment]
NB - either way, we should probably allow unknown times for sites that are not used for inference (e.g. invariant sites, for a start).

**Comment by jeromekelleher** [comment]
Yes, true.

**Comment by hyanwong** [comment]
With #363, the situation has changed a little. We use `tskit.UNKNOWN_TIME` to mark sites where time is specifically intended to be freq, and simply `np.nan` for sites which shouldn't be used in inference (like an invariant site). So I think this makes everything easier:

We check if any sites are finite. If so, we check that there are no sites marked with `tskit.UNKNOWN_TIME` (and raise an error if so, saying you can't mix finite times with UNKNOWN (i.e. freq-based) times). We also say that if you do specify finite times, you can use np.nan for sites that are not to be used in inference, if you want, although if you have a site time but simply want to exclude the site form inference, it's more flexible to use the `exclude_positions` parameter in `generate_ancestors`.
