### ISSUE TITLE
sampledata.site_times_bound()

### ISSUE THREAD

**Issue by awohns** [tskit-dev/tsinfer#335]
It would be helpful to have a function of the `SampleData` class which returns a numpy array of length `sampledata.num_sites` with the age of the oldest individual with a derived allele at each site.

For instance, if a SampleData file has a historic sample at time 1000, the function would return 0 at all sites where the historic sample has the ancestral allele and 1000 at sites where it has the derived allele. If there were two historic samples aged 100 and 1000 and _both_ had a derived allele at a given site, 1000 would be returned.

Was just discussing this with @hyanwong. It could be a function in tsdate (it lives in an unmerged branch right now) but it feels more like a function for tsinfer. What do you think @jeromekelleher? Could easily remain in tsdate though as an auxillary function for returning "dated" SampleData files.

**Comment by jeromekelleher** [comment]
Sure, sounds like a good idea. Maybe open a PR with the proposed method?
