### ISSUE TITLE
Switch to tskit.UNKNOWN_TIME?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#336]
We are currently using `tsinfer.TIME_UNSPECIFIED = -np.inf`. Should we switch to the newly instituted `tskit.UNKNOWN_TIME` which is a specific sort of NaN value, instead?

**Comment by jeromekelleher** [comment]
Yes, that would make sense. We can do this as part of the tskit 0.3.0 update.

**Comment by hyanwong** [comment]
I think we should do this for tsinfer 0.2, as it will involve a format change in the sample data files.
