### ISSUE TITLE
Sensible warning should be given if trying to run infer on a tree seq file

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#342]
In #341 , @stsmall tried to run inference on a tree sequence file, not a sample data file.

```
tsinfer infer simulation-source.trees
```

And got `MDB_INVALID: File is not an LMDB file` - perhaps we should make this a more obvious error message?

**Comment by jeromekelleher** [comment]
Should be possible, all right. IIRC though, the errors coming out of LMDB aren't very granular, so it might be something we have to live with.

**Comment by hyanwong** [comment]
Can we explicitly check if it's a TS (e.g. using tskit) before trying to open it in LMDB? Or is that too expensive?

**Comment by jeromekelleher** [comment]
Yeah, you could do either of these. Neither would be particularly expensive. I'd say do whichever one leads to less ugly code.
