### ISSUE TITLE
Switch to default metadata being `null` rather than `{}`?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#352]
In tskit, if the metadata schema is JSON, then blank entries are filled with `null` rather than `{}`. In tsinfer (where the JSON format is assumed, and schemas have not yet been implemented), we set blank entries to be `{}` instead. It might help transition to the schema style if we switch to `null` to match tskit. I don't think this will cause any backwards incompatibilities, as `{}` will continue to be valid in old files. It seems like a trivial change to me - can you see any problems with this @jeromekelleher ?

**Comment by benjeffery** [comment]
I'm not sure about this - I wonder if `tsinfer` should be using the schemas? In the PR you have it seems that the user sets arbitrary JSON, I assume tsinfer then sets a permissive JSON schema on the tree-sequence it makes? I would expect the user to set the schema if they are setting metadata, that way tsinfer could support `struct` etc.

**Comment by hyanwong** [comment]
I think we should be using the schemas, but I'm assuming that's a lot more work. This is just to make it easier to to that in the long term.

**Comment by hyanwong** [comment]
P.s. issue here, @benjeffery - https://github.com/tskit-dev/tsinfer/issues/272. I don't feel competent to take that on, and I suspect you have too much on your plate to take this on in the next week!

**Comment by benjeffery** [comment]
Ah didn't see that issue! Great, if this is planned then I don't mind `null` for now.

**Comment by hyanwong** [comment]
Closing as a result of focussing on #272
