### ISSUE TITLE
Change "fitch_parsimony" to simply "parsimony"

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#355]
After https://github.com/tskit-dev/tskit/issues/987 is fixed, we aren't strictly using the Fitch algorithm. And the exact algorithm is probably not of interest to the user anyway. So I suggest that we simply change

```
INFERENCE_FITCH_PARSIMONY = "fitch_parsimony"
```

to

```
INFERENCE_PARSIMONY = "parsimony"
```

We could even make this change now.

**Comment by jeromekelleher** [comment]
Agreed. I think the idea was that we might have more sophisticated parsimony at some point in which nucleotide transition matrices are taken into account, but we can add some qualifier later if this becomes the case.
