### ISSUE TITLE
Make a new "AncestorsTreeSequence" class as a tsinfer wrapper for a tree sequence.

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#368]
A sudden thought: wouldn't it be easy to do

```
class AncestorsTreeSequence(tskit.TreeSequence):
    """
    Description: an ancestors tree sequence is just like a normal one, only all the nodes are marked as samples, etc etc.
    """
    pass
```

And ensure that we return one of these from match_ancestors. Then we can check when we `match_samples` that we're feeding an AncestorsTreeSequence, rather than any old TS into the algorithm.

The AncestorsTreeSequence would still have all the methods etc of a tree sequence, so I don't think functionality would be reduced at all. I guess the only issue would be that if you stored one in a file, you would have to remember to do:

```
ancestors_ts = tsinfer.load("my_ancestors_ts.trees")
```

rather than

```
ancestors_ts = tskit.load("my_ancestors_trs.trees")
```

But actually I prefer that, as then you don't need to even import tskit (or know that it exists) to load up the files necessary for inference.

**Comment by hyanwong** [comment]
And further (this is probably a different issue, TBH), could we make `match_samples()` a method of an AncestorsTreeSequence. Then if we made `match_ancestors()` a method of an AncestorData object, we could do inference like this:

```
ancestors = tsinfer.generate_ancestors(samples)
anc_ts = ancestors.match_ancestors(samples)
final_ts = anc_ts.match_samples(samples)

# Or for short
final_ts = tsinfer.generate_ancestors(samples).match_ancestors(samples).match_samples(samples)
```

**Comment by jeromekelleher** [comment]
I'm pretty solidly against the idea of using inheritance like this - the TreeSequence class isn't designed to be extended and it would cause more problems than it would solve. The SlimTreeSequence class has proved to be quite brittle, and it would have been better to use a different approach, IMO.

**Comment by hyanwong** [comment]
OK - you clearly know best here. It would be good to document what an Ancestors Tree sequence is, though, and how if differs from a normal tree sequence. Is there code that tells people what's wrong if they attempt to use a normal TS in place of an ancestors TS? I can imagine this happening.

How about the other suggestion, to make `match_ancestors` a method of an ancestors_data instance? It's less neat without the `.match_samples()` method on an ancestors TS, but still seems logical to me.

**Comment by jeromekelleher** [comment]
I don't see much point in changing these APIs for this release - it's not actually enabling people to do anything new and would break code for no real benefit.

**Comment by hyanwong** [comment]
Fair enough. I liked the idea when an ancestors tree sequence was a different sort of tree sequence, as the chaining seemed very logical. But without that, it's not quite so clean anyway.

I'm still yearning to flag up the ancestors TS as a "special" sort of TS somehow - perhaps with a top level attribute or something. It seems a bit confusing to me to have it as a normal TS with bespoke, mostly undocumented behaviour (e.g. all nodes are sample nodes, etc etc).
