### ISSUE TITLE
Convert cM to probability of recombination

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#398]
As @JereKoskela pointed out, the distance in cM between sites is only a good measure of probability of recombination for small distances. To allow for larger distances, it might be sensible to convert the genetic distance to actual probability of recombination (e.g. see [the wikipedia article](https://en.wikipedia.org/wiki/Centimorgan#Relation_to_the_probability_of_recombination) ):

```
(1-exp(-2 * dist_in_morgans))/2
```

This would mean that users wouldn't be able to specify a pathological recombination probability, e.g. by setting recombination_rate to 1 in a 1Mb genome, which was causing problems in testing ([the last bullet point here](https://github.com/tskit-dev/tsinfer/pull/395#issue-532845030) ). It wouldn't stop users specifying probabilities greater than 1 if they set the `recombination` array directly, but that's not documented, so _caveat emptor_. However, the maximum probability that could occur along the genome would be 0.5 rather than 1, and therefore this line in the algorithm:

https://github.com/tskit-dev/tsinfer/blob/7f69d59b37217146b700364fa2de0da4fefc56c8/tsinfer/algorithm.py#L725

would max out at `(1 - 0.5 + 0.5/n)`, rather than the more expected, symmetrical value of `1/n` 

Perhaps this is OK, though, as the value is always going to be used in proportion to the mismatch rate? Otherwise we might want to e.g. multiply it by 2 - although we'd need to think through the rationale carefully.

That brings up the point that it would still, however, be possible to set a mismatch ratio which created mismatch probabilities greater than 1 because, at the moment, we simply multiply the recombination probability by the mismatch ratio. It might be useful to scale the mismatch ratio somehow too, so that even if someone set a ratio of (say 1000), if the recombination probability were 0.5, we didn't set a mismatch probability at that site of 500.0. That raises the question: if the recombination probability is maxed out, at near 0.5, what does it mean to have a mismatch probability that is 1000 times higher? Is that even a meaningful statement?

Incorporating the formula above into a (new) RecombinationMap object would be ideal, but for the moment, I think we should just hard code it into the tsinfer part of the algorithm, when converting rate to LS probabilities.

**Comment by hyanwong** [comment]
> Perhaps this is OK, though, as the value is always going to be used in proportion to the mismatch rate? Otherwise we might want to e.g. multiply it by 2 - although we'd need to think through the rationale carefully.

I've done some more thinking about this. It's helpful to imagine the situation where we have *all* the ancestors, in every generation. In this case, the `p_no_recomb`  value probably should max out at 0.5, to account for the correlation between ancestries caused by having the same parents (the same reason why [trees on different chromosomes are correlated in the first few generations](https://github.com/tskit-dev/msprime/pull/1299/files)). In this case it might still be useful to have a mismatch probability of `1/n`, meaning that the value at this site is completely arbitrary, so even if there's a conflict, it is preferable to stay copying from the same chromosome. So I think that the mismatch probabilities should max out at `1/n` and the recombination probabilities should max out at 0.5.

As the number of generations between ancestors goes above 1, the maximum recombination probabilities should, in principle I think, start maxing out nearer `1/n` than 0.5, but that's an extra wrinkle that I, personally would be happy to ignore for the time being, especially since this stuff only applies in really extreme cases, where loci are separated by huge recombinational distances.

**Comment by hyanwong** [comment]
@jeromekelleher - could I have a little clarification here. There's a line in the matching algorithm: https://github.com/tskit-dev/tsinfer/blob/7f69d59b37217146b700364fa2de0da4fefc56c8/tsinfer/algorithm.py#L728

Which does a different thing when rho is >> 1, because then `p_no_recomb` becomes negative, and the condition is never true. I think this is in the guts of the likelihood-on-a-tree code, so I'm a little out of my depth here (although I should get you not explain it all to me some time!)

My suggestion above is that what you are calling `rho` here (which I think of as the probability of recombination between this site and the previous one, rather than "rho", the recombination rate), should be limited so that it is never greater than 0.5.

**Comment by hyanwong** [comment]
Similarly here: https://github.com/tskit-dev/tsinfer/blob/7f69d59b37217146b700364fa2de0da4fefc56c8/tsinfer/algorithm.py#L736 if mu >> 1 (or, in fact, if mu is, say 0.1 but `num_alleles` is >= 12, then `p_e`  (the emission probability, I assume) become negative, which doesn't seem very desirable to me.

**Comment by hyanwong** [comment]
Oh, and finally, would it be less confusing to replace `rho` with `r` (or `r_prob`) and `mu` with `m` (or `m_prob`) in the python algorithm?

**Comment by jeromekelleher** [comment]
I think rho and mu are fine here, fairly standard notation.

**Comment by hyanwong** [comment]
We should add this to 0.2.0

**Comment by hyanwong** [comment]
If we do what I suggest above then we would use r(x1, x2), maxing out at 5, for the HMM probabilities, where

`rho(x)` = recombination rate at position x
`d(x1, x2)` = genetic map distance in Morgans, i.e. mean number of recombinations between position x1 and x2 = `Integral_x1^x2 (rho(x))`
`r(x1, x2)` = probability of (an odd number of) recombinations between x1 and x2 = `(1-exp(-2 * d))/2`

And for mismatch ratio, say M, we would want the feature that for small r, the mismatch *probability*, (m) is approximately M*r, but maxes out at 1. A function that would do this is to set

`m = (1-exp(-d * M))`

Here are some examples of how that would pan out, for different genetic distances with the mismatch_ratio, M, set to 0.1, 1, and 100. You can see that it does the expected thing for map distances below about 1e-03, i.e. 0.1 centiMorgans. Above that, the "ratio" is affected by the upper bound a little, but I think that's inevitable. For instance, if 2 loci are 1cM apart (d=1e-2) then setting `M=mismatch_ratio=100` will multiply the probability of recombination by 62, not by 100, whereas if  `M=mismatch_ratio=0.1` it will multiply it by 0.1009 not 0.1.

```
d (genetic distance)            r     m(M=0.1) ratio(M=0.1)       m(M=1) ratio(M=1)     m(M=100) ratio(M=100)
               1e-08 1.000000e-08 1.000000e-09    0.1000000 1.000000e-08   1.000000 9.999995e-07    99.999951
               1e-07 9.999999e-08 1.000000e-08    0.1000000 9.999999e-08   1.000000 9.999950e-06    99.999510
               1e-06 9.999990e-07 9.999999e-08    0.1000001 9.999995e-07   1.000000 9.999500e-05    99.995100
               1e-04 9.999000e-05 9.999950e-06    0.1000095 9.999500e-05   1.000050 9.950166e-03    99.511613
               1e-05 9.999900e-06 9.999995e-07    0.1000010 9.999950e-06   1.000005 9.995002e-04    99.951016
               1e-04 9.999000e-05 9.999950e-06    0.1000095 9.999500e-05   1.000050 9.950166e-03    99.511613
               1e-03 9.990007e-04 9.999500e-05    0.1000950 9.995002e-04   1.000500 9.516258e-02    95.257776
               1e-02 9.900663e-03 9.995002e-04    0.1009528 9.950166e-03   1.005000 6.321206e-01    63.846283
               1e-01 9.063462e-02 9.950166e-03    0.1097833 9.516258e-02   1.049958 9.999546e-01    11.032810
               1e+00 4.323324e-01 9.516258e-02    0.2201144 6.321206e-01   1.462117 1.000000e+00     2.313035
               1e+01 5.000000e-01 6.321206e-01    1.2642411 9.999546e-01   1.999909 1.000000e+00     2.000000
               1e+02 5.000000e-01 9.999546e-01    1.9999092 1.000000e+00   2.000000 1.000000e+00     2.000000
               1e+03 5.000000e-01 1.000000e+00    2.0000000 1.000000e+00   2.000000 1.000000e+00     2.000000
```
