### ISSUE TITLE
Cannot match if mismatch probabilities are 1 (assertion fails in PY_ENGINE, path not found in C_ENGINE)

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#402]
In my attempts to crash the PY_ENGINE implementation of the matching algorithm, I find I can trigger an assertion error by setting the mismatch probabilities to 1. Perhaps we don't care, as this is only the python side and the C_ENGINE just returns `_tsinfer.LibraryError: Match impossible under input parameters.`, but I flag it up in case it's emblematic of a deeper issue. 

```
ts = msprime.simulate(10, mutation_rate=1, random_seed=1)
sd = tsinfer.SampleData.from_tree_sequence(ts, use_sites_time=False)
anc = tsinfer.generate_ancestors(sd)
num_loci = anc.num_sites
r = np.full(num_loci - 1, 0.1)
prob = 1
m = np.full(num_loci, prob)
tsinfer.match_ancestors(sd, anc, recombination=r, mismatch=m, engine=tsinfer.PY_ENGINE)
```

gives

```
  File "tsinfer/tsinfer/algorithm.py", line 910, in find_path
    self.update_site(site, h[site])
  File "tsinfer/tsinfer/algorithm.py", line 744, in update_site
    assert self.mismatch[site] == 0
```

Also if we set `prob` to much greater than 1 (e.g. 100), the PY_ENGINE never completes but seems hang at 100%CPU, even on this very small example. Interrupting it appears to suggest that it may be caught in an infinite `while` loop:

```
    left, right, parent = matcher.find_path(haplotype, start, end, match)
  File "tsinfer/tsinfer/algorithm.py", line 960, in find_path
    return self.run_traceback(start, end, match)
  File "tsinfer/tsinfer/algorithm.py", line 1011, in run_traceback
    while self.allelic_state[v] == -1:
```

If we implement https://github.com/tskit-dev/tsinfer/issues/398 then it should be impossible to set these pathological values using the documented interface, although it would still be possible to pass them in using the undocumented `mismatch` and `recombination` parameters, as above.

**Comment by jeromekelleher** [comment]
Good stuff, thanks @hyanwong. Sorting out this behaviour will help us figure out what to do for #233

**Comment by hyanwong** [comment]
I'm adding some tests to test_inference and flagging them up for skipping, so we have them there to test better behaviour.

**Comment by hyanwong** [comment]
> I'm adding some tests to `test_inference.py` and flagging them up for skipping, so we have them there to test better behaviour.

**Comment by hyanwong** [comment]
In #403 @jeromekelleher wanted to define mismatch such that values of 0.5 (rather than 1) gave the maximally uninformative emission probabilities. That means we should probably never set the mismatch probabilities to 1: they should always max out at 0.5 (we should warn people as such somewhere) Therefore these pathological mismatch values shouldn't ever be used, and we might be able to close this issue.

**Comment by hyanwong** [comment]
We might still want to investigate why mismatch values of 1 mean that a path cannot be found, however (even in the C code). I think that *logically* it should be possible. So perhaps we should leave this open but kick down the road to 0.2.1 or even 0.3

**Comment by jeromekelleher** [comment]
It seems logical enough to me. Suppose we had a reference panel of one hapotype, [0, 0] and we had a target haplotype of [0, 0] with a mismatch value of 1. Then the probability of all paths is 0, and therefore no match is possible.

**Comment by hyanwong** [comment]
Very good point. I forgot that at the start of match_ancestors there will probably be no haplotypes that disagree. I suspect this should work during match_samples, though.

**Comment by hyanwong** [comment]
I've just tested, and it does work in match_samples. Hurrah.

I see the problem now, the python assert didn't tackle the case when mismatch=1, when we can also get a zero likelihood. I'll change the logic and raise a correct error.
