### ISSUE TITLE
Are the HMM emission probabilities parameterised correctly?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#403]
Currently, the emission probabilities seem to be given by this line: https://github.com/tskit-dev/tsinfer/blob/7f69d59b37217146b700364fa2de0da4fefc56c8/tsinfer/algorithm.py#L736

That means when `mu` is 1 (which I would take to mean that the emitted allele is completely unrelated to the haplotype we are copying from) then for a 2-allele model, p_e is `1- (2-1) * 1 = 0` Can this be correct? Shouldn't the minimum emission probability be `1/num_alleles`, @jeromekelleher ?

**Comment by hyanwong** [comment]
Another thought: it would be better (at least in the match-samples phase) to use the actual allele frequency to determine the "uninformative" emission probabilities. If the derived allele is at freq `p`, then (assuming the underlying state is uninformative), the emissions should be `p` for the derived allele, and `1-p` for the ancestral allele.

This is a bit more difficult during the match_ancestors phase, because early in time, the derived allele will be at freq 0. But even if we used the current freq as a proxy for this, I suspect it would be better than using equal probabilities of 0.5/0.5.

**Comment by jeromekelleher** [comment]
The emission proba is based on the existing treatments: see, .e.g, [Rosen and Paten](https://almob.biomedcentral.com/articles/10.1186/s13015-019-0144-9), [Lunter](https://academic.oup.com/bioinformatics/article/35/5/798/5079326) and [Stepens and Donelly](https://arxiv.org/abs/1006.1514).

We have dropped the "coalescenty" terms from the emission proba in, e.g., S&D, as these are constants. But, we are, I think, consistent with the other derivations. How do you see what we're doing as different from these treatments?

**Comment by hyanwong** [comment]
Thanks for the links @jeromekelleher. I guess this is a question of the interpretation of the "mutation" rate: we aren't parameterising it as a mutation but potentially as an "error", which might change the angle we come at it.

Regardless, I can't see how it makes sense to allow negative emission probabilities in their formulations (e.g. for mu=1, A>2). I feel I should ask Gil about this anyway.

**Comment by hyanwong** [comment]
Easiest it to think about the extreme case: take a mutation (or mismatch) probability of mu=1. Do we mean that this is a probability of 1 that we mutate *to another state*, or a probability of 1 that we are hit by a mutagenic (or error-prone) process? The parameterisation in Rosen and Paten (for example) assumes the first: `1-(A-1)mu`, so that for A=2, if mu is 1, we cannot match any more, and are forced to switch (emission probability is 0 => this path becomes impossible).

I would argue that if we are thinking of this in terms of error, the maximum mismatch probability should correspond to the case where the current copying path provides no information about the emitted state. That's a different parameterisation of the emission probs.

This feels like something to chat about face-to-face, TBH.

**Comment by hyanwong** [comment]
Actually, reading though the papers, Equation 4.2 in Stephens and Donelly uses my suggestion, not that in Rosen and Paten, I think?

![Screenshot 2020-12-09 at 12 30 32](https://user-images.githubusercontent.com/4699014/101630132-57b56b00-3a1a-11eb-99e6-481c2869ef02.png)

As they say: "Notice that as θ → ∞ the alleles 0 and 1 at any given site become equally likely", which is definitely not true for the Rosen and Paten formulation.

**Comment by jeromekelleher** [comment]
I spent a long time working on this in the context of the general purpose code for tskit, and I'm happy with the independent-of-n parameterisation of the emission probabilities. The clearest implementation is [here](https://github.com/tskit-dev/tskit/blob/main/python/tests/test_haplotype_matching.py#L75). There's plenty of precedent for doing it this way, and S&D do say that the mutation values don't matter much. We can always add an option to change the behaviour later if we wish.

Unless there's an obvious actual error in what we're doing we shouldn't change things now - we just need to state that this is what we're doing.

**Comment by hyanwong** [comment]
I think there is (essentially) an error for num_alleles > 2. As you say, `n` probably doesn't matter too much as we get to large numbers of haplotypes, but I think that there's a missing factor of num_alleles (i.e. 2) in the current parameterisation: it should be something like `(1 - (num_alleles - 1) * mu) / num_alleles` and `mu/num_alleles`. Otherwise we get nonsensical values for mu=1. The other option is to scale mu so that the maximum "mismatch_probability" is 0.5, rather than 1, but that seems a hack?

**Comment by hyanwong** [comment]
I mean. basically, we should never allow p_e or p_t to be less than 0 or greater than 1, otherwise we break the algorithm.

**Comment by hyanwong** [comment]
> You're right, the R&P parameterisation that I worked from is wrong for k > 2. Goddamit! Well spotted, thanks.

That's OK. I feel like I've been bugging you too much about this, so happy it's not been a waste of time for you or me.

> Hmm, this is a mess. Perhaps it's not so bad though: we can just disallow sites with > 2 alleles for inference. 

Yes, I think we can do this for the time being.

We don't actually count missing data as an allele, AFAIK, so this should be OK.

Hmm. I'm worried that we might. I'll check in a little bit, just to satisfy me, and if you're right, I'll update the docs.

> In practise, we don't use > biallelic sites for inference, anyway, right?

Correct. So I think we're OK in that respect.
 
> This is as a short-term fix to get 0.2 out the door.

Yes, I agree. But I do think that we need to decide whether a mismatch probability of 1 means that the value being emitted is always the exact opposite of that suggested by the hidden state, or if it means that the hidden state is (basically) uninformative about what allele is emitted. The first seems a bit weird to me, and I'm strongly inclined to go for the latter, which means (I think) dividing by a factor of 2 (well num_alleles, but we're going to constraining that to 2 anyway).

**Comment by jeromekelleher** [comment]
I think it's simplest to keep things parameterised as mu meaning "the probability of mutating to the other allele". If mu is 0 then we must have a match and if mu is 1 we must have a mismatch. Lunter also takes this view: "and pμ is the probability of a mutation to one of the three other nucleotides." - he hard-codes into the model the 4 nucleotide perspective.

**Comment by hyanwong** [comment]
> I think it's simplest to keep things parameterised as mu meaning "the probability of mutating to the other allele". If mu is 0 then we must have a match and if mu is 1 we must have a mismatch. 

Hmm, in that case we need to document it *really* carefully, I think, because I (and I suspect others) would assume that a "mismatch" probability of 1 means that the emitted state is random, not that it *cannot* match the haplotype.

If we do go down this route, I would rescale the mismatch ratio so that it could only ever produce "mismatch probabilities" from 0 to 0.5. It seems nonsensical that if we tweak the mismatch parameter up to high values, it will force everything to deliberately mismatch.

**Comment by hyanwong** [comment]
By the way, that's not what the parameterisation of the recombination rate does, so we're being a little inconsistent here, not that anyone but ourselves would notice. A recombination probability of 1 means there's a chance of recombining onto any haplotype, *including oneself*. A mismatch/mutation probability of 1 means there's a chance of mutation to any other allele *excluding oneself*.

**Comment by hyanwong** [comment]
We should also write this all down somewhere, for ourselves if nothing else, as we'll probably want to adjust for >2 alleles later, etc.

**Comment by hyanwong** [comment]
> We don't actually count missing data as an allele, AFAIK, so this should be OK.

As I suspected, we actually do. Fixed in #413 , but it defaults to counting them, except when passed to the tree seq builder. Perhaps we never want to count them (i.e. default to count_missing=False)

**Comment by hyanwong** [comment]
Closed & documented by #404
