### ISSUE TITLE
What's samples_metadata for?

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsinfer#412]
I'm going through the changes needed for including metadata schemas in #392 and dealing with ``samples_metadata``  is sucking up a lot of time. In particular, it really limits our flexibility in defining metadata schemas for nodes within tsinfer, because we have to allow users define schemas that are just relevant for the samples. Without this complexity, we'd be free to define our own struct schema which would allow us to efficiently encode information from the algorithm about nodes.

What's it for? I'm struggling to think of an example where we'd want to associate different metadata with the two nodes in an individual. Aren't the vast majority of cases we'd actually be interested in handled by individual metadata? Do we have any actual use cases for this, or is it a "this might come in handy at some point" feature?

@awohns - do you use ``samples_metadata`` in your code?

**Comment by jeromekelleher** [comment]
Looks like we had the ``samples/metadata`` field in the last-released version of tskit, but we didn't provide any API for setting it. So we're free to drop the column in the file format (since we're bumping the version number) and ``samples_metadata`` parameter to ``add_individual``.

**Comment by hyanwong** [comment]
I reckon you can probably kill it. It *might* be useful if you want to pass stuff through to the nodes in a tree sequence, but I can't see why that would be any more useful than passing the metadata via the individual.

The nodes keep their IDs between the sample_data file and the tree seq, don't they? So you could store metadata in the individual and indicate which node it was from anyway.

**Comment by jeromekelleher** [comment]
OK, will drop it.

**Comment by awohns** [comment]
I don't use it in my code, I think it's ok to drop. Yan and I discussed that you could store maternal and paternal ids in the individual metadata.
