### ISSUE TITLE
Missing data issue

### ISSUE THREAD

**Issue by angelgr2** [tskit-dev/tsinfer#426]
Greetings!

I recently started using `tsinfer` in one of our projects and I first wanted to say thank for your work on the software. Seems like an amazing tool and I'm looking forward to using it on future projects. At the moment, I am trying to infer tree sequences from sequencing data from a population of wild fish.

I've had success generating sequencing on very clean subsets of the data, but I am encountering some errors as I try to introduce missing genotypes to the dataset. Based on the [documentation](https://tsinfer.readthedocs.io/en/latest/api.html#tsinfer.SampleData.add_site), I was adding `tskit.MISSING_DATA` to the genotype array whenever I encountered a missing genotype.

```py
# Some pseudocode here
# After parsing a phased VCF, check the genotype field
genotype_list = []
...
if genotype == '.':
    genotype_list.append = tskit.MISSING_DATA
```

When troubleshooting, I am printing the `genotype_list` before calling the `add_site()` function, I see the missing genotypes encoded as `-1`, which I understood was correct based on the `tskit` [documentation](https://tskit.readthedocs.io/en/latest/data-model.html#missing-data).

```py
[1, 0, 1, 1, -1, -1, 0, 0]
```

However, when I try to add the site, I just keep triggering an error because of the encoding of the genotypes:

```py
ValueError: Genotypes values must be between 0 and len(alleles) - 1
```

I saw a few closed issues on related subjects on both the `tskit` and `tsinfer` GitHub pages (one example [here](https://github.com/tskit-dev/tsinfer/issues/153)), but it was not clear to me the correct fix. Similarly, I tried the `tsinfer.constants.UNKNOWN_ALLELE` in that previous issue, but it encodes the genotype as `255` and triggers the same error.

Am I using the `tskit.MISSING_DATA` correctly here? Is it still the proper way to declare missing genotypes and if so, is adding it at the level of the genotype array the right approach?

Thanks for your assistance and sorry if I am ignoring some simple fix in the documentation.

-Angel

**Comment by hyanwong** [comment]
Hi Angel - thanks for the report, and I'm glad you are using tsinfer. It sounds like you are using version 0.1.4, but missing data is only supported in the development version (the latest "docs"), which can only be installed from GitHub. We should probably include the version number in the docs somewhere, just to make this clear. To install the GitHub version, you can try:

```
python3 -m pip install git+https://github.com/tskit-dev/tsinfer
```

Note that we may soon be adjusting the file format to allow for metadata (https://github.com/tskit-dev/tsinfer/pull/392), so if you create sample data files with this version, they may not be usable with the next release (which should be in a week or two). The metadata update will probably happen today. Why not test out the current GitHub version just to check if it works as you expect, then wait 24 hours before running any critical analysis, by which time the format will, I think, have stabilised.

**Comment by jeromekelleher** [comment]
Hi @angelgr2, thanks for the report. We'll hopefully have a new version out in a few days, and we will be changing the file formats etc, so it's probably best to hold off until the release. Great to hear you're interested in using tsinfer!

**Comment by angelgr2** [comment]
Thanks Yan and Jerome. I will try the dev version first to try stuff out. There's still a bit of work to do on my end before running any critical analyses. Will keep an eye out for the new stable release.

**Comment by jeromekelleher** [comment]
OK - things are definitely going to break over the next few days though, so you'll probably need to rebuild your SampleData files.
