### ISSUE TITLE
Docs: list version number prominently on the doc pages

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#427]
We had a [report](#426 ) from a user who I think was looking at the [dev docs](https://tsinfer.readthedocs.io/en/latest/) but trying stuff out having installed the "stable" (0.1.4) version of tsinfer. It might be helpful to list the actual version number that the docs pertain to somewhere obvious on the docs pages? I couldn't find it on a qiciok scan, but I may just be overlooking the obvious. Do you know if this is an easy thing to incorporate, @benjeffery ? Or is it not worth sorting out anything if we are moving to a new docs system anyway?

**Comment by benjeffery** [comment]
The version is on the top of the sidebar - if it isn't a tag it says "latest"

**Comment by hyanwong** [comment]
Yeah, I guess I mean it would be useful to know if "latest" means `0.1.5.dev361+gdd8b117.d20201214` or whatever. Perhaps that's obvious to those in the know? I wasn't sure though.

**Comment by jeromekelleher** [comment]
I think this will be less of an issue once we get 0.2 out. Having said that, I'm really not sure how much value there is in having a "latest" version of docs, since we don't want anyone to *use* the latest version, and it's really just for developers.

**Comment by benjeffery** [comment]
I agree - this is fixed by having the default docs be the latest release. `Latest` is good for the early development phase though, but I think `tsinfer` is leaving that.

**Comment by hyanwong** [comment]
If "latest" was listed as "development - version `XXX.devYYY` it would be less misleading, I think. I do like having the "main" GitHub branch docs somewhere online, though.

**Comment by jeromekelleher** [comment]
It's hard to do this stuff with readthedocs - I've tried fiddling with it before and gave up. I think we need to wait for the new docs site to make this happen, it's not worth spending time on it now.

Agreed it's good to have a "development" version of the docs, ideally with some visual warning on the page that the docs are for unreleased code.

I'm going to close this as it's not really a tsinfer issue, more of a general how-we-do-things one.

**Comment by hyanwong** [comment]
We could open an issue in the "Administrative" repo, if we want to keep track of it. But by the sound of it, it might be resolved by whatever doc system we end up with anyway, so not sure it's worth an issue?
