### ISSUE TITLE
Add mismatch and recombination_rate arguments to the command line

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsinfer#435]
The CLI currently does not allow control of these parameters.

**Comment by hyanwong** [comment]
I have a PR to do this, but it's hard to know whether recombination and mismatch have actually been used during inference, so hard to test whether it works. In my opinion, the best way would be to add the mismatch and recombination args to the provenance data, and test for that.

This was already something I have wanted to do for a while, as at the moment it's difficult to know from an inferred tree sequence whether it was inferred with mismatch allowed or not. So I think we should merge https://github.com/tskit-dev/tsinfer/pull/558 and then add the mismatch and recombination rates to the provenance data.

However, there's a niggle about what to add to provenance if an entire RateMap is used. See https://github.com/tskit-dev/tsinfer/issues/332#issuecomment-867792691. I'm happy with whatever works here to be able to at least know that a recombination map was used, regardless of its actual contents for the time being.

**Comment by jeromekelleher** [comment]
If we store the CLI args in provenance (which I think we do?) then this should sort itself out. I don't want to get into storing actual maps as JSON data in provenance, it's a waste of time.

**Comment by hyanwong** [comment]
> If we store the CLI args in provenance (which I think we do?) then this should sort itself out. 

I had a look through the CLI code and couldn't find the parameters stored anywhere (however, I never use the CLI, so I might have missed something). Either way, I worry a little that no-one actually uses the CLI, but simply calls functions in the python interface, and then it becomes difficult to find out e.g. the mismatch parameters.

> I don't want to get into storing actual maps as JSON data in provenance, it's a waste of time

Yes, this seems additional burden which isn't really necessary. I mentioned it to @benjeffery and he pointed out that this is what we do in the msprime provenance, but that is probably overkill.

**Comment by hyanwong** [comment]
> Let's not get into provenance, it's mostly a waste of time.

I agree in general, but I would like to get the mismatch stuff out of the inferred tree sequence though. I think it's important.

> I think a lot of people are comfortable with CLIs and would prefer to interact with them over custom scripts (me included) so lets add the functionality we need to make them useful.

Sure, I'm happy to get the CLI working as you and others might need (although I do think that most people use the python interface in preference, but we should support both, whatever). Nevertheless, I'm not sure how to test whether mismatch etc has worked unless we store provenance somehow. I guess I could look in the debug stream?
