### ISSUE TITLE
Ability to change ancestral states *after* add_sites?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#45]
Something that turned up when chatting to @pkalbers, but that I think might be more generally useful. (I have a nasty feeling this might be very difficult, so perhaps there is a better alternative?). Most people inputting large datasets will be getting the haplotype information from one source and the ancestral states information from another. So it would be useful to be able to 

1) input all genotype data first, *without* designating ancestral states, then (before samples.finalize()) have the ability to make a second pass to allocate ancestral states. If ancestral state is unknown, the site should not be marked for inference.

2) take and existing samples file, and replace it with one where the ancestral states have been re-assigned (I suspect that people may wish to test different ancestral state reconstructions on the same dataset).

**Comment by jeromekelleher** [comment]
This is all doable. In principle anything can be edited in the .samples file, we just need to add APIs to do so. There's an API for editing the ``inference`` flag at the moment, we'll just have to think about  how to edit a particular site also.

**Comment by jeromekelleher** [comment]
Thinking about this again, it's simpler to just make a new sample data file, based on the old one. You're updating the entire genotype matrix if you change the ancestral/derived state, so there's no point in doing it in-place. There's a method for iterating over the genotypes efficiently which can be used.

**Comment by hyanwong** [comment]
Right, this is a sensible way to do it. I assume the method you are talking about is samples.genotypes(), which returns an index and a np array of (1,0). I presume where the ancestral state was wrong I would just invert the 0,1 matrix and pass it back in to add_sites(). BUT, I would also need to reverse the labels ["A", "T"], etc, and these don't seem to be returned by the `genotypes()` function. Is there any way to read them on iteration?

**Comment by jeromekelleher** [comment]
Just pull out the whole array: ``alleles = sample_data.alleles[:]``. Easy to reverse each alleles and invert the genotypes.

**Comment by hyanwong** [comment]
Oh, sorry, I see what you mean. I thought sample_data.alleles[:] contained all the sample data too, not just the allele names.

Note, however, that I can't find `sample_data.alleles`: did you mean `sample_data.sites_alleles`, or is the name going to change? 

Also, I assume they are in the same order as in the genotypes() iterator, so I can do e.g. 

```
for allele, (i, genotype) in zip(sample_data.sites_alleles[:],sample_data.genotypes()):
    new_sample_data.add_sites(...)
```

**Comment by jeromekelleher** [comment]
Yes, sorry, ``sample_data.sites_alleles``.  

You can zip together like above, or you can index into the ``alleles`` array using the sites ID ``i``.
