### ISSUE TITLE
Wrong version reported when installed locally (e.g. pip install -e)

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#454]
When I clone and install the current version of tsinfer by doing `python3 -m pip install -e .` from the tsinfer dir, it creates a version labelled something like 

```
>>> tsinfer.__version__
'0.1.2.dev567+gd683b97'
```

Rather that 0.2.devXXX

**Comment by jeromekelleher** [comment]
I can't reproduce this:
```
(venv) jk@tempest$ python3 -m pip install -e .
(venv) jk@tempest$ tsinfer -V
tsinfer 0.2.1.dev2+g88c5153
```
Are you sure you've cloned the upstream tsinfer and not your own fork (which probably wouldn't be up to date)?

What do you get if you run ``git tag``?

**Comment by hyanwong** [comment]
It's my own fork (and a separate branch within that), but rebased against upstream/main. Perhaps that's not enough to get the tags. If so, just close this, I guess, and sorry for the noise. I assumed it would get the version from something in the files, rather than a GitHub setting.

**Comment by hyanwong** [comment]
Looks like I need `git fetch upstream --tags` - didn't realised that. Thanks for the pointer @jeromekelleher
