### ISSUE TITLE
Add debug output for computed mismatch etc rates

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsinfer#455]
Currently not giving any useful information on this on the debug stream.

**Comment by hyanwong** [comment]
Yeah, good point. I can sprinkle some in, although outputting a huge array of mismatch values is probably a bad idea. Perhaps we can quote means and variances, if we want to give some feel for the values being used?

**Comment by jeromekelleher** [comment]
Yes, exactly. We'd like the mean, max, and min I think.
