### ISSUE TITLE
SampleData bombs out when no sites have been added

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#46]
In the extreme case where we have no sites (but do know how many samples we have), and create a `SampleData()` instance but do not add any sites, then `finalise()` bombs out with `TypeError: _finalise_samples() missing 1 required positional argument: 'num_samples'`.

Although it's obviously a ridiculous example, I can see some edge cases where you might want to create a SampleData instance with no sites, and store metadata etc in the file. Perhaps there should be an optional argument to `SampleData.__init__` or perhaps SampleData.finalise() to provide the number of samples if it is not given. Even if not, a more sensible error message should probably be given.

**Comment by jeromekelleher** [comment]
It should be handled properly, or at least give a good error. (#43 was for this).
