### ISSUE TITLE
Change metadata tests for compatibility with msprime 1.0.0

### ISSUE THREAD

**Issue by awohns** [tskit-dev/tsinfer#468]
Lots of tests related to population metadata fail with the upcoming `msprime` version. I guess we should change these tests sometime before the release?
I'm happy to do it

**Comment by jeromekelleher** [comment]
That sounds good, thanks. I think we can put in a msprime>=1.0.0 in the requirements files and it'll sort itself out - can assume devs are on the alpha now.

**Comment by hyanwong** [comment]
I don't think any metadata tests are failing now, only #494 and #493 so this issue can probably be closed

**Comment by jeromekelleher** [comment]
OK, closing.
