### ISSUE TITLE
Add time_units attribute to AncestorData file

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#469]
At the moment we get all the metadata for the final tree sequence from the SampleData file. However, there is at least one piece of metadata which makes sense to associate with an AncestorData file, which is the meaning of time (as yet unimplemented, but see https://github.com/tskit-dev/tskit/issues/495 and https://github.com/tskit-dev/tskit/issues/1051). In other words, should the ancestors file "know" whether the time units are years, generation, freq measures, etc?

This came up because of https://github.com/tskit-dev/tsinfer/pull/467, where it can be useful to know if the ancestors that we are dealing with are using frequency as time, or something else. It might also be sensible to be able to check whether the AncestorData file is using the same meaning of time as its associated SampleData file, if we ever allow this to occur. when e.g. running `insert_proxy_samples(.., require_same_sample_data=False)`.

**Comment by hyanwong** [comment]
`time_units` is now a top-level attribute of a tree sequence. It seems sensible to add it as a top level attribute of an AncestorData file too, using the same enumerations as in `tskit`

**Comment by hyanwong** [comment]
Can we bung this into the [next milestone](https://github.com/tskit-dev/tsinfer/milestone/2)? It should be easy I think.

**Comment by hyanwong** [comment]
We want to set `time_units` to "uncalibrated" if we are using frequency-as-time. We will then need to pass the time_units field from AncestorData to the ancestors_tree sequence, and from the ancestors tree sequence through to the final tree sequence (rather than taking this from the SampleData file.

**Comment by hyanwong** [comment]
If we only want to make this a minor v version bump, presumably we return "unconstrained" if the attribute doesn't exist in the AncestorData instance. I wonder if this could be breaking in some way, though?

**Comment by jeromekelleher** [comment]
Returning ``uncalibrated`` by default seems OK?

**Comment by hyanwong** [comment]
Closing in favour of https://github.com/tskit-dev/tsinfer/issues/696
