### ISSUE TITLE
Check for finalised SampleData files in merge

### ISSUE THREAD

**Issue by awohns** [tskit-dev/tsinfer#472]
`merge` doesn't check that the sampledata files being merged are finalised. A silent error in creating a downstream SampleData file caused trouble after merging that file with others and trying to infer a tree sequence.
I can add a check that both SampleData files being merged are finalised in `merge`. 
Spoke to @hyanwong and he thinks it's a good idea. What do you think @jeromekelleher. It's a one line fix.

**Comment by jeromekelleher** [comment]
Yep, good idea.
