### ISSUE TITLE
Allocate larger blocks for ancestor builder

### ISSUE THREAD

**Issue by percyfal** [tskit-dev/tsinfer#489]
It may happen that the number of sites used to finalise ancestor building is so large that [tsk_blkalloc_init](https://github.com/tskit-dev/tsinfer/blob/main/lib/ancestor_builder.c#L145) allocates too little memory in [ancestor_builder_alloc](https://github.com/tskit-dev/tsinfer/blob/main/lib/ancestor_builder.c#L124). cf discussion #488 ; the bug manifested when some [370k sites](https://github.com/tskit-dev/tsinfer/discussions/488#discussioncomment-588565) were used to finalise ancestor building, which resulted in [focal_sites](https://github.com/tskit-dev/tsinfer/blob/main/lib/ancestor_builder.c#L534) being assigned a NULL value.

**Comment by hyanwong** [comment]
Increasing the amount of memory requested on that line works OK in #600

**Comment by hyanwong** [comment]
@srachita hit this issue when running tsinfer on some population data with 3 outgroups from another species: in this case a large number of sites show the classic species split with all the outgroup individuals sharing unique alleles. This is a reasonable thing to want to do, I would say. It's not clear to me that simply removing the outgroup(s) or the sites in question would be the right thing to do here: they are an inherent part of the analysis. So increasing the amount of memory requested by `tsk_blkalloc_init` does seem like a reasonable thing to do.

Is there any reason why not to allocate (say) 16MB here rather than 1MB, @jeromekelleher ? It wouldn't be a permanent fix, but would help in a few of these cases.

**Comment by jeromekelleher** [comment]
No reason at all @hyanwong - 1MB just seemed like a reasonable choice. I think we probably need to make things a bit more robust though and figure out what the maximum size might be in Python, and pass this value down to the C code. We don't want to start allocating (say) 1GB just in case there's some mad corner case somewhere.

That's probably why I didn't just fix it at the time I'd imagine.

**Comment by hyanwong** [comment]
It looks to me as if the only large blocks being allocated by `tsk_blkalloc_get` are:

```
focal_sites = tsk_blkalloc_get(
                &self->allocator, pattern_map->num_sites * sizeof(tsk_id_t));
```

and:

```
site->genotypes
            = tsk_blkalloc_get(&self->allocator, self->num_samples * sizeof(allele_t));
```

We know the maximum number of focal sites, which is simply the total number of sites, right? So can't we simply allocate enough memory for all of these, something like:

```
tsk_blkalloc_init(self->num_sites * sizeof(tsk_id_t) + self->num_samples  * sizeof(allele_t) + a_few_extra_bytes)
```

Or am I misunderstanding something?

**Comment by jeromekelleher** [comment]
Yes, good call. So the answer is something like

```c
max_size = 1024 * 1024;
max_size = TSK_MAX(self->num_sites * sizeof(tsk_id_t), max_size);
max_size = TSK_MAX(self->num_samples  * sizeof(allele_t), max_size);
```
This is the size maximum size of a single block that gets allocated, but there'll be lots and lots of little allocations. There's no point in allocating blocks (that we subsequently hand out in little chunks, on request) in less than 1MB.

**Comment by hyanwong** [comment]
Good call. How might we actually test this without hammering the test suite?

**Comment by hyanwong** [comment]
@percyfal : do you want to test the latest fix to check it works on the files you were having problems with?

```
python3 -m pip install git+https://github.com/tskit-dev/tsinfer
```

**Comment by percyfal** [comment]
@hyanwong I would, but we rephased our data and the problem magically disappeared :) I'll see if I can dig up the old dataset, if it's still around. In any case, I did solve the problem previously on the old dataset by increasing the allocation size, just as the current fix does, and recompiling. I'll let you know if I find the relevant test data.

**Comment by hyanwong** [comment]
> @hyanwong I would, but we rephased our data and the problem magically disappeared :) 

Ha. Even better.

> I'll see if I can dig up the old dataset, if it's still around. In any case, I did solve the problem previously on the old dataset by increasing the allocation size, just as the current fix does, and recompiling. I'll let you know if I find the relevant test data.

Thanks. Don't spend too much time on it, as I'm pretty sure it'll work, but if it's only a 10 min job, then another test would be reassuring.
