### ISSUE TITLE
add_sample() takes an inordinate amount of time for large datasets

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#49]
For the UK-BB, with 487409 * 2 samples, about 50% of the time converting bgen to a .samples file is spent calling `sample_data.add_sample({'name':samp_name})` a million times (the remaining 50% is in what I would expect to be the intensive bit: `add_sites()`). This is somewhat surprising. It might be useful to be able to add sample names / metadata in batches, if this would speed it up.

**Comment by jeromekelleher** [comment]
Closing this as it turns out it's not such a big issue.
