### ISSUE TITLE
Alleles not equal on tsinfer verify, v 0.2.0

### ISSUE THREAD

**Issue by stsmall** [tskit-dev/tsinfer#490]
Hi,
I am working with the tsinfer version 0.2.0. When running verify, I get an error about alleles not being equal. I checked that all my sites have only 2 alleles and that the ancestral allele matches either the REF or ALT. I also removed all singletons, not sure if this was advised or not. I used this script (https://github.com/stsmall/Kiribina_Folonzo/blob/debug/vcf2tsinfer.py) which was a modification of the one in the tutorial. tsinfer ran to completion without error.
thanks for the help!
@stsmall

> $ tsinfer list chrX.trees
path      = chrX.trees
size      = 519.0 MiB
edges     = 9215138
trees     = 910682
sites     = 2160904
mutations = 2124826

> $ tsinfer verify chrX.samples chrX.trees
2021-04-22 10:36:02,999 [47534] CRITICAL root: Traceback (most recent call last):
  File "tsinfer", line 8, in <module>
    sys.exit(main())
  File "tsinfer/__main__.py", line 5, in main
    cli.tsinfer_main()
  File "tsinfer/cli.py", line 499, in tsinfer_main
    args.runner(args)
  File "tsinfer/cli.py", line 238, in run_verify
    tsinfer.verify(samples, ts, progress_monitor=args.progress)
  File "tsinfer/inference.py", line 181, in verify
    raise ValueError(f"alleles not equal: {var1.alleles} != {var2.alleles}")
ValueError: alleles not equal: ('C', 'T') != ('C',)

**Comment by hyanwong** [comment]
Ah, it looks like these are monomorphic sites, right? Perhaps we forgot to test how those are handled in `verify()`. I suspect you can ignore this until we fix it, though.

**Comment by stsmall** [comment]
ugh, yep. Monomorphic sites. I am sorry that I missed that.

**Comment by hyanwong** [comment]
No problem, we should handle this anyway.

**Comment by hyanwong** [comment]
The new msprime mutation model is also not guaranteed to give the non-ancestral alleles in the same order as input. I'm working on a fix.

**Comment by hyanwong** [comment]
@stsmall - if you have a moment could you check that the latest GitHub version of tsinfer now works with your files with the monomorphic sites?
