### ISSUE TITLE
Crash when (I think) there is not disk space - needs clearer error message

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#50]
I think someone is using up disk space on the cluster, so in python, when I run

`sample_data =  tsinfer.SampleData(path="chr20.samples".format(chr))`

tsinfer fails with

`lib/mdb.c:5614: Assertion 'root > 1' failed in mdb_page_search()`

It's not a very clear error message, if the problem *is* one of space.

**Comment by jeromekelleher** [comment]
There's nothing we can do about this I'm afraid --- looks like a problem with lmdb. 

To be clear, this is aborting out from C rather than raising an error back to Python, right? If so this is disappointing.

**Comment by hyanwong** [comment]
Yes, I think so. This is running within a Python interactive session, and I do

```
>>> sample_data =  tsinfer.SampleData(path="chr{}.samples".format(chr))

lib/mdb.c:5614: Assertion 'root > 1' failed in mdb_page_search()
Aborted
-bash-4.2$
```

which aborts the python session and drops me back into the shell. I assume if it raised an error back to Python it would drop me back into the Python interpreter.

**Comment by jeromekelleher** [comment]
Yes, this is aborting. Very disappointing from LMDB.

Well, theres zip we can do about it right now, so I'm going to close this issue. Good to know about it though, thanks for reporting.

**Comment by hyanwong** [comment]
Perhaps report up to LMDB? I assume we can't catch this within Python by wrapping it in a try: except block.

**Comment by jeromekelleher** [comment]
> Perhaps report up to LMDB? I assume we can't catch this within Python by wrapping it in a try: except block.

I've had a quick look and it's not at all obvious how to report or search for bugs in the upstream lmdb library.

If we could wrap it in a try except block we wouldn't have a problem --- aborts kill the interpreter, so there's no chance for Python code to recover.
