### ISSUE TITLE
More descriptive error reporting when creating sample data file?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#546]
Off the back of https://github.com/tskit-dev/tsinfer/discussions/545#discussioncomment-896269 it might be helpful to actually output (or save) the data that we attempt to stick into zarr, if the attempt fails. Perhaps we could wrap https://github.com/tskit-dev/tsinfer/blob/c1f3295678411aa395422e0c3852a1f4e0b85205/tsinfer/formats.py#L181 in a try/except block, and then dump the "buffered" array somewhere? Presumably it might be too big to print out though?

However, this may not be worth doing, if we are moving to inputting via sgkit in the future - I don't know what the timescale is on that though.

**Comment by jeromekelleher** [comment]
I don't think it's worth the effort to be honest, it'd be a lot of work. In the linked discussion it's a metadata issue, which I agree we could give a more descriptive error on, but that's probably an upstream tskit thing (we could say "error encoding metadata key 'x', data 'y' is not JSON serialisable" or whatever)

**Comment by hyanwong** [comment]
> that's probably an upstream tskit thing (we could say "error encoding metadata key 'x', data 'y' is not JSON serialisable" or whatever)

Yes, that seems sensible.

**Comment by benjeffery** [comment]
https://github.com/tskit-dev/tskit/issues/1505
