### ISSUE TITLE
Error when executing tutorial

### ISSUE THREAD

**Issue by floklimm** [tskit-dev/tsinfer#549]
Hello,
When executing the tutorial, specifically the "Data Example", I receive the following error

`---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-16-5a25b4c4d6e4> in <module>
      6     path="P_dom_chr24_phased.samples", sequence_length=chromosome_length(vcf)
      7 ) as samples:
----> 8     add_diploid_sites(vcf, samples)

<ipython-input-15-51f5d781c9bc> in add_diploid_sites(vcf, samples)
      5     """
      6     pos = 0
----> 7     for variant in vcf:  # Loop over variants, each assumed at a unique site
      8         print(variant)
      9         if pos == variant.POS:

/opt/anaconda3/envs/lineageClustering/lib/python3.7/site-packages/cyvcf2/cyvcf2.pyx in cyvcf2.cyvcf2.VCF.__next__()

Exception: error parsing variant with `htslib::bcf_read` error-code: 0
`

I printed the variants and it occurs after the following variant
`chr24	7067266	.	T	*	.	PASS	AC=1;AN=20;AA=T	GT	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	0|0	1|0`

I assume that it is some kind of problem with the file ending but wanted to raise this issue here since googling didn't lead me anywhere. It might also be a problem with cyvcf2, instead of tsinfer.

I am using MacOS with Python in version '3.7.10 (default, Feb 26 2021, 10:16:00) \n[Clang 10.0.0 ]'.

**Comment by hyanwong** [comment]
Thanks for the report. This sounds like an `htslib` error: I guess reading it with htslib outside of tsinfer fails too?

**Comment by floklimm** [comment]
I have to admit that I wouldn't know how to test this. I have never used `htslib` before.

**Comment by hyanwong** [comment]
I've just tested this on my Mac (python 3.9 though, in a jupyter notebook) and it works fine. It looks like you installed cyvcf via conda - so I guess you could try uninstalling and installing via pip? Or perhaps it's an internet problem? Can you clear any cyvcf2 caches and try again?

**Comment by floklimm** [comment]
Removing cyvcf2 and reinstalling via pip solved the problem.

Thank you for your help!

**Comment by hyanwong** [comment]
> Removing cyvcf2 and reinstalling via pip solved the problem.

Great, do you want to close the issue?

> Thank you for your help!

No problem
