### ISSUE TITLE
MemoryError in tsinfer.infer()

### ISSUE THREAD

**Issue by srachita** [tskit-dev/tsinfer#600]
I am trying to infer tree sequence from the sample data file for each chromosome separately for a plant species using tsinfer.infer()  for 286 individuals. This works fine for the shortest chromosome but fails for all the other chromosomes with 'MemoryError' at 'tsinfer/inference.py", line 949, in run
    self.descriptors = self.ancestor_builder.ancestor_descriptors()'
I doubt it is the RAM causing this issue because until this step the maximum RAM it consumes is less than a GB and I run it on an HPC with more than 700 GB RAM unshared with others. I observe that the number of threads evoked is more than 150. I already tried setting the num_threads to 0. Is the number of threads evoked causing this issue? Also, how can I better control the number of threads evoked within the tool?

**Comment by srachita** [comment]
PS. The size of my sample data file for each chromosome is less than 50MB

**Comment by jeromekelleher** [comment]
Hmm, that *is* weird @srachita! Would it be possible to make one of your sample data files available on the internet somewhere so we could try this out?

**Comment by srachita** [comment]
One chromosome's sample data file is uploaded on google drive and is shared with @jeromekelleher and potentially with the tsinfer team. The link is as follows:  https://drive.google.com/drive/folders/1mIZUobNneWzVVC8uS3TJ62MAjTp18hYz?usp=sharing

**Comment by hyanwong** [comment]
Hi @srachita : I can have a look, if you give me access to the file: I'll ask for permission to access via the google drive interface.

**Comment by rachitasrivastava** [comment]
Shared the file.

**Comment by srachita** [comment]
Shared the file with @hyanwong

**Comment by srachita** [comment]
Hi. I just wanted to know if there is any update on this issue?

**Comment by hyanwong** [comment]
I'll get onto this today, apologies for the delay, and thanks for reminding me!

**Comment by hyanwong** [comment]
FWIW, I can confirm that I get this error too:

```
>>> import tsinfer
>>> sd = tsinfer.load("chr3_data.samples")
>>> anc = tsinfer.generate_ancestors(sd, progress_monitor=True)
ga-add   (1/2)100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 1.68M/1.68M [00:49, 34.2kit/s]
Traceback (most recent call last):███████████████████████████████████████████████████████████████████████████████████▉| 1.68M/1.68M [00:48, 34.8kit/s]
  File "<stdin>", line 1, in <module>
  File "/Users/yan/Documents/Research/BDI/tsinfer/tsinfer/inference.py", line 376, in generate_ancestors
    generator.run()
  File "/Users/yan/Documents/Research/BDI/tsinfer/tsinfer/inference.py", line 945, in run
    self.descriptors = self.ancestor_builder.ancestor_descriptors()
MemoryError

```

**Comment by hyanwong** [comment]
Just to note @jeromekelleher that there are a lot of sites in this file: 

```
INFO:tsinfer.inference:Starting addition of 1678318 sites
INFO:tsinfer.inference:Finished adding sites
DEBUG:tsinfer.formats:Syncronously flushing buffer
DEBUG:tsinfer.formats:Flushing buffer 0: start=0 n=0
DEBUG:tsinfer.formats:Buffer 0 flush done
DEBUG:tsinfer.formats:Fixing up LMDB file size
```

-> Memory error

**Comment by hyanwong** [comment]
Building via the python engine seems to work. At least, it gets past the `self.ancestor_builder.ancestor_descriptors()` phase, but I've killed it after only getting through 2.87k/395k ancestors in 8 hours. Python memory use peaked at 3GB. So I think it's something to do with the C engine not allocating enough memory for such a large number of sites (therefore ancestors) in the `.ancestor_descriptors()` function.

**Comment by hyanwong** [comment]
It's failing here:

**Comment by jeromekelleher** [comment]
Ah, thanks very much @hyanwong, great digging! This is #489 again. I'm not sure when we're going to get a release out to fix this, unfortunately.

It seems like this could be a symptom of something weird in the data though? This does sound like a *lot* of focal sites for a single ancestor!

**Comment by srachita** [comment]
@hyanwong Thank you for spending time on this issue. I would like to mention the scenario we were trying to test. We purposely mapped the reads from the closest related species (which is our outgroup) and called the variants. The variants from the outgroup were a part of the sample data file provided to you. We were trying to estimate the abundance of topologies where the outgroup was grouping with one of the sub-populations of the species under study. The file was not polarized as the 'ancestral states' were a part of the variant file. We suspect this would cause an excess of variant sites('derived states'). 
P.S. The divergence between the reference and outgroup is 0.025.

**Comment by hyanwong** [comment]
Hi @srachita: it might be that these focal sites are the ones where the distribution separates the outgroup from all the other species, which would explain why there are so many. Here's how to find the distributions with lots of identical sites:

```
>>> import collections
>>> count = collections.Counter()
>>> for v in sd.variants():
>>>   count[tuple(v.genotypes)] += 1
>>>
>>> count.most_common(10)
```

which shows that the top 2 allele distributions account for 40% of the sites (359054 and 287866 sites). Part of the reason is that the most common distribution is all zeros, but those monomorphic sites are ignored by the algorithm. Here's the info about the 287866 sites with the 2nd most common distribution:

```
import numpy as np
most_common = count.most_common(2)
for individual_id in np.unique(sd.samples_individual[:][np.array(most_common[1][0], dtype=bool)]):
    print(sd.individual(individual_id))
```

giving:

```
Individual(id=251, flags=0, location=[], metadata={'name': "['PR03948']"}, samples=[502, 503], population=0, time=0.0)
Individual(id=283, flags=0, location=[], metadata={'name': "['PR05649']"}, samples=[566, 567], population=0, time=0.0)
Individual(id=285, flags=0, location=[], metadata={'name': "['PR00212']"}, samples=[570, 571], population=0, time=0.0)
```

Are these the 2 outgroup samples?

**Comment by srachita** [comment]
Yes. These indeed are the outgroup samples.

**Comment by hyanwong** [comment]
Ah - that explains it. @jeromekelleher  - could a temporary hack be to simply increase the size passed to in `tsk_blkalloc_init ` in https://github.com/tskit-dev/tsinfer/blob/b3f37392b36d19d98b940f645f9eb4a6c7d2fddf/lib/ancestor_builder.c#L145, and recompile. I'm not familiar with how this part of the codebase works.

**Comment by hyanwong** [comment]
Confirming, I increased that to `1024 * 1024 * 10`, recompiled, and it seems to work (so far). Do you want to try, @srachita ?

**Comment by srachita** [comment]
Thank you for this. If this also allows keeping sites specific to the outgroup during the inference of tree, then I would give this a try.

**Comment by hyanwong** [comment]
Let me know here how it goes.

**Comment by jeromekelleher** [comment]
Yep, that's a perfectly good workaround @hyanwong - probably quite similar to what we'll end up doing.

**Comment by srachita** [comment]
Linux

**Comment by hyanwong** [comment]
Great, it should be very easy to compile then. `git clone --recurse-submodules https://github.com/tskit-dev/tsinfer` then run `make` in the cloned tsinfer directory, then `python3 -m pip install -e .` should do it. It might be worth uninstalling the old one first (`python3 -m pip uninstall tsinfer`).

**Comment by srachita** [comment]
Perfect! Thank you.

**Comment by srachita** [comment]
The trick works completely fine for me

**Comment by hyanwong** [comment]
We've just pushed a fix to the main repo, so you can also do

```
python3 -m pip install git+https://github.com/tskit-dev/tsinfer
```
