### ISSUE TITLE
insert_proxy_samples should optionally return a mapping 

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#605]
As part of https://github.com/tskit-dev/tsinfer/issues/604, when calling `ancestors.insert_proxy_samples()` it would be useful to be able to return a dictionary mapping the ancestor ID to the ID in the sample data file. I propose that, like `simplify`, we have a parameter "map_ancestors" to that function, which if True, means that the function returns a tuple of `new_ancestors, ancestor_map`. In this case, `ancestor_map` could be a dictionary of `{sample_data_id: ancestor_id}`

**Comment by jeromekelleher** [comment]
SGTM

**Comment by hyanwong** [comment]
After discussion, the best way forward actually seems to be to add an extra column to the AncestorsData file format saying which sample an ancestor represents (or `tskit.NULL` for ancestors that do not correspond to a specific sample.

**Comment by jeromekelleher** [comment]
Shall we close this then?

**Comment by hyanwong** [comment]
Could do - I'll work up a PR separately
