### ISSUE TITLE
Is the parameter "simplify" correctly named?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#622]
It seems a little confusing, to those who don't know the details of `simplify`, that e.g. tsdate requires a "simplified" ts (i.e. [without unary nodes](https://github.com/tskit-dev/tsdate/pull/188)), but that specifying `tsinfer.infer(sample_data, simplify=True)` does *not* produce the right sort of tree sequence and a further round of simplification is needed to remove the unary nodes.

Therefore, I wonder if it is worth changing the parameter name to something else. Here's one suggestion: we could reverse the meaning, and have `keep_all_nodes`, with `None` doing the current behaviour, `False` doing a full simplify (i.e. removing unary nodes), and True omitting all simplification. I'm not sure if this is a bit too opaque, though, and if so, whether a better parameter name would fix it? Other suggesting welcome.

**Comment by jeromekelleher** [comment]
That sounds like a pretty aggressively breaking change to me @hyanwong - wouldn't this completely break existing code?

If we change this we need to make sure that the default behaviour remains the same (I think we're happy that this is the output we want people to do their evaluations against?), and that we don't break existing code.

Without thinking too hard about it, it seems like a lot of work for not a whole pile of gain?

**Comment by hyanwong** [comment]
I think we would retain (but deprecate) the `simplify` parameter? And yes, keep the default the same. Perhaps this isn't needed so much if tsdate errors out on tree sequences with unary nodes, but I do think it might be a rather confusingly named parameter? Happy to leave it though.
