### ISSUE TITLE
add_samples crashes in some loops with BadRslotError

### ISSUE THREAD

**Issue by awohns** [tskit-dev/tsinfer#64]
add_sample, when used in a loop that reads records from a VCF, causes the following error:

> BadRslotError: mdb_txn_begin: MDB_BAD_RSLOT: Invalid reuse of reader locktable slot

Simplest bit of code I could get to reproduce this error:
```
import tsinfer
import vcf

vcf_reader = vcf.Reader(filename='1000genomes_phase3_vcf/1000_genomes/ALL.chr20_GRCh38.genotypes.20170504.vcf.gz')

sample_data = tsinfer.SampleData(path="chr20.grch38.ensembl_aa.samples")
i = 0
for record in vcf_reader.fetch('20', 0):
    sample_data.add_site(position=record.POS, genotypes=[0,0,0,1], alleles=["G", "C"])
```

Adding samples in this loop is fine: 
```
sample_data = tsinfer.SampleData(path="chr20.grch38.ensembl_aa.samples")
i = 0
while i < 10:
    i = i + 1
    sample_data.add_site(position=i, genotypes=[0,0,0,1], alleles=["G", "C"])
```

**Comment by awohns** [comment]
I think this is simply because some of the records in the VCF have the same position number

**Comment by jeromekelleher** [comment]
Also can you paste in the full stack trace please?

**Comment by jeromekelleher** [comment]
OK, I've reproduced this. The issue happened when the same file is opened several times but not properly closed. The fix was to delete the lock file if it exists before opening.

Using a context manager is a good idea here @awohns:
```
with tsinfer.SampleData(path="chr20.grch38.ensembl_aa.samples") as sample_data:
     for record in vcf_reader.fetch('20', 0):
         sample_data.add_site(position=record.POS, genotypes=[0,0,0,1], alleles=["G", "C"])
```
Then you can't forget to close the file, even if an error happens.

**Comment by hyanwong** [comment]
Currently you have to call finalise() to add provenance information, so can’t use a context manager in that case.

**Comment by jeromekelleher** [comment]
The provenance API there is preliminary and will probably change. Should probably have an explicity ``add_provenance`` call rather than munging it in with finalise.
