### ISSUE TITLE
Remove ultimate ancestor using subset

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#649]
Since we never actually need the ultimate ancestor once we have run match_ancestors, can we simply remove it from the ancestors tree sequence using `tables.subset()`? It's a bit odd leaving it in. Is it necessary for matching samples against the ancestors TS? I think not.

**Comment by jeromekelleher** [comment]
I think we could probably just not add it in the first place, but likely this will break some tests.

**Comment by gtsambos** [comment]
If this global CA is actually informative -- which maybe it could be, idk, if you trusted its tsdated age, and it's an MRCA? -- then it could even be useful to keep. But it's unlikely that this is what it actually represents though, right? You have no information about mutations that have arisen before each local MRCA, so I imagine you wouldn't be doing a good job of dating this ultimate ancestor.

**Comment by hyanwong** [comment]
I think I agree with you @jeromekelleher that neither are things that we want in the final tree sequence, even though we do normally want to keep unary nodes. We would need to check that tsdate is happy with this (which I think it should be).

As a halfway house, we could remove these nodes from the final output tree sequence by post processing? Then at some future point we could remove them from within the algorithm itself, should that be necessary?

**Comment by jeromekelleher** [comment]
> As a halfway house, we could remove these nodes from the final output tree sequence by post processing? Then at some future point we could remove them from within the algorithm itself, should that be necessary?

I think we could get rid of one of them all right. I think it would be good if we could say that node 0 is the ultimate ancestor consisting of all zeros, in the standard pipeline, as this is what we assume in any case.

**Comment by hyanwong** [comment]
> I think we could get rid of one of them all right. I think it would be good if we could say that node 0 is the ultimate ancestor consisting of all zeros, in the standard pipeline, as this is what we assume in any case.

What if node 0 is not coalescent in a tree though. Do we remove the edge(s) from the oldest MRCA to node 0, so that the haplotype given by 0 in the tree sequence might not span the whole sequence? I.e. in Georgia's picture below

![Screen Shot 2022-05-31 at 4 07 14 pm](https://user-images.githubusercontent.com/4699014/171189430-6d3c0503-c844-4e75-943c-e0aa0f4ca472.png)

Do we delete 12 (which I assume is the all-zero CA) from the left hand tree? And how about node 11 in the left hand tree?

**Comment by hyanwong** [comment]
Node 13 is easy to delete, but I do think that we want to be careful with node 12 too. I worry that we can't really claim that all the trees will trace back to the same all-zeros ancestor at some point in the past. If we are dating this tree sequence, we shouldn't assume there is a single all-zeros ancestor at a fixed point in time. I assumed this is what you meant when you called both the ultimate and the all-zeros ancestors as "artifactual" above.

Of course, at the moment, we simplify before dating, so this isn't really an issue, but I do think it is potentially misleading as to the true pattern of ancestry to have a single all-zeros ancestor at a fixed point in time.

**Comment by jeromekelleher** [comment]
Fair enough - that's quite a bit trickier then.

**Comment by hyanwong** [comment]
Here's some code that removes the ultimate ancestor:

```
def remove_ultimate(ts):
    # Assumes this is a tree sequence from tsinfer
    _, u_indices, u_counts = np.unique(ts.tables.nodes.time, return_index=True, return_counts=True)
    # oldest node should be the ultimate ancestor
    assert u_counts[-1] == 1
    ultimate_ancestor = u_indices[-1]
    assert u_counts[-2] == 1  # CA of zeros
    zeros_ancestor = u_indices[-2]

    assert not np.isin(ultimate_ancestor, ts.tables.mutations.node)  # no mutations above the ultimate ancestor
    ultimate_edge = ts.tables.edges[ts.num_edges-1]
    assert ultimate_edge.parent == ultimate_ancestor and ultimate_edge.child == zeros_ancestor and ultimate_edge.left==0.0 and ultimate_edge.right== ts.sequence_length
    keep = np.concatenate((np.arange(ultimate_ancestor), np.arange(ultimate_ancestor+1, ts.num_nodes)))
    ts = ts.subset(keep, reorder_populations=False, remove_unreferenced=False)
    # could deal with the zeros_ancestor here
    
    return ts
```

**Comment by hyanwong** [comment]
> Fair enough - that's quite a bit trickier then.

Yep - that's why I think it's probably worth opening another issue: https://github.com/tskit-dev/tsinfer/issues/672

**Comment by jeromekelleher** [comment]
Decision: let's do this at the start instead of the end.
