### ISSUE TITLE
Point release to fix packaging for Zarr

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsinfer#658]
Now that 2.11.3 is out and we have fixed up our code in #657, probably a good idea to pop out a quick point release?

I don't think much has happend since last release (haven't checked though!) so should be straightforward.

Can you have a look please @benjeffery?

**Comment by hyanwong** [comment]
Could we decide on #642 before the point release? See Ben's recent comment there.

**Comment by hyanwong** [comment]
> Could we decide on #642 before the point release? See Ben's recent comment there.

I'm happy to go with whatever struct definition @benjeffery suggests, if @jeromekelleher is away today.

**Comment by benjeffery** [comment]
As the zarr bug was pretty bad, I'll put out a point release. We can do another one in quick succession after #642 is decided, but I don't want to rush #642.

**Comment by hyanwong** [comment]
Fair enough. SGTM.

**Comment by jeromekelleher** [comment]
Yes, let's just pop out a quick point release, as the zarr stuff is breaking.

**Comment by benjeffery** [comment]
https://github.com/tskit-dev/tsinfer/releases/tag/0.2.3
