### ISSUE TITLE
Migrate docs to tskit.dev

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsinfer#678]
We're still building the docs on rtd, and we should migrate them over to the standard tskit-dev setup.

Is there much involved in this @benjeffery?

**Comment by benjeffery** [comment]
It's a matter of adding the tsinfer docs build to https://github.com/tskit-dev/tskit-site/blob/main/.github/workflows/build-deploy.yml and then adding a `curl` line to the tsinfer docs action.

**Comment by jeromekelleher** [comment]
Also some conversion of the tsinfer Actions to include a docs build?

**Comment by benjeffery** [comment]
I've self-assigned this, but won't get to it till after tskit 0.5.0 and a first draft of the site is done.

**Comment by jeromekelleher** [comment]
Thanks - no hurry

**Comment by benjeffery** [comment]
Live now at:
https://tskit.dev/tsinfer/docs/latest/
and
https://tskit.dev/tsinfer/docs/stable/
