### ISSUE TITLE
Add an "ancestral_state_index" parameter to SampleData.add_sites()?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#686]
At the moment we require people to order their allele lists such that the first allele is the ancestral state. This can be a little fiddly, and often the ancestral state isn't known anyway, so it would be good to have a way for users to indicate this, while keeping the site in the final TS. Currently the way to incorporate a site with an unknown ancestral state is to pick one at random as the first one to put, and include the site in the `exclude_positions` parameter of `generate_ancestors()`, which seems pretty obscure to me.

I suggest that a non-breaking change that could allow this would be to have an extra parameter "ancestral_state_index", which defaults to 0, meaning that the zeroth allele in the `alleles` parameter is treated as the ancestral state. This would be similar to the sort of format we expect to see when we switch to using sgkit as the input format. We could allow `tskit.NULL` to be passed to mean that we don't know the ancestral state, and it should be placed using parsimony.

This seems pretty intuitive to me, but there are some decisions to be made here. When we add a site with (say) `ancestral_state_index=1`, do we record the genotypes and allele list before sticking them into the sample data file (which seems a bit hacky, and is not likely to be portable to sgkit). Or do we switch the genotypes when we build the ancestors, in which case we will need to swap the genotypes when we match against the ancestors using `match_samples` or `match_ancestors`. If the latter, I suspect that it might be helpful for sanity checking purposes to store the meaning of the genotype values (i.e. the reordered alleles list) in the AncestorData instance.

**Comment by jeromekelleher** [comment]
Nice idea, I like it. I think we should separate out the idea of saving people from fiddling with the allele ordering from specifying whether the ancestral state is known or not though.

Or, we could make it simpler yet, by giving the actual allele value of the ancestral state, so that people don't have to figure out what index its at at all?

Ultimately we're probably going to want to have an ``ancestral_state_confidence`` or something, and we do something slightly different for low, medium and high-confidence ancestral state calls (which is why I don't think we should mush the functionality into this proposal).

**Comment by hyanwong** [comment]
> Or, we could make it simpler yet, by giving the actual allele value of the ancestral state, so that people don't have to figure out what index its at at all?

Yes, that works. `None` (default) would mean take the first in the allele list. But although I agree with your general point about separating out functionality, I do think we should consider allowing `tskit.NULL` here, as it's weird to *have* to specify an ancestral state if we really don't know it at all.

> Ultimately we're probably going to want to have an `ancestral_state_confidence` or something, and we do something slightly different for low, medium and high-confidence ancestral state calls (which is why I don't think we should mush the functionality into this proposal).

I agree with that too, and it's worth bearing this in mind. I think that would probably be added to both the SampleData and the AncestorsData formats.

**Comment by jeromekelleher** [comment]
>  I do think we should consider allowing tskit.NULL here, as it's weird to have to specify an ancestral state if we really don't know it at all.

We can't use tskit.NULL as that's -1, which people could quite reasonably use to mean the last element of the array.

> I agree with that too, and it's worth bearing this in mind. I think that would probably be added to both the SampleData and the AncestorsData formats.

I think we'd end up having to change these anyway to do what you're talking about, so lets do the simple thing first.

**Comment by hyanwong** [comment]
> > I do think we should consider allowing tskit.NULL here, as it's weird to have to specify an ancestral state if we really don't know it at all.
> 
> We can't use tskit.NULL as that's -1, which people could quite reasonably use to mean the last element of the array.

Hmm, I just thought: tskit.NULL would be fine if we expected a value ("A", "T", "G", "C"), rather than an index, right?

**Comment by hyanwong** [comment]
I think in tsinfer we require the derived state to be `1`, right? So I suggest that we store both a column of ancestral states and a column of derived states in the sample data file, and we can pass in both an ancestral state and a derived state to `add_site` (which default to 0 and 1 respectively). That way, as long as the other alleles are left in an unchanged order, we can output the same variant encoding as we passed in:

```python
sd.add_site(position=0, genotypes=[2, 3, 2], alleles=["A", "T", "G", "C"], ancestral_state="C", derived_state="G")
sd.sites_genotypes[0] == [1, 0, 1]  # suitable for inference: 0 is the ancestral state
sd.sites_alleles[0] == ("C", "G", "A", "T")  # "A" and "T" are in the same order as passed in
sd.sites_original_ancestral_allele_index[0] == 3
sd.sites_original_derived_allele_index[0] == 2
```

Then we can make sure that the `variants()` operator by default returns the same order as passed in, even though under the hood it is storing a different array:

```python
def variant(self, site_id):
    # return what we passed in. We could also add a param to return the "internal" encoding, or another passed in allele list
    genotypes = sd.sites_genotypes[site_id]
    alleles = sd.sites_alleles[site_id]
    allele_index = [
        sd.sites_original_ancestral_allele_index[site_id],
        sd.sites_original_derived_allele_index[site_id],
    ]
    allele_map = np.array(allele_index +[i for i in range(len(alleles) if i not in allele_index])
    # allele_map = [3, 2, 0, 1]
    reverse_map = {v: k for k, v in enumerate(allele_map)}
    genotypes = allele_map[genotypes]
    alleles = tuple(alleles[reverse_map[i]] for i in range(len(alleles)))
    return(self.site(site_id), alleles, genotypes)
```

**Comment by jeromekelleher** [comment]
I don't see why we need the ``derived_state`` - the matching engine can handle arbitrary alleles, and the ancestor generation only works for biallelic sites?

I don't think we need to preserve the input variant encoding - there will be plenty of cases where the ancestral state is the ALT allele, e.g.

**Comment by hyanwong** [comment]
Does the matching engine work with sites arrays like `[0, 3, 3, 3, 0, 0]` then? I thought it required biallelic sites to encode the derived state as a `1`?

**Comment by hyanwong** [comment]
> I don't think we need to preserve the input variant encoding

Not preserving the original encoding was causing complete havoc when Shing was trying e.g. to merge sample data files, mess with tree sequences vs SD files, etc. I thought this might cause a lot less pain for end-users.

**Comment by jeromekelleher** [comment]
> Does the matching engine work with sites arrays like [0, 3, 3, 3, 0, 0] then? I thought it required biallelic sites to encode the derived state as a 1?

I think that's fine, it just treats them as numbers to match. There might be some weirdness with how it decides what the number of alleles is though, come to think of it.

**Comment by hyanwong** [comment]
> > Does the matching engine work with sites arrays like [0, 3, 3, 3, 0, 0] then? I thought it required biallelic sites to encode the derived state as a 1?
> 
> I think that's fine, it just treats them as numbers to match. There might be some weirdness with how it decides what the number of alleles is though, come to think of it.

I think the ancestors generator assumes 0/1 though?

**Comment by jeromekelleher** [comment]
> I think the ancestors generator assumes 0/1 though?

I don't know.

**Comment by jeromekelleher** [comment]
Can we recode inline? I.e., could we update the variants and haplotypes iterators to recode the genotypes to map the alleles to ancestral state etc?

**Comment by hyanwong** [comment]
> Storing a `derived_state` is a retrograde step though - this will differ between files and cause more problems. What do you store when there's more than 2 alleles? What do you do when you merge two files and now there's more than two alleles at a site?

Yes, this is a bad notation on my part. I mean "the allele that is treated as derived for matching purposes". But maybe we only allow 2 alleles to be input for inference sites?

**Comment by hyanwong** [comment]
> Can we recode inline? I.e., could we update the variants and haplotypes iterators to recode the genotypes to map the alleles to ancestral state etc?

Variants is easy. Haplotypes: if we have an array of ancestral_states, the same as the length of sites, then this is just a long mapping array, right? So a single numpy lookup.

**Comment by jeromekelleher** [comment]
> Yes, this is a bad notation on my part. I mean "the allele that is treated as derived for matching purposes". But maybe we only allow 2 alleles to be input for inference sites?

We'll be supporting arbitrary alleles for matching pretty soon.

**Comment by hyanwong** [comment]
> Can we recode inline? I.e., could we update the variants and haplotypes iterators to recode the genotypes to map the alleles to ancestral state etc?

This would make it a lot easier if/when moving to SGkit. So probably worth thinking about.

**Comment by jeromekelleher** [comment]
If there's only two alleles, then deciding which one is "1" is simple if we've already decided which one is "0". If there's more than two alleles, then a "derived state" isn't meaningful.

Let's try out the dynamic remapping thing, see if we can make it work. As you say, we'll want to do this anyway when we're working with large sgzarr files where 0 will mean REF and not ancestral state.

**Comment by hyanwong** [comment]
> We'll be supporting arbitrary alleles for matching pretty soon.

But in `tsinfer` we will still only ever be able to use sites that return `0`, `1`, or `-1` I think. Although the constraint is entirely in the ancestors generation step, not in the matching.

**Comment by jeromekelleher** [comment]
We want to be more flexible that than. Suppose you add in observed ancestral haplotypes that have more than two alleles. We will want to match against them. The matching engine can already do this (see #675 )

**Comment by hyanwong** [comment]
> We want to be more flexible that than. Suppose you add in observed ancestral haplotypes that have more than two alleles. We will want to match against them. The matching engine can already do this (see #675 )

Yes, that's a good point.

**Comment by hyanwong** [comment]
So do we (potentially) want the ancestor builder to generate ancestors that are not just 0/1 arrays but could be e.g. 0/2 or 0/3? I think that would involve changing the builder logic a little. More precisely, if we do this:

```
sd.add_site(
    position=0,
    genotypes=[2, 3, 2],  # array has only 2 values, but they aren't 0 and 1
    alleles=["A", "T", "G", "C"],
    ancestral_state="C")
# sd.sites_genotypes[0]  == [2, 3, 2]
# sd.sites_alleles[0]  == ("A", "T", "G", "C")

```

Do we want to get out 0/1 genotypes with something like

```python
sd.variant(0, use_inference_encoding)  # returns pos, genotypes=[1, 0, 1], alleles=("C", "G")
```

Or are we happy retiring 0/3 genotypes in this case:

```python
sd.variant(0, use_inference_encoding)  # returns pos, genotypes=[3, 0, 3], alleles=("C", "A", "T", "G")
```

If we want 0/1 genotypes, for efficiency reasons we'll probably need to store the mapping of "G" -> allele_index 1, " somewhere, e.g. `sd.sites_derived_alleles_order`

**Comment by jeromekelleher** [comment]
> So do we (potentially) want the ancestor builder to generate ancestors that are not just 0/1 arrays but could be e.g. 0/2 or 0/3?

Perhaps - I don't know without getting into it.

**Comment by hyanwong** [comment]
Actually, an easy halfway house here is to only allow sites for inference that have exactly 2 alleles defined (hence the derived state will always be 1 anyway). I think we might have this restriction at the moment anyway. We can then revisit later the problem of sites with >2 alleles but in which only 2 states are used in the `genotypes` array.
