### ISSUE TITLE
Document numpy array accessors in the sample data files?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#688]
@szhan didn't know about e.g.

```
sample_data.sites_position[:]
```

Which turns out to be really helpful for his use case. Should we document these array accessors, or are we deliberately hiding them while waiting for SGkit to mature?

**Comment by jeromekelleher** [comment]
It's not so much about waiting for sgkit to mature as finding the 2 or 3 months of development time it'll take to change our data input side. We basically need to start again and rethink a whole bunch of things, but there's several papers that need to be written first.

**Comment by jeromekelleher** [comment]
Sure, if you like, won't do any harm.

**Comment by szhan** [comment]
Yes! I'll get to it.

**Comment by hyanwong** [comment]
Don't prioritise it, but if it helps you to learn this stuff, then fine.

Note that all of the array functions, e.g. the `sd.sites_position` accessor (which are thin layers to the underlying Zarr arrays) needs to be called like  `sd.sites_position[:]` to get the whole array out as a numpy vector.

**Comment by hyanwong** [comment]
Duplicate of #699
