### ISSUE TITLE
Replace `permissive_json_schema` with `tskit.MetadataSchema.permissive_json()`

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#694]
If I assign metadata to individuals using `tskit.MetadataSchema.permissive_json()`, tsinfer dies when trying to extend the schema using [`add_to_schema`](https://github.com/tskit-dev/tsinfer/blob/b87fbea7ff423e6480574f829858a4d84e96aa9e/tsinfer/inference.py#L74)

```
import msprime
import tskit
import tsinfer

nm = ["a", "b", "c", "d", "e"]
ts = msprime.sim_ancestry(len(nm), ploidy=1, sequence_length=100, random_seed=1)
ts = msprime.sim_mutations(ts, rate=0.1, random_seed=1)
tables = ts.dump_tables()
tables.individuals.metadata_schema = tskit.MetadataSchema.permissive_json()
for i, n in enumerate(nm):
   tables.individuals[i] = tables.individuals[i].replace(metadata={"name": n})
sd = tsinfer.SampleData.from_tree_sequence(tables.tree_sequence())
tsinfer.infer(sd)
```

```
---> 76     if name in schema["properties"]:
     77         raise ValueError(f"The metadata {name} is reserved for use by tsinfer")
     78     if definition is None:

KeyError: 'properties'
```

**Comment by hyanwong** [comment]
The reason is that this is how a permissive schema is defined in tsinfer, and it doesn't match the tskit version:

https://github.com/tskit-dev/tsinfer/blob/b87fbea7ff423e6480574f829858a4d84e96aa9e/tsinfer/formats.py#L66

**Comment by benjeffery** [comment]
The error is that line 76 above should be:
```python
try:
    if name in schema['properties']
       raise ValueError(f"The metadata {name} is reserved for use by tsinfer")
except KeyError:
    pass

As schemas don't have to have properties defined.

**Comment by hyanwong** [comment]
Thanks Ben. The formats.py file says:

```
def permissive_json_schema():
    # A version of this should be in tskit, but we keep it here for now
    # for convenience
    return {
        "codec": "json",
        "type": "object",
        "properties": {},
        "required": [],
        "additionalProperties": True,
    }
```

I'm not sure what the rationale for a different sort of permissive_json_schema in tskit vs tsinfer is? I guess we are happy to leave this here for now, anyway.

**Comment by benjeffery** [comment]
I think that was put in place before tskit had that schema. It should be replaced with the tskit one.

**Comment by benjeffery** [comment]
The tsinfer one is identical for all purposes. Empty list properties works the same as absent for validation.

**Comment by hyanwong** [comment]
I think I need your help here @benjeffery. In particular, in a sample_data file, the metadata schema is stored internally as a dict. Should the getter and setter functions such as

```
sample_data.populations_metadata = x
```

take `x` as a dictionary (or None) or as a tskit.MetadataSchema object? The following line implies the former, but that seems wrong to me:

https://github.com/tskit-dev/tsinfer/blob/d61ae2fa13af2d04516685d9cc510de5ddee1cd2/tests/test_formats.py#L1277

**Comment by hyanwong** [comment]
> I assume they should take the actual object. The property being `None` for legacy compatibility is fine as long as that is interpreted correctly as `tskit.MetadataSchema(None)` at other points.

I've just got back to this. In tskit, something like `type(inferred_ts.table_metadata_schemas.population)` returns tskit.metadata.MetadataSchema, so I suspect we should change the return type of `sample_data.population_metadata_schema` to match this.

**Comment by hyanwong** [comment]
I think we should add this to https://github.com/tskit-dev/tsinfer/milestone/3 - I imagine it is relatively simple to make the switch, and should make any other metadata stuff (e.g. https://github.com/tskit-dev/tsinfer/issues/701) less bespoke.

**Comment by hyanwong** [comment]
> Agreed, easy win.

So do we want to break backwards compatibility and return `tskit.MetadataSchema(None)` from e.g. `sd.population_metadata_schema()` for null schemas, in order to match up with tskit's `ts.table_metadata_schemas.population`?
