### ISSUE TITLE
Document SampleData attributes

### ISSUE THREAD

**Issue by szhan** [tskit-dev/tsinfer#699]
It would be nice to have the data attributes of `SampleData` (e.g. `sites_alleles` and `sites_genotypes`) explained in the online doc. This is a TODO item in the manual "Add documentation for the data attributes in read-mode."

**Comment by hyanwong** [comment]
The underlying arrays may change when using SGkit for SampleData (i.e. for tsinfer version 0.4). When that is settled, we can document any array data subsequently.
