### ISSUE TITLE
ancestor.sites_position[:] confusingly named

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#70]
I think ancestor.sites_position[:] gives a list mapping inferred ancestor indexes to the _true_ ancestor indexes in the tree sequence. calling it "sites_position" implies to me that it maps inference sites to physical positions. Should it be renamed e.g. to sites_index or sites_position_idx something similar?.

**Comment by hyanwong** [comment]
Actually, perhaps *I'm* confused, and it really is a list of explicit physical positions. Sorry. Will double check.

**Comment by jeromekelleher** [comment]
No, it's a list of explicit physical positions for the sites in the ancestors file. In principle it's redundant as you can derive the information from the samples file, but it all gets quite roundabout and confusing, so I thought it was better to put it in and make things a bit easier.

**Comment by hyanwong** [comment]
Yes, sorry, my bad - was old code left over when we set the position as the site index during inference. But now I can't see a way to go from inferred ancestor indexes to the true ancestor indexes in the tree sequence. The ancestors_end[:] etc properties return indexes into the list of sites marked with inference==False. How to I convert this into true site indexes?

**Comment by jeromekelleher** [comment]
All sites in the ancestors file are indexed wrt to the inference sites *only*. The best thing to do is to just translate everything into a physical coordinate with ``sites_position``. So, something like
```
position = ancestors.sites_posititon[:] 
start = ancestors.ancestors_start[:]
end = ancestors.ancestors_end[:]
length = position[end] - position[start]
```
Length is now measured in physical units. Any other way of doing it will be misleading I think.

There probably is code lying around that just takes length as ``end - start`` directly, but this is wrong and should be fixed.

**Comment by hyanwong** [comment]
Right. I started doing that anyway, but good to have it confirmed that this is the way forward. Thanks
