### ISSUE TITLE
Add documentation for the sequence_length argument of SampleData.subset()

### ISSUE THREAD

**Issue by szhan** [tskit-dev/tsinfer#703]
There is no explanation for the argument `sequence_length`.
<img width="788" alt="Screen Shot 2022-08-23 at 1 36 17 PM" src="https://user-images.githubusercontent.com/5580375/186163110-1872e60a-6df9-4a59-8ed5-0efd4bc7fc41.png">

**Comment by hyanwong** [comment]
Ah yes, it's passed to the SampleData constructor, so counts in `**kwargs`. We should redefine the args in the docs to get rid of it.

**Comment by hyanwong** [comment]
Or perhaps document it, since the default is not the same as in the SampleData constructor
