### ISSUE TITLE
Add redirects at Read The Docs

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tsinfer#723]
After #678

**Comment by hyanwong** [comment]
Just a prod to add these redirects when you have time @benjeffery

**Comment by benjeffery** [comment]
I've pushed a `rtd_redirect` branch and have asked RTD to use the to bulid docs as step 1. Step to is to redirect the other pages.

**Comment by benjeffery** [comment]
![Screenshot from 2022-10-21 16-32-59](https://user-images.githubusercontent.com/8552/197233607-75d43d07-c966-4917-94b2-4a1eccb0500e.png)
