### ISSUE TITLE
Get allele frequencies from a Variant object

### ISSUE THREAD

**Issue by szhan** [tskit-dev/tsinfer#724]
I think it could be useful to add a `frequencies()` function to the `Variant` class in `tsinfer`. This would make it more convenient to compare the variants from a `SampleData` object and variants from a `TreeSequence` object. I was doing something like this when processing the FinnGen WGS data.

**Comment by hyanwong** [comment]
You mean to the `SampleData` class. We could do, pending the (distant) move to SGkit, which would presumably make this redundant.

**Comment by jeromekelleher** [comment]
I think we want avoid hanging any more functionality off the SampleData object. Hopefully the sgkit thing actually isn't too far way. I think can see a way forward in which the SampleData object is just a thin wrapper around the sgkit zarr dataset. @benjeffery will be having a look at this in the near future.
