### ISSUE TITLE
Windows install fails because of msprime

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsinfer#751]
We don't have binary wheels for msprime on Windows, and our install is therefore failing on pip (for the reasons that we don't have binary wheels on windows).

This is annoying as we only use msprime to support ratemaps on the command line.

I suggest we remove this feature for 0.3.0 (and the msprime dependency) so that we can get the release out quickly.

@hyanwong, any thoughts?

**Comment by hyanwong** [comment]
We could remove the `--recombination_map` option entirely, or just disable it if msprime is not available to `import`?

**Comment by jeromekelleher** [comment]
Let's remove the``--recombination_map `` entirely for now. Conditional dependencies are a mess and not what we want to introduce as a quick way of getting the release out.

**Comment by hyanwong** [comment]
Disabled in #752. Do we want to leave this issue open or close and open a new one to track getting this in?

In the long term, do we want to 

a) port the rate map code into tsinfer (either directly or via e.g. a submodule)
b) have windows wheels
c) move the rate map class into tskit
d) some other solution?

**Comment by jeromekelleher** [comment]
Let's open a new issue I think. I don't know what the simplest/least bad option is  tbh.

**Comment by jeromekelleher** [comment]
Closed in #752
