### ISSUE TITLE
0.3.0 pypi upload failed

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsinfer#756]
The 0.3.0 release failed to upload to pypi (action [here](https://github.com/tskit-dev/tsinfer/actions/runs/3323713378/jobs/5494505146)). Looks like something to do with Markdown not being supported.

Unsure what the right way to proceed is here, best wait for @benjeffery to weigh in.

``` 
HTTPError: 400 Bad Request from https://test.pypi.org/legacy/          
68
         'text/x-markdown' is an invalid value for Description-Content-Type.    
69
         Error: Invalid description content type: type/subtype is not valid See 
70
         https://packaging.python.org/specifications/core-metadata for more     
71
         information.
```

**Comment by benjeffery** [comment]
How odd, that was copied from other successful actions I think. Will fix it up and deploy.

**Comment by jeromekelleher** [comment]
No rush!

**Comment by benjeffery** [comment]
https://pypi.org/project/tsinfer/0.3.0/

**Comment by jeromekelleher** [comment]
woo, thanks Ben!

**Comment by hyanwong** [comment]
Great, thanks. We can probably merge https://github.com/tskit-dev/tskit-site/pull/134 and announce the release 🎉
