### ISSUE TITLE
ancestor-comparison evaluation doesn't work with error

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsinfer#76]
Various parts of the logic in ancestor-comparison depends on the original tree sequence exactly reflecting the haplotypes, which isn't true when we have error. We definitely need to be able to see the effect of error on these plots, so need to rework a little.

**Comment by hyanwong** [comment]
Good point. Do you want me to look through this?

**Comment by jeromekelleher** [comment]
Yes please; it'd be great if you could fix this issue with a PR.
