### ISSUE TITLE
Output separate pngs rather an multipage pdfs for ancestor-comparison

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsinfer#77]
@hyanwong, it's more convenient to have all the plots in png format.

**Comment by hyanwong** [comment]
Would it not be better to have them all as pdfs (better res for publication etc)?

**Comment by hyanwong** [comment]
Oh, and I find it a pain when I zoom in to pngs and can't see the small detail. Although we could output larger png files, I suppose.

**Comment by jeromekelleher** [comment]
These aren't for publication, so let's not worry about that.

Could make the pngs higher quality, or make them all PDFs. I'd prefer PNGs for this though as they're easier to view when dealing with lots of them. 

But no multi-pages, that just makes things too awkward to compare.

**Comment by jeromekelleher** [comment]
OK, well I'll add a global switch to output PDF/png if it's important to you to use PDF. It's messy outputting both, so either we standardise on PDF, png, or we allow either. I don't want multipage stuff here. I'm not worried other repos, but here I want to be able to quickly scan lots of images and png is much better for this.

**Comment by hyanwong** [comment]
Yep - sounds like a plan. Thanks.
