### ISSUE TITLE
CI: windows tests failing with parallel running

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsinfer#771]
See eg [here](https://github.com/tskit-dev/tsinfer/actions/runs/3422191487/jobs/5699288681)

I thought I'd turned off parallel test running in #769 but it appears not?

The simplest thing is probably to run the tests in sequential mode. Or someone could figure out why tempdir.TemporaryDirectory doesn't seem to be working properly on Windows...

**Comment by benjeffery** [comment]
Ahhh, you need `-n 0` as https://github.com/tskit-dev/tsinfer/blob/main/setup.cfg#L68 defaults testing to `-n 4`

**Comment by jeromekelleher** [comment]
Sigh, still failing: https://github.com/tskit-dev/tsinfer/actions/runs/3435485226/jobs/5727901725

**Comment by benjeffery** [comment]
We run the tests in serial now, so hopefully this doesn't occur again.
