### ISSUE TITLE
sgkit: Error/Warning on unphased data when ploidy > 1.

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tsinfer#772]
I'm leaning towards this being an error - with an override flag, unless there are arguments for this being a warning?

**Comment by hyanwong** [comment]
Error with override, I think. Warnings are too easy to ignore, and unphased data completely breaks the assumptions.

**Comment by hyanwong** [comment]
(I think the override is an optional nicety too, FWIW)

**Comment by jeromekelleher** [comment]
SGTM

An alternative to override would be to point people in the direction of phasing docs in sgkit and to say "you can force the phasing like this, but beware!"
