### ISSUE TITLE
Change SgkitSampleData to accept a path or store.

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tsinfer#783]
The API for this currently only accepts a path. It would be better if it accepted either a path or a zarr store as an argument. For example, allowing the user to pass in a zarr store would make it easier to use the SgkitSampleData class with zarr data that has been stored in memory or in some other non-file-based storage system.

**Comment by benjeffery** [comment]
Could also directly take an sgkit or xarray dataset?

**Comment by jeromekelleher** [comment]
Seems reasonable - I figure there'll be a bunch of QC steps first on the sgkit dataset before passing in, so users will be aware of sgkit much more than zarr.

**Comment by hyanwong** [comment]
Fixed in 788d4dfdd09c3f552c8b5e17b67218245f4cf46f
