### ISSUE TITLE
Circle CI failure

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tsinfer#790]
`ImportError: cannot import name 'Ttest_1sampResult' from 'scipy.stats.stats'`

**Comment by benjeffery** [comment]
https://app.circleci.com/pipelines/github/tskit-dev/tsinfer/1336/workflows/c923a1da-4d9e-4e36-a1a3-4548c988cbe0/jobs/1893

**Comment by jeromekelleher** [comment]
Dask/sgkit problem?
