### ISSUE TITLE
Installation currently fails under python 3.11 due to numba dep

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#796]
One of the packages in `requirements/development.txt` depends on numba which hasn't yet been updated to work with Python 3.11. I guess we should pin to 3.10 for the time being and leave this issue open until numba is fixed.

**Comment by benjeffery** [comment]
Not long now as it is in testing: https://github.com/numba/numba/issues/8304#issuecomment-1353448183
