### ISSUE TITLE
Package tsinfer for pyodide

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tsinfer#821]

**Comment by benjeffery** [comment]
Started on this with the dependancies - lmdb is in progress and seems to work: https://github.com/pyodide/pyodide/pull/3842

**Comment by hyanwong** [comment]
Nice, thanks Ben.

**Comment by hyanwong** [comment]
Oh yuck, sorry. Is there any short-term workaround instead (e.g. make emscripten lmbd & tsinfer wheels and don't worry about passing multithreaded tests?)

**Comment by benjeffery** [comment]
A very basic test fails, this is not to do with multi-threading. The only way to get around this would be to make lmdb an optional dependancy in tsinfer.

**Comment by hyanwong** [comment]
Ah, bugger. Seems like we are a bit snookered then. Sorry to send you down a blind alley. Any further suggestion welcome, though.

**Comment by jeromekelleher** [comment]
That's totally not worth it - let's park this.

**Comment by hyanwong** [comment]
Sure. I guess we'll need to get a docker version up for the June practical, and cross our fingers that it will work OK this time.

**Comment by jeromekelleher** [comment]
I don't think we have a choice here Yan, packaging upstream components is much more time consuming and risky

**Comment by hyanwong** [comment]
Yes, hopefully someone else will sort out something that will work for this in the future. Not worth spending excess time on it now since lots of pyodide is a "work in progress".
