### ISSUE TITLE
Store resume buffer of match results

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsinfer#826]
As an alternative to #825 and #793, we could keep an LMBD which maps the keys (child node IDs) to their results. The ``_find_path`` function should check this (if it's enabled?) and if the result exists we return that instead of running the match.

This should give us a pragmatic way of restarting long running computations.

**Comment by benjeffery** [comment]
I think we'll also need to cache the epoch calculations, as this can take a while with the new level order code.

**Comment by jeromekelleher** [comment]
That can probably be done much more efficiently I think, just needs a standard line-sweep algorithm? Let's get this working with just integer epoch IDs first and worry about doing the level ordering stuff afterwards.
