### ISSUE TITLE
Tutorial on creating Sample File from VCF giving error

### ISSUE THREAD

**Issue by Tatianabellagio** [tskit-dev/tsinfer#841]
Hi, I tried running the code on the [tutorial](https://tskit.dev/tsinfer/docs/stable/tutorial.html#data-example:~:text=VCF%20reading%20library.-,Reading%20a%20VCF,-%23) and got the error:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[3], line 59
     56 with tsinfer.SampleData(
     57     path="P_dom_chr24_phased.samples", sequence_length=chromosome_length(vcf)
     58 ) as samples:
---> 59     add_diploid_sites(vcf, samples)
     61 print(
     62     "Sample file created for {} samples ".format(samples.num_samples)
     63     + "({} individuals) ".format(samples.num_individuals)
     64     + "with {} variable sites.".format(samples.num_sites),
     65     flush=True,
     66 )

Cell In[3], line 15, in add_diploid_sites(vcf, samples)
     14 print(pos)
---> 15 progressbar = tqdm(total=samples.sequence_length, desc="Read VCF", unit='bp')
     16 print(progressbar)

NameError: name 'tqdm' is not defined

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
Cell In[3], line 59
...
-> 1912         raise ValueError("Must add at least one sample individual")
   1913     elif self._build_state == self.ADDING_SAMPLES:
   1914         self._individuals_writer.flush()

ValueError: Must add at least one sample individual 

```

I ran it with my own vcf file, got the error, and then ran it with the data from the tutorial [at](https://github.com/tskit-dev/tsinfer/raw/main/docs/_static/P_dom_chr24_phased.vcf.gz) and got the same error. 

Also, it would be really useful if you could document the format of Sample File [here](https://tskit.dev/tsinfer/docs/stable/file_formats.html#sec-file-formats-samples:~:text=of%20these%20files.-,Samples%20File,-%23) so that I could just create it myself. Maybe a sample of how that file should look like would also be great.

Thanks a lot for all your efforts!

**Comment by Tatianabellagio** [comment]
ok, I did:
` from tqdm import tqdm `
and it worked.
But that was not stated in the import vcf part so it might be useful to either add or get a more informative error.
Thanks a lot!
Tati

**Comment by hyanwong** [comment]
Ah yes, thanks for pointing that out. It's at the top of the page, not in that section of code, which as you say, might be a bit confusing.

However, we are about to release a new version of tsinfer that will allow importing from VCF in a more flexible manner, via [SGkit](https://pystatgen.github.io/sgkit/latest/), so I think this tutorial will be made obsolete soon anyway...

**Comment by Tatianabellagio** [comment]
Oh great! Just FYI the same happened with 
`from tskit import MISSING_DATA`
But yes makes sense to not bother if it is gonna be changed soon!
Great job 
Best
Tati

**Comment by hyanwong** [comment]
Thanks. Yes, the examples are run as a bit notebook, so some of the required imports and definitions might not be in the same cell, but in previous cells. This can get a bit confusing, sorry!

**Comment by bekirsch** [comment]
Hi, although the issue is reported as closed this is still confusing when running the tutorial from [here](https://tskit.dev/tsinfer/docs/stable/tutorial.html#reading-a-vcf). For the example to work, the code snippet should include `from tqdm import tqdm`
and a lot of VCFs will need `from tskit import MISSING_DATA`.

Anyway, great software, just wanted to let you know.
Cheers
Bene

**Comment by hyanwong** [comment]
Hi Bene - thanks for the report.

> Hi, although the issue is reported as closed this is still confusing when running the tutorial from [here](https://tskit.dev/tsinfer/docs/stable/tutorial.html#reading-a-vcf). 

Ah yes, the required imports are one of the cells higher up. However, they are a bit complicated, which is why re-importing was avoided

We are likely to move away from this bespoke import script anyway, and move to using SGkit instead, so it may not be worth addressing this point until that's done.
