### ISSUE TITLE
Ancestral allele handling

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tsinfer#846]
@hyanwong and I sat down and tried to think through properly how ancestral allele handling from sgkit should work.

The sgkit `variant_ancestral_allele` string array needs to be converted to a numeric allele index by tsinfer's `SgkitSampleData`.
Currently, this is done in a strict way, where an error is thrown if the ancestral allele is absent from the sites' allele list. This is not ideal as sites with missing or absent ancestral alleles should be placed with parsimony. In the case of missing ancestral this should be parsimony that chooses the most parsimonious allele for the ancestral state, and for absent ancestral alleles this should be parsimony with the absent allele as the ancestral state.

So these points need fixing:
 - Sites where the ancestral allele is missing (e.g `N`, `-` or `.`) should be interpreted by tsinfer as `-1` such that later on the site gets a parsimonious ancestral allele.
 - Sites where the ancestral allele is not in the "missing list" or in the sites' allele list should get added to the site's allele list so that tsinfer sees the site as triallelic and places it with parsimony. We can't edit the alleles list in the sgkit dataset so we'll do it in RAM in tsinfer.
 
I suggest we raise a warning with the total number and state of absent alleles as if the user has an ancestral sequence with upper and lower case, the case that doesn't match the alleles will be seen as absent.

**Comment by hyanwong** [comment]
Yes, that's exactly it

> Sites where the ancestral allele is not in the "missing list" or in the sites' allele list should get added to the site's allele list so that tsinfer sees the site as triallelic and places it with parsimony

More specifically, so that the ancestral state is *not* chosen by parsimony, but the distribution of alleles under that site *is* chosen by parsimony (and not used for inference)

**Comment by hyanwong** [comment]
I think all the items in this issue are now addressed, are they @benjeffery? If so, I presume we can close this issue.
