### ISSUE TITLE
Hard error on missing sgkit ancestral state

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tsinfer#847]
Currently, we raise a warning on missing ancestral state. I think this should be a hard error as the warning is easily missed and the resulting tree sequence will be pretty much garbage. The use of the zeroth allele is a legacy hangover from early tsinfer days - if the user really wants to do that they can specify and ancestral state array which contains the zeroth allele for each site.

**Comment by hyanwong** [comment]
It might be useful in the docstring to give an example of passing the first (ref) allele as the ancestral state (or have a shorthand param setting to state this?)
