### ISSUE TITLE
Ancestral alleles from VCF

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#848]
Probably an SGkit issue, but I'm not sure of the status of ancestral allele encoding in the SGkit repo.

There is an INFO field in the VCF which can contain one (or weirdly, more) ancestral alleles. If would be useful to be able to read these into the SGkit dataset. See the example code at https://tskit.dev/tsinfer/docs/stable/tutorial.html#data-example which is intended to read in (e.g.) 1000G VCFs with AA defined.

Please transfer this issue to the right place in SGkit if appropriate @benjeffery .

**Comment by benjeffery** [comment]
I think sgkit can already read in this info - it will then be a couple of lines to get it in a state for tsinfer. Leaving this open till we get those lines in a tutorial.

**Comment by hyanwong** [comment]
This is in https://tskit.dev/tsinfer/docs/latest/usage.html#variantdata-and-ancestral-alleles now
