### ISSUE TITLE
polytomies

### ISSUE THREAD

**Issue by frezaei98** [tskit-dev/tsinfer#868]
Hello, 
 Can polytomies be present in the inferred trees generated by tsinfer?  If not, how does tsinfer ensure no polytomies?

**Comment by hyanwong** [comment]
Hi - yes, polytomies are often generated by tsinfer. See e.g. https://tskit.dev/tsinfer/docs/stable/tutorial.html#toy-example

Tskit gives a tree-by-tree way of breaking polytomies in https://tskit.dev/tskit/docs/stable/python-api.html#tskit.Tree.split_polytomies
