### ISSUE TITLE
Compilation overrides CC

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#904]
I'm trying to compile `tsinfer` on OSX with the conda compilers. The problem is that these don't always install a symlink for gcc. However, they do define the correct `CC` environment variable.

In the tsinfer Makefile, we currently set `CC=gcc`:

https://github.com/tskit-dev/tsinfer/blob/e99a3dc4dec27459c84a374ecf2c398f38f48511/Makefile#L1

Is there any reason why we can't instead say

```
CC?=gcc
```

so that if CC is already defined, we don;'t overwrite it? This would help proper compilation with conda in my system (I don't know why this has recently stopped working)?

**Comment by jeromekelleher** [comment]
Sure, give it a go.
