### ISSUE TITLE
Tests don't work unless you install the package

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#907]
If I clone the git repo in a new python environment, go to the top-level `tsinfer` directory, type `make`, and then `pytest`, I get

```
tsinfer % pytest
ImportError while loading conftest '/Users/yan/Documents/GitHub/tsinfer/tests/conftest.py'.
tests/conftest.py:45: in <module>
    import tsinfer
E   ModuleNotFoundError: No module named 'tsinfer'
```

I think most of the tskit packages allow tests to be run from the root directory, don't they? This is helpful for testing, to make sure you are using the current codebase rather than any old installed one for testing.

**Comment by jeromekelleher** [comment]
This is surprising - is this because of the pytest fixtures doing something unexpected with the environment? We definitely don't want fixtures based on the installed version.

I'm not generally a fan of these global fixture anyway.

**Comment by hyanwong** [comment]
Aha, I think it's because I used `pytest` rather than `python -m pytest`. See https://docs.pytest.org/en/7.1.x/explanation/pythonpath.html#invoking-pytest-versus-python-m-pytest. So I think we can close this.
