### ISSUE TITLE
Grep for "sgkit" in names and replace

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsinfer#934]
We're using "sgkit" in a few places where we mean the underlying VCF Zarr representation (e.g. ``sgkit_samples_mask_name`` in #917). Search for these and replace with something appropriate.

**Comment by hyanwong** [comment]
I believe that apart from in the test suite, the only place where the work "sgkit" is now exposed is here: https://github.com/tskit-dev/tsinfer/blob/738bd13d531cbb2188b5fefabc6fb2e5879e16a4/tsinfer/formats.py#L2297

**Comment by hyanwong** [comment]
Fixed in #961
