### ISSUE TITLE
Typo in formats.VariantData.individuals_metadata?

### ISSUE THREAD

**Issue by percyfal** [tskit-dev/tsinfer#948]
In figuring out how to add metadata to individuals, I noticed that formats.VariantData.individuals_metadata loads the population_metadata_schema (cf https://github.com/tskit-dev/tsinfer/blob/db448b6da0253bfed4c703f2ad511824832baac4/tsinfer/formats.py#L2608-L2609). Typo?

**Comment by benjeffery** [comment]
Thanks, will fix - not sure how the tests miss that but will add a test too.

**Comment by hyanwong** [comment]
This is why we released an alpha! Thanks for picking up on that @percyfal.
