### ISSUE TITLE
Do not warn about unknown states if ancestral allele is "N"

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#962]
In #960 @benjeffery said:

> This has made me realise the vcfzarr spec should probably be more explicit that zero-length alleles are not allowed. It is currently there as implicit as it states "" is a fill value.

In that case, I presume that we can always assume that an ancestral allele of `""` means "intentionally marked as unknown", so that we can recommend that people use that to mark sites of unknown ancestral allele. Furthermore, I suspect that means we can exclude such alleles from the "warning" output that normally says:

```
An ancestral allele was not found in the variant_allele array for the {tot} sites ({frac_bad * 100 :.2f}%) listed below.
```

?

**Comment by hyanwong** [comment]
Revised in the light of discussions in #963 so that "N" should be the "deliberately unknown" state. We still want to treat "" as unknown, but this is more likely to be accidental.

**Comment by benjeffery** [comment]
Yeah, I think you're right that we shouldn't warn on `N`
